package edu.ksu.cis.bandera.specification.predicate.lexer;

/* This file was generated by SableCC (http://www.sablecc.org/). */

public class LexerException extends Exception
{
	public LexerException(String message)
	{
		super(message);
	}
}
