/* This file was generated by SableCC (http://www.sablecc.org/). */

package edu.ksu.cis.bandera.birp.lexer;

public class LexerException extends Exception
{
    public LexerException(String message)
    {
        super(message);
    }
}
