package edu.ksu.cis.bandera.abstraction.pvs;

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Bandera, a Java(TM) analysis and transformation toolkit           *
 * Copyright (C) 1998-2001 SAnToS Laboratories (santos@cis.ksu.edu)  *

 * All rights reserved.                                              *
 *                                                                   *
 * This work was done as a project in the SAnToS Laboratory,         *
 * Department of Computing and Information Sciences, Kansas State    *
 * University, USA (http://www.cis.ksu.edu/santos).                  *
 * It is understood that any modification not identified as such is  *
 * not covered by the preceding statement.                           *
 *                                                                   *
 * This work is free software; you can redistribute it and/or        *
 * modify it under the terms of the GNU Library General Public       *
 * License as published by the Free Software Foundation; either      *
 * version 2 of the License, or (at your option) any later version.  *
 *                                                                   *
 * This work is distributed in the hope that it will be useful,      *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of    *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU *
 * Library General Public License for more details.                  *
 *                                                                   *
 * You should have received a copy of the GNU Library General Public *
 * License along with this toolkit; if not, write to the             *
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,      *
 * Boston, MA  02111-1307, USA.                                      *
 *                                                                   *
 * Java is a trademark of Sun Microsystems, Inc.                     *
 *                                                                   *
 * To submit a bug report, send a comment, or get the latest news on *
 * this project and other SAnToS projects, please visit the web-site *
 *                http://www.cis.ksu.edu/santos                      *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Sep 29 14:44:06 CDT 2000
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EQ = 11;
  public static final int BEGIN = 21;
  public static final int EXTENDS = 25;
  public static final int PLUS = 3;
  public static final int MINUS = 4;
  public static final int GT = 15;
  public static final int NE = 10;
  public static final int TIMES = 5;
  public static final int NUMBER = 33;
  public static final int SEMI = 2;
  public static final int LBRACE = 31;
  public static final int ABSTRACTION = 24;
  public static final int MOD = 7;
  public static final int EQUAL = 29;
  public static final int COMMA = 32;
  public static final int LPAREN = 18;
  public static final int FLOAT = 27;
  public static final int GE = 13;
  public static final int EOF = 0;
  public static final int ABSTRACT = 23;
  public static final int error = 1;
  public static final int INT = 26;
  public static final int ARROW = 17;
  public static final int DIV = 6;
  public static final int UMINUS = 20;
  public static final int NOT = 16;
  public static final int RBRACE = 30;
  public static final int RPAREN = 19;
  public static final int LT = 14;
  public static final int END = 22;
  public static final int ID = 34;
  public static final int AND = 8;
  public static final int OR = 9;
  public static final int LE = 12;
  public static final int TOKENS = 28;
}
