package edu.ksu.cis.bandera.abstraction.options.node;

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Bandera, a Java(TM) analysis and transformation toolkit           *
 * Copyright (C) 1998-2001 SAnToS Laboratories (santos@cis.ksu.edu)  *

 * All rights reserved.                                              *
 *                                                                   *
 * This work was done as a project in the SAnToS Laboratory,         *
 * Department of Computing and Information Sciences, Kansas State    *
 * University, USA (http://www.cis.ksu.edu/santos).                  *
 * It is understood that any modification not identified as such is  *
 * not covered by the preceding statement.                           *
 *                                                                   *
 * This work is free software; you can redistribute it and/or        *
 * modify it under the terms of the GNU Library General Public       *
 * License as published by the Free Software Foundation; either      *
 * version 2 of the License, or (at your option) any later version.  *
 *                                                                   *
 * This work is distributed in the hope that it will be useful,      *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of    *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU *
 * Library General Public License for more details.                  *
 *                                                                   *
 * You should have received a copy of the GNU Library General Public *
 * License along with this toolkit; if not, write to the             *
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,      *
 * Boston, MA  02111-1307, USA.                                      *
 *                                                                   *
 * Java is a trademark of Sun Microsystems, Inc.                     *
 *                                                                   *
 * To submit a bug report, send a comment, or get the latest news on *
 * this project and other SAnToS projects, please visit the web-site *
 *                http://www.cis.ksu.edu/santos                      *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/* This file was generated by SableCC (http://www.sable.mcgill.ca/sablecc/). */

import java.util.*;
import edu.ksu.cis.bandera.abstraction.options.analysis.*;

public final class AClassOption extends PClassOption
{
	private TCls _cls_;
	private PName _name_;
	private TLBrace _lBrace_;
	private final LinkedList _fieldOption_ = new TypedLinkedList(new FieldOption_Cast());
	private final LinkedList _methodOption_ = new TypedLinkedList(new MethodOption_Cast());
	private TRBrace _rBrace_;

	private class FieldOption_Cast implements Cast
	{
		public Object cast(Object o)
		{
			PFieldOption node = (PFieldOption) o;

			if((node.parent() != null) &&
				(node.parent() != AClassOption.this))
			{
				node.parent().removeChild(node);
			}

			if((node.parent() == null) ||
				(node.parent() != AClassOption.this))
			{
				node.parent(AClassOption.this);
			}

			return node;
		}
	}

	private class MethodOption_Cast implements Cast
	{
		public Object cast(Object o)
		{
			PMethodOption node = (PMethodOption) o;

			if((node.parent() != null) &&
				(node.parent() != AClassOption.this))
			{
				node.parent().removeChild(node);
			}

			if((node.parent() == null) ||
				(node.parent() != AClassOption.this))
			{
				node.parent(AClassOption.this);
			}

			return node;
		}
	}
	public AClassOption()
	{
	}
	public AClassOption(
		TCls _cls_,
		PName _name_,
		TLBrace _lBrace_,
		XPFieldOption _fieldOption_,
		XPMethodOption _methodOption_,
		TRBrace _rBrace_)
	{
		setCls(_cls_);

		setName(_name_);

		setLBrace(_lBrace_);

		if(_fieldOption_ != null)
		{
			while(_fieldOption_ instanceof X1PFieldOption)
			{
				this._fieldOption_.addFirst(((X1PFieldOption) _fieldOption_).getPFieldOption());
				_fieldOption_ = ((X1PFieldOption) _fieldOption_).getXPFieldOption();
			}
			this._fieldOption_.addFirst(((X2PFieldOption) _fieldOption_).getPFieldOption());
		}

		if(_methodOption_ != null)
		{
			while(_methodOption_ instanceof X1PMethodOption)
			{
				this._methodOption_.addFirst(((X1PMethodOption) _methodOption_).getPMethodOption());
				_methodOption_ = ((X1PMethodOption) _methodOption_).getXPMethodOption();
			}
			this._methodOption_.addFirst(((X2PMethodOption) _methodOption_).getPMethodOption());
		}

		setRBrace(_rBrace_);

	}
	public AClassOption(
		TCls _cls_,
		PName _name_,
		TLBrace _lBrace_,
		List _fieldOption_,
		List _methodOption_,
		TRBrace _rBrace_)
	{
		setCls(_cls_);

		setName(_name_);

		setLBrace(_lBrace_);

		{
			Object temp[] = _fieldOption_.toArray();
			for(int i = 0; i < temp.length; i++)
			{
				this._fieldOption_.add(temp[i]);
			}
		}

		{
			Object temp[] = _methodOption_.toArray();
			for(int i = 0; i < temp.length; i++)
			{
				this._methodOption_.add(temp[i]);
			}
		}

		setRBrace(_rBrace_);

	}
	public void apply(Switch sw)
	{
		((Analysis) sw).caseAClassOption(this);
	}
	public Object clone()
	{
		return new AClassOption(
			(TCls) cloneNode(_cls_),
			(PName) cloneNode(_name_),
			(TLBrace) cloneNode(_lBrace_),
			cloneList(_fieldOption_),
			cloneList(_methodOption_),
			(TRBrace) cloneNode(_rBrace_));
	}
	public TCls getCls()
	{
		return _cls_;
	}
	public LinkedList getFieldOption()
	{
		return _fieldOption_;
	}
	public TLBrace getLBrace()
	{
		return _lBrace_;
	}
	public LinkedList getMethodOption()
	{
		return _methodOption_;
	}
	public PName getName()
	{
		return _name_;
	}
	public TRBrace getRBrace()
	{
		return _rBrace_;
	}
	void removeChild(Node child)
	{
		if(_cls_ == child)
		{
			_cls_ = null;
			return;
		}

		if(_name_ == child)
		{
			_name_ = null;
			return;
		}

		if(_lBrace_ == child)
		{
			_lBrace_ = null;
			return;
		}

		if(_fieldOption_.remove(child))
		{
			return;
		}

		if(_methodOption_.remove(child))
		{
			return;
		}

		if(_rBrace_ == child)
		{
			_rBrace_ = null;
			return;
		}

	}
	void replaceChild(Node oldChild, Node newChild)
	{
		if(_cls_ == oldChild)
		{
			setCls((TCls) newChild);
			return;
		}

		if(_name_ == oldChild)
		{
			setName((PName) newChild);
			return;
		}

		if(_lBrace_ == oldChild)
		{
			setLBrace((TLBrace) newChild);
			return;
		}

		for(ListIterator i = _fieldOption_.listIterator(); i.hasNext();)
		{
			if(i.next() == oldChild)
			{
				if(newChild != null)
				{
					i.set(newChild);
					oldChild.parent(null);
					return;
				}

				i.remove();
				oldChild.parent(null);
				return;
			}
		}

		for(ListIterator i = _methodOption_.listIterator(); i.hasNext();)
		{
			if(i.next() == oldChild)
			{
				if(newChild != null)
				{
					i.set(newChild);
					oldChild.parent(null);
					return;
				}

				i.remove();
				oldChild.parent(null);
				return;
			}
		}

		if(_rBrace_ == oldChild)
		{
			setRBrace((TRBrace) newChild);
			return;
		}

	}
	public void setCls(TCls node)
	{
		if(_cls_ != null)
		{
			_cls_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_cls_ = node;
	}
	public void setFieldOption(List list)
	{
		Object temp[] = list.toArray();
		for(int i = 0; i < temp.length; i++)
		{
			_fieldOption_.add(temp[i]);
		}
	}
	public void setLBrace(TLBrace node)
	{
		if(_lBrace_ != null)
		{
			_lBrace_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_lBrace_ = node;
	}
	public void setMethodOption(List list)
	{
		Object temp[] = list.toArray();
		for(int i = 0; i < temp.length; i++)
		{
			_methodOption_.add(temp[i]);
		}
	}
	public void setName(PName node)
	{
		if(_name_ != null)
		{
			_name_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_name_ = node;
	}
	public void setRBrace(TRBrace node)
	{
		if(_rBrace_ != null)
		{
			_rBrace_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_rBrace_ = node;
	}
	public String toString()
	{
		return ""
			+ toString(_cls_)
			+ toString(_name_)
			+ toString(_lBrace_)
			+ toString(_fieldOption_)
			+ toString(_methodOption_)
			+ toString(_rBrace_);
	}
}
