package edu.ksu.cis.bandera.abstraction.options.node;

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Bandera, a Java(TM) analysis and transformation toolkit           *
 * Copyright (C) 1998-2001 SAnToS Laboratories (santos@cis.ksu.edu)  *

 * All rights reserved.                                              *
 *                                                                   *
 * This work was done as a project in the SAnToS Laboratory,         *
 * Department of Computing and Information Sciences, Kansas State    *
 * University, USA (http://www.cis.ksu.edu/santos).                  *
 * It is understood that any modification not identified as such is  *
 * not covered by the preceding statement.                           *
 *                                                                   *
 * This work is free software; you can redistribute it and/or        *
 * modify it under the terms of the GNU Library General Public       *
 * License as published by the Free Software Foundation; either      *
 * version 2 of the License, or (at your option) any later version.  *
 *                                                                   *
 * This work is distributed in the hope that it will be useful,      *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of    *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU *
 * Library General Public License for more details.                  *
 *                                                                   *
 * You should have received a copy of the GNU Library General Public *
 * License along with this toolkit; if not, write to the             *
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,      *
 * Boston, MA  02111-1307, USA.                                      *
 *                                                                   *
 * Java is a trademark of Sun Microsystems, Inc.                     *
 *                                                                   *
 * To submit a bug report, send a comment, or get the latest news on *
 * this project and other SAnToS projects, please visit the web-site *
 *                http://www.cis.ksu.edu/santos                      *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/* This file was generated by SableCC (http://www.sable.mcgill.ca/sablecc/). */

import java.util.*;
import edu.ksu.cis.bandera.abstraction.options.analysis.*;

public final class AMethodOption extends PMethodOption
{
	private TId _id_;
	private TLParen _lParen_;
	private PParams _params_;
	private TRParen _rParen_;
	private TLBrace _lBrace_;
	private final LinkedList _localOption_ = new TypedLinkedList(new LocalOption_Cast());
	private TRBrace _rBrace_;

	private class LocalOption_Cast implements Cast
	{
		public Object cast(Object o)
		{
			PLocalOption node = (PLocalOption) o;

			if((node.parent() != null) &&
				(node.parent() != AMethodOption.this))
			{
				node.parent().removeChild(node);
			}

			if((node.parent() == null) ||
				(node.parent() != AMethodOption.this))
			{
				node.parent(AMethodOption.this);
			}

			return node;
		}
	}
	public AMethodOption()
	{
	}
	public AMethodOption(
		TId _id_,
		TLParen _lParen_,
		PParams _params_,
		TRParen _rParen_,
		TLBrace _lBrace_,
		XPLocalOption _localOption_,
		TRBrace _rBrace_)
	{
		setId(_id_);

		setLParen(_lParen_);

		setParams(_params_);

		setRParen(_rParen_);

		setLBrace(_lBrace_);

		if(_localOption_ != null)
		{
			while(_localOption_ instanceof X1PLocalOption)
			{
				this._localOption_.addFirst(((X1PLocalOption) _localOption_).getPLocalOption());
				_localOption_ = ((X1PLocalOption) _localOption_).getXPLocalOption();
			}
			this._localOption_.addFirst(((X2PLocalOption) _localOption_).getPLocalOption());
		}

		setRBrace(_rBrace_);

	}
	public AMethodOption(
		TId _id_,
		TLParen _lParen_,
		PParams _params_,
		TRParen _rParen_,
		TLBrace _lBrace_,
		List _localOption_,
		TRBrace _rBrace_)
	{
		setId(_id_);

		setLParen(_lParen_);

		setParams(_params_);

		setRParen(_rParen_);

		setLBrace(_lBrace_);

		{
			Object temp[] = _localOption_.toArray();
			for(int i = 0; i < temp.length; i++)
			{
				this._localOption_.add(temp[i]);
			}
		}

		setRBrace(_rBrace_);

	}
	public void apply(Switch sw)
	{
		((Analysis) sw).caseAMethodOption(this);
	}
	public Object clone()
	{
		return new AMethodOption(
			(TId) cloneNode(_id_),
			(TLParen) cloneNode(_lParen_),
			(PParams) cloneNode(_params_),
			(TRParen) cloneNode(_rParen_),
			(TLBrace) cloneNode(_lBrace_),
			cloneList(_localOption_),
			(TRBrace) cloneNode(_rBrace_));
	}
	public TId getId()
	{
		return _id_;
	}
	public TLBrace getLBrace()
	{
		return _lBrace_;
	}
	public LinkedList getLocalOption()
	{
		return _localOption_;
	}
	public TLParen getLParen()
	{
		return _lParen_;
	}
	public PParams getParams()
	{
		return _params_;
	}
	public TRBrace getRBrace()
	{
		return _rBrace_;
	}
	public TRParen getRParen()
	{
		return _rParen_;
	}
	void removeChild(Node child)
	{
		if(_id_ == child)
		{
			_id_ = null;
			return;
		}

		if(_lParen_ == child)
		{
			_lParen_ = null;
			return;
		}

		if(_params_ == child)
		{
			_params_ = null;
			return;
		}

		if(_rParen_ == child)
		{
			_rParen_ = null;
			return;
		}

		if(_lBrace_ == child)
		{
			_lBrace_ = null;
			return;
		}

		if(_localOption_.remove(child))
		{
			return;
		}

		if(_rBrace_ == child)
		{
			_rBrace_ = null;
			return;
		}

	}
	void replaceChild(Node oldChild, Node newChild)
	{
		if(_id_ == oldChild)
		{
			setId((TId) newChild);
			return;
		}

		if(_lParen_ == oldChild)
		{
			setLParen((TLParen) newChild);
			return;
		}

		if(_params_ == oldChild)
		{
			setParams((PParams) newChild);
			return;
		}

		if(_rParen_ == oldChild)
		{
			setRParen((TRParen) newChild);
			return;
		}

		if(_lBrace_ == oldChild)
		{
			setLBrace((TLBrace) newChild);
			return;
		}

		for(ListIterator i = _localOption_.listIterator(); i.hasNext();)
		{
			if(i.next() == oldChild)
			{
				if(newChild != null)
				{
					i.set(newChild);
					oldChild.parent(null);
					return;
				}

				i.remove();
				oldChild.parent(null);
				return;
			}
		}

		if(_rBrace_ == oldChild)
		{
			setRBrace((TRBrace) newChild);
			return;
		}

	}
	public void setId(TId node)
	{
		if(_id_ != null)
		{
			_id_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_id_ = node;
	}
	public void setLBrace(TLBrace node)
	{
		if(_lBrace_ != null)
		{
			_lBrace_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_lBrace_ = node;
	}
	public void setLocalOption(List list)
	{
		Object temp[] = list.toArray();
		for(int i = 0; i < temp.length; i++)
		{
			_localOption_.add(temp[i]);
		}
	}
	public void setLParen(TLParen node)
	{
		if(_lParen_ != null)
		{
			_lParen_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_lParen_ = node;
	}
	public void setParams(PParams node)
	{
		if(_params_ != null)
		{
			_params_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_params_ = node;
	}
	public void setRBrace(TRBrace node)
	{
		if(_rBrace_ != null)
		{
			_rBrace_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_rBrace_ = node;
	}
	public void setRParen(TRParen node)
	{
		if(_rParen_ != null)
		{
			_rParen_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_rParen_ = node;
	}
	public String toString()
	{
		return ""
			+ toString(_id_)
			+ toString(_lParen_)
			+ toString(_params_)
			+ toString(_rParen_)
			+ toString(_lBrace_)
			+ toString(_localOption_)
			+ toString(_rBrace_);
	}
}
