package edu.ksu.cis.bandera.abstraction.options.node;

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Bandera, a Java(TM) analysis and transformation toolkit           *
 * Copyright (C) 1998-2001 SAnToS Laboratories (santos@cis.ksu.edu)  *

 * All rights reserved.                                              *
 *                                                                   *
 * This work was done as a project in the SAnToS Laboratory,         *
 * Department of Computing and Information Sciences, Kansas State    *
 * University, USA (http://www.cis.ksu.edu/santos).                  *
 * It is understood that any modification not identified as such is  *
 * not covered by the preceding statement.                           *
 *                                                                   *
 * This work is free software; you can redistribute it and/or        *
 * modify it under the terms of the GNU Library General Public       *
 * License as published by the Free Software Foundation; either      *
 * version 2 of the License, or (at your option) any later version.  *
 *                                                                   *
 * This work is distributed in the hope that it will be useful,      *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of    *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU *
 * Library General Public License for more details.                  *
 *                                                                   *
 * You should have received a copy of the GNU Library General Public *
 * License along with this toolkit; if not, write to the             *
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,      *
 * Boston, MA  02111-1307, USA.                                      *
 *                                                                   *
 * Java is a trademark of Sun Microsystems, Inc.                     *
 *                                                                   *
 * To submit a bug report, send a comment, or get the latest news on *
 * this project and other SAnToS projects, please visit the web-site *
 *                http://www.cis.ksu.edu/santos                      *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/* This file was generated by SableCC (http://www.sable.mcgill.ca/sablecc/). */

import edu.ksu.cis.bandera.abstraction.options.analysis.*;

public final class X1TDim extends XTDim
{
	private XTDim _xTDim_;
	private TDim _tDim_;

	public X1TDim()
	{
	}
	public X1TDim(
		XTDim _xTDim_,
		TDim _tDim_)
	{
		setXTDim(_xTDim_);
		setTDim(_tDim_);
	}
	public void apply(Switch sw)
	{
		throw new RuntimeException("Switch not supported.");
	}
	public Object clone()
	{
		throw new RuntimeException("Unsupported Operation");
	}
	public TDim getTDim()
	{
		return _tDim_;
	}
	public XTDim getXTDim()
	{
		return _xTDim_;
	}
	void removeChild(Node child)
	{
		if(_xTDim_ == child)
		{
			_xTDim_ = null;
		}

		if(_tDim_ == child)
		{
			_tDim_ = null;
		}
	}
	void replaceChild(Node oldChild, Node newChild)
	{
	}
	public void setTDim(TDim node)
	{
		if(_tDim_ != null)
		{
			_tDim_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_tDim_ = node;
	}
	public void setXTDim(XTDim node)
	{
		if(_xTDim_ != null)
		{
			_xTDim_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_xTDim_ = node;
	}
	public String toString()
	{
		return "" +
			toString(_xTDim_) +
			toString(_tDim_);
	}
}
