package edu.ksu.cis.bandera.specification.predicate.parser;

/* This file was generated by SableCC (http://www.sablecc.org/). */

final class State
{
	int state;
	Object node;

	State(int state, Object node)
	{
		this.state = state;
		this.node = node;
	}
}
