package edu.ksu.cis.bandera.abstraction.specification.node;

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Bandera, a Java(TM) analysis and transformation toolkit           *
 * Copyright (C) 1998-2001 SAnToS Laboratories (santos@cis.ksu.edu)  *

 * All rights reserved.                                              *
 *                                                                   *
 * This work was done as a project in the SAnToS Laboratory,         *
 * Department of Computing and Information Sciences, Kansas State    *
 * University, USA (http://www.cis.ksu.edu/santos).                  *
 * It is understood that any modification not identified as such is  *
 * not covered by the preceding statement.                           *
 *                                                                   *
 * This work is free software; you can redistribute it and/or        *
 * modify it under the terms of the GNU Library General Public       *
 * License as published by the Free Software Foundation; either      *
 * version 2 of the License, or (at your option) any later version.  *
 *                                                                   *
 * This work is distributed in the hope that it will be useful,      *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of    *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU *
 * Library General Public License for more details.                  *
 *                                                                   *
 * You should have received a copy of the GNU Library General Public *
 * License along with this toolkit; if not, write to the             *
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,      *
 * Boston, MA  02111-1307, USA.                                      *
 *                                                                   *
 * Java is a trademark of Sun Microsystems, Inc.                     *
 *                                                                   *
 * To submit a bug report, send a comment, or get the latest news on *
 * this project and other SAnToS projects, please visit the web-site *
 *                http://www.cis.ksu.edu/santos                      *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/* This file was generated by SableCC (http://www.sable.mcgill.ca/sablecc/). */

import java.util.*;
import edu.ksu.cis.bandera.abstraction.specification.analysis.*;

public final class AGreaterEqualRelExp extends PRelExp
{
	private PRelExp _relExp_;
	private TGreaterEqual _greaterEqual_;
	private PShiftExp _shiftExp_;

	public AGreaterEqualRelExp()
	{
	}
	public AGreaterEqualRelExp(
		PRelExp _relExp_,
		TGreaterEqual _greaterEqual_,
		PShiftExp _shiftExp_)
	{
		setRelExp(_relExp_);

		setGreaterEqual(_greaterEqual_);

		setShiftExp(_shiftExp_);

	}
	public void apply(Switch sw)
	{
		((Analysis) sw).caseAGreaterEqualRelExp(this);
	}
	public Object clone()
	{
		return new AGreaterEqualRelExp(
			(PRelExp) cloneNode(_relExp_),
			(TGreaterEqual) cloneNode(_greaterEqual_),
			(PShiftExp) cloneNode(_shiftExp_));
	}
	public TGreaterEqual getGreaterEqual()
	{
		return _greaterEqual_;
	}
	public PRelExp getRelExp()
	{
		return _relExp_;
	}
	public PShiftExp getShiftExp()
	{
		return _shiftExp_;
	}
	void removeChild(Node child)
	{
		if(_relExp_ == child)
		{
			_relExp_ = null;
			return;
		}

		if(_greaterEqual_ == child)
		{
			_greaterEqual_ = null;
			return;
		}

		if(_shiftExp_ == child)
		{
			_shiftExp_ = null;
			return;
		}

	}
	void replaceChild(Node oldChild, Node newChild)
	{
		if(_relExp_ == oldChild)
		{
			setRelExp((PRelExp) newChild);
			return;
		}

		if(_greaterEqual_ == oldChild)
		{
			setGreaterEqual((TGreaterEqual) newChild);
			return;
		}

		if(_shiftExp_ == oldChild)
		{
			setShiftExp((PShiftExp) newChild);
			return;
		}

	}
	public void setGreaterEqual(TGreaterEqual node)
	{
		if(_greaterEqual_ != null)
		{
			_greaterEqual_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_greaterEqual_ = node;
	}
	public void setRelExp(PRelExp node)
	{
		if(_relExp_ != null)
		{
			_relExp_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_relExp_ = node;
	}
	public void setShiftExp(PShiftExp node)
	{
		if(_shiftExp_ != null)
		{
			_shiftExp_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_shiftExp_ = node;
	}
	public String toString()
	{
		return ""
			+ toString(_relExp_)
			+ toString(_greaterEqual_)
			+ toString(_shiftExp_);
	}
}
