package edu.ksu.cis.bandera.abstraction.specification.node;

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Bandera, a Java(TM) analysis and transformation toolkit           *
 * Copyright (C) 1998-2001 SAnToS Laboratories (santos@cis.ksu.edu)  *

 * All rights reserved.                                              *
 *                                                                   *
 * This work was done as a project in the SAnToS Laboratory,         *
 * Department of Computing and Information Sciences, Kansas State    *
 * University, USA (http://www.cis.ksu.edu/santos).                  *
 * It is understood that any modification not identified as such is  *
 * not covered by the preceding statement.                           *
 *                                                                   *
 * This work is free software; you can redistribute it and/or        *
 * modify it under the terms of the GNU Library General Public       *
 * License as published by the Free Software Foundation; either      *
 * version 2 of the License, or (at your option) any later version.  *
 *                                                                   *
 * This work is distributed in the hope that it will be useful,      *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of    *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU *
 * Library General Public License for more details.                  *
 *                                                                   *
 * You should have received a copy of the GNU Library General Public *
 * License along with this toolkit; if not, write to the             *
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,      *
 * Boston, MA  02111-1307, USA.                                      *
 *                                                                   *
 * Java is a trademark of Sun Microsystems, Inc.                     *
 *                                                                   *
 * To submit a bug report, send a comment, or get the latest news on *
 * this project and other SAnToS projects, please visit the web-site *
 *                http://www.cis.ksu.edu/santos                      *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/* This file was generated by SableCC (http://www.sable.mcgill.ca/sablecc/). */

import java.util.*;
import edu.ksu.cis.bandera.abstraction.specification.analysis.*;

public final class ANeqEqExp extends PEqExp
{
	private PEqExp _eqExp_;
	private TNotEqual _notEqual_;
	private PRelExp _relExp_;

	public ANeqEqExp()
	{
	}
	public ANeqEqExp(
		PEqExp _eqExp_,
		TNotEqual _notEqual_,
		PRelExp _relExp_)
	{
		setEqExp(_eqExp_);

		setNotEqual(_notEqual_);

		setRelExp(_relExp_);

	}
	public void apply(Switch sw)
	{
		((Analysis) sw).caseANeqEqExp(this);
	}
	public Object clone()
	{
		return new ANeqEqExp(
			(PEqExp) cloneNode(_eqExp_),
			(TNotEqual) cloneNode(_notEqual_),
			(PRelExp) cloneNode(_relExp_));
	}
	public PEqExp getEqExp()
	{
		return _eqExp_;
	}
	public TNotEqual getNotEqual()
	{
		return _notEqual_;
	}
	public PRelExp getRelExp()
	{
		return _relExp_;
	}
	void removeChild(Node child)
	{
		if(_eqExp_ == child)
		{
			_eqExp_ = null;
			return;
		}

		if(_notEqual_ == child)
		{
			_notEqual_ = null;
			return;
		}

		if(_relExp_ == child)
		{
			_relExp_ = null;
			return;
		}

	}
	void replaceChild(Node oldChild, Node newChild)
	{
		if(_eqExp_ == oldChild)
		{
			setEqExp((PEqExp) newChild);
			return;
		}

		if(_notEqual_ == oldChild)
		{
			setNotEqual((TNotEqual) newChild);
			return;
		}

		if(_relExp_ == oldChild)
		{
			setRelExp((PRelExp) newChild);
			return;
		}

	}
	public void setEqExp(PEqExp node)
	{
		if(_eqExp_ != null)
		{
			_eqExp_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_eqExp_ = node;
	}
	public void setNotEqual(TNotEqual node)
	{
		if(_notEqual_ != null)
		{
			_notEqual_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_notEqual_ = node;
	}
	public void setRelExp(PRelExp node)
	{
		if(_relExp_ != null)
		{
			_relExp_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_relExp_ = node;
	}
	public String toString()
	{
		return ""
			+ toString(_eqExp_)
			+ toString(_notEqual_)
			+ toString(_relExp_);
	}
}
