package edu.ksu.cis.bandera.abstraction.specification.node;

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Bandera, a Java(TM) analysis and transformation toolkit           *
 * Copyright (C) 1998-2001 SAnToS Laboratories (santos@cis.ksu.edu)  *

 * All rights reserved.                                              *
 *                                                                   *
 * This work was done as a project in the SAnToS Laboratory,         *
 * Department of Computing and Information Sciences, Kansas State    *
 * University, USA (http://www.cis.ksu.edu/santos).                  *
 * It is understood that any modification not identified as such is  *
 * not covered by the preceding statement.                           *
 *                                                                   *
 * This work is free software; you can redistribute it and/or        *
 * modify it under the terms of the GNU Library General Public       *
 * License as published by the Free Software Foundation; either      *
 * version 2 of the License, or (at your option) any later version.  *
 *                                                                   *
 * This work is distributed in the hope that it will be useful,      *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of    *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU *
 * Library General Public License for more details.                  *
 *                                                                   *
 * You should have received a copy of the GNU Library General Public *
 * License along with this toolkit; if not, write to the             *
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,      *
 * Boston, MA  02111-1307, USA.                                      *
 *                                                                   *
 * Java is a trademark of Sun Microsystems, Inc.                     *
 *                                                                   *
 * To submit a bug report, send a comment, or get the latest news on *
 * this project and other SAnToS projects, please visit the web-site *
 *                http://www.cis.ksu.edu/santos                      *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/* This file was generated by SableCC (http://www.sable.mcgill.ca/sablecc/). */

import java.util.*;
import edu.ksu.cis.bandera.abstraction.specification.analysis.*;

public final class AOperator extends POperator
{
	private TOperator _operator_;
	private POp _op_;
	private TId _id_;
	private TBegin _begin_;
	private final LinkedList _pattern_ = new TypedLinkedList(new Pattern_Cast());
	private TEnd _end_;

	private class Pattern_Cast implements Cast
	{
		public Object cast(Object o)
		{
			PPattern node = (PPattern) o;

			if((node.parent() != null) &&
				(node.parent() != AOperator.this))
			{
				node.parent().removeChild(node);
			}

			if((node.parent() == null) ||
				(node.parent() != AOperator.this))
			{
				node.parent(AOperator.this);
			}

			return node;
		}
	}
	public AOperator()
	{
	}
	public AOperator(
		TOperator _operator_,
		POp _op_,
		TId _id_,
		TBegin _begin_,
		XPPattern _pattern_,
		TEnd _end_)
	{
		setOperator(_operator_);

		setOp(_op_);

		setId(_id_);

		setBegin(_begin_);

		if(_pattern_ != null)
		{
			while(_pattern_ instanceof X1PPattern)
			{
				this._pattern_.addFirst(((X1PPattern) _pattern_).getPPattern());
				_pattern_ = ((X1PPattern) _pattern_).getXPPattern();
			}
			this._pattern_.addFirst(((X2PPattern) _pattern_).getPPattern());
		}

		setEnd(_end_);

	}
	public AOperator(
		TOperator _operator_,
		POp _op_,
		TId _id_,
		TBegin _begin_,
		List _pattern_,
		TEnd _end_)
	{
		setOperator(_operator_);

		setOp(_op_);

		setId(_id_);

		setBegin(_begin_);

		{
			Object temp[] = _pattern_.toArray();
			for(int i = 0; i < temp.length; i++)
			{
				this._pattern_.add(temp[i]);
			}
		}

		setEnd(_end_);

	}
	public void apply(Switch sw)
	{
		((Analysis) sw).caseAOperator(this);
	}
	public Object clone()
	{
		return new AOperator(
			(TOperator) cloneNode(_operator_),
			(POp) cloneNode(_op_),
			(TId) cloneNode(_id_),
			(TBegin) cloneNode(_begin_),
			cloneList(_pattern_),
			(TEnd) cloneNode(_end_));
	}
	public TBegin getBegin()
	{
		return _begin_;
	}
	public TEnd getEnd()
	{
		return _end_;
	}
	public TId getId()
	{
		return _id_;
	}
	public POp getOp()
	{
		return _op_;
	}
	public TOperator getOperator()
	{
		return _operator_;
	}
	public LinkedList getPattern()
	{
		return _pattern_;
	}
	void removeChild(Node child)
	{
		if(_operator_ == child)
		{
			_operator_ = null;
			return;
		}

		if(_op_ == child)
		{
			_op_ = null;
			return;
		}

		if(_id_ == child)
		{
			_id_ = null;
			return;
		}

		if(_begin_ == child)
		{
			_begin_ = null;
			return;
		}

		if(_pattern_.remove(child))
		{
			return;
		}

		if(_end_ == child)
		{
			_end_ = null;
			return;
		}

	}
	void replaceChild(Node oldChild, Node newChild)
	{
		if(_operator_ == oldChild)
		{
			setOperator((TOperator) newChild);
			return;
		}

		if(_op_ == oldChild)
		{
			setOp((POp) newChild);
			return;
		}

		if(_id_ == oldChild)
		{
			setId((TId) newChild);
			return;
		}

		if(_begin_ == oldChild)
		{
			setBegin((TBegin) newChild);
			return;
		}

		for(ListIterator i = _pattern_.listIterator(); i.hasNext();)
		{
			if(i.next() == oldChild)
			{
				if(newChild != null)
				{
					i.set(newChild);
					oldChild.parent(null);
					return;
				}

				i.remove();
				oldChild.parent(null);
				return;
			}
		}

		if(_end_ == oldChild)
		{
			setEnd((TEnd) newChild);
			return;
		}

	}
	public void setBegin(TBegin node)
	{
		if(_begin_ != null)
		{
			_begin_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_begin_ = node;
	}
	public void setEnd(TEnd node)
	{
		if(_end_ != null)
		{
			_end_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_end_ = node;
	}
	public void setId(TId node)
	{
		if(_id_ != null)
		{
			_id_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_id_ = node;
	}
	public void setOp(POp node)
	{
		if(_op_ != null)
		{
			_op_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_op_ = node;
	}
	public void setOperator(TOperator node)
	{
		if(_operator_ != null)
		{
			_operator_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_operator_ = node;
	}
	public void setPattern(List list)
	{
		Object temp[] = list.toArray();
		for(int i = 0; i < temp.length; i++)
		{
			_pattern_.add(temp[i]);
		}
	}
	public String toString()
	{
		return ""
			+ toString(_operator_)
			+ toString(_op_)
			+ toString(_id_)
			+ toString(_begin_)
			+ toString(_pattern_)
			+ toString(_end_);
	}
}
