package edu.ksu.cis.bandera.abstraction.specification.node;

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Bandera, a Java(TM) analysis and transformation toolkit           *
 * Copyright (C) 1998-2001 SAnToS Laboratories (santos@cis.ksu.edu)  *

 * All rights reserved.                                              *
 *                                                                   *
 * This work was done as a project in the SAnToS Laboratory,         *
 * Department of Computing and Information Sciences, Kansas State    *
 * University, USA (http://www.cis.ksu.edu/santos).                  *
 * It is understood that any modification not identified as such is  *
 * not covered by the preceding statement.                           *
 *                                                                   *
 * This work is free software; you can redistribute it and/or        *
 * modify it under the terms of the GNU Library General Public       *
 * License as published by the Free Software Foundation; either      *
 * version 2 of the License, or (at your option) any later version.  *
 *                                                                   *
 * This work is distributed in the hope that it will be useful,      *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of    *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU *
 * Library General Public License for more details.                  *
 *                                                                   *
 * You should have received a copy of the GNU Library General Public *
 * License along with this toolkit; if not, write to the             *
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,      *
 * Boston, MA  02111-1307, USA.                                      *
 *                                                                   *
 * Java is a trademark of Sun Microsystems, Inc.                     *
 *                                                                   *
 * To submit a bug report, send a comment, or get the latest news on *
 * this project and other SAnToS projects, please visit the web-site *
 *                http://www.cis.ksu.edu/santos                      *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/* This file was generated by SableCC (http://www.sable.mcgill.ca/sablecc/). */

import java.util.*;
import edu.ksu.cis.bandera.abstraction.specification.analysis.*;

public final class ATokenSet extends PTokenSet
{
	private TTokens _tokens_;
	private TEq _eq_;
	private PIdSet _idSet_;
	private TSemicolon _semicolon_;

	public ATokenSet()
	{
	}
	public ATokenSet(
		TTokens _tokens_,
		TEq _eq_,
		PIdSet _idSet_,
		TSemicolon _semicolon_)
	{
		setTokens(_tokens_);

		setEq(_eq_);

		setIdSet(_idSet_);

		setSemicolon(_semicolon_);

	}
	public void apply(Switch sw)
	{
		((Analysis) sw).caseATokenSet(this);
	}
	public Object clone()
	{
		return new ATokenSet(
			(TTokens) cloneNode(_tokens_),
			(TEq) cloneNode(_eq_),
			(PIdSet) cloneNode(_idSet_),
			(TSemicolon) cloneNode(_semicolon_));
	}
	public TEq getEq()
	{
		return _eq_;
	}
	public PIdSet getIdSet()
	{
		return _idSet_;
	}
	public TSemicolon getSemicolon()
	{
		return _semicolon_;
	}
	public TTokens getTokens()
	{
		return _tokens_;
	}
	void removeChild(Node child)
	{
		if(_tokens_ == child)
		{
			_tokens_ = null;
			return;
		}

		if(_eq_ == child)
		{
			_eq_ = null;
			return;
		}

		if(_idSet_ == child)
		{
			_idSet_ = null;
			return;
		}

		if(_semicolon_ == child)
		{
			_semicolon_ = null;
			return;
		}

	}
	void replaceChild(Node oldChild, Node newChild)
	{
		if(_tokens_ == oldChild)
		{
			setTokens((TTokens) newChild);
			return;
		}

		if(_eq_ == oldChild)
		{
			setEq((TEq) newChild);
			return;
		}

		if(_idSet_ == oldChild)
		{
			setIdSet((PIdSet) newChild);
			return;
		}

		if(_semicolon_ == oldChild)
		{
			setSemicolon((TSemicolon) newChild);
			return;
		}

	}
	public void setEq(TEq node)
	{
		if(_eq_ != null)
		{
			_eq_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_eq_ = node;
	}
	public void setIdSet(PIdSet node)
	{
		if(_idSet_ != null)
		{
			_idSet_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_idSet_ = node;
	}
	public void setSemicolon(TSemicolon node)
	{
		if(_semicolon_ != null)
		{
			_semicolon_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_semicolon_ = node;
	}
	public void setTokens(TTokens node)
	{
		if(_tokens_ != null)
		{
			_tokens_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_tokens_ = node;
	}
	public String toString()
	{
		return ""
			+ toString(_tokens_)
			+ toString(_eq_)
			+ toString(_idSet_)
			+ toString(_semicolon_);
	}
}
