package edu.ksu.cis.bandera.specification.pattern.node;

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Bandera, a Java(TM) analysis and transformation toolkit           *
 * Copyright (C) 1998-2001 SAnToS Laboratories (santos@cis.ksu.edu)  *

 * All rights reserved.                                              *
 *                                                                   *
 * This work was done as a project in the SAnToS Laboratory,         *
 * Department of Computing and Information Sciences, Kansas State    *
 * University, USA (http://www.cis.ksu.edu/santos).                  *
 * It is understood that any modification not identified as such is  *
 * not covered by the preceding statement.                           *
 *                                                                   *
 * This work is free software; you can redistribute it and/or        *
 * modify it under the terms of the GNU Library General Public       *
 * License as published by the Free Software Foundation; either      *
 * version 2 of the License, or (at your option) any later version.  *
 *                                                                   *
 * This work is distributed in the hope that it will be useful,      *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of    *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU *
 * Library General Public License for more details.                  *
 *                                                                   *
 * You should have received a copy of the GNU Library General Public *
 * License along with this toolkit; if not, write to the             *
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,      *
 * Boston, MA  02111-1307, USA.                                      *
 *                                                                   *
 * Java is a trademark of Sun Microsystems, Inc.                     *
 *                                                                   *
 * To submit a bug report, send a comment, or get the latest news on *
 * this project and other SAnToS projects, please visit the web-site *
 *                http://www.cis.ksu.edu/santos                      *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/* This file was generated by SableCC (http://www.sable.mcgill.ca/sablecc/). */

import java.util.*;
import edu.ksu.cis.bandera.specification.pattern.analysis.*;

public final class AStringsStrings extends PStrings
{
	private PStrings _strings_;
	private TPlus _plus_;
	private TStringLiteral _stringLiteral_;

	public AStringsStrings()
	{
	}
	public AStringsStrings(
		PStrings _strings_,
		TPlus _plus_,
		TStringLiteral _stringLiteral_)
	{
		setStrings(_strings_);

		setPlus(_plus_);

		setStringLiteral(_stringLiteral_);

	}
	public void apply(Switch sw)
	{
		((Analysis) sw).caseAStringsStrings(this);
	}
	public Object clone()
	{
		return new AStringsStrings(
			(PStrings) cloneNode(_strings_),
			(TPlus) cloneNode(_plus_),
			(TStringLiteral) cloneNode(_stringLiteral_));
	}
	public TPlus getPlus()
	{
		return _plus_;
	}
	public TStringLiteral getStringLiteral()
	{
		return _stringLiteral_;
	}
	public PStrings getStrings()
	{
		return _strings_;
	}
	void removeChild(Node child)
	{
		if(_strings_ == child)
		{
			_strings_ = null;
			return;
		}

		if(_plus_ == child)
		{
			_plus_ = null;
			return;
		}

		if(_stringLiteral_ == child)
		{
			_stringLiteral_ = null;
			return;
		}

	}
	void replaceChild(Node oldChild, Node newChild)
	{
		if(_strings_ == oldChild)
		{
			setStrings((PStrings) newChild);
			return;
		}

		if(_plus_ == oldChild)
		{
			setPlus((TPlus) newChild);
			return;
		}

		if(_stringLiteral_ == oldChild)
		{
			setStringLiteral((TStringLiteral) newChild);
			return;
		}

	}
	public void setPlus(TPlus node)
	{
		if(_plus_ != null)
		{
			_plus_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_plus_ = node;
	}
	public void setStringLiteral(TStringLiteral node)
	{
		if(_stringLiteral_ != null)
		{
			_stringLiteral_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_stringLiteral_ = node;
	}
	public void setStrings(PStrings node)
	{
		if(_strings_ != null)
		{
			_strings_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_strings_ = node;
	}
	public String toString()
	{
		return ""
			+ toString(_strings_)
			+ toString(_plus_)
			+ toString(_stringLiteral_);
	}
}
