/* This file was generated by SableCC (http://www.sablecc.org/). */

package edu.ksu.cis.bandera.birp.node;

import java.util.*;
import edu.ksu.cis.bandera.birp.analysis.*;

public final class AAndExpr6 extends PExpr6
{
    private PExpr6 _expr6_;
    private TAnd _and_;
    private PExpr5 _expr5_;

    public AAndExpr6()
    {
    }

    public AAndExpr6(
        PExpr6 _expr6_,
        TAnd _and_,
        PExpr5 _expr5_)
    {
        setExpr6(_expr6_);

        setAnd(_and_);

        setExpr5(_expr5_);

    }
    public Object clone()
    {
        return new AAndExpr6(
            (PExpr6) cloneNode(_expr6_),
            (TAnd) cloneNode(_and_),
            (PExpr5) cloneNode(_expr5_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAndExpr6(this);
    }

    public PExpr6 getExpr6()
    {
        return _expr6_;
    }

    public void setExpr6(PExpr6 node)
    {
        if(_expr6_ != null)
        {
            _expr6_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _expr6_ = node;
    }

    public TAnd getAnd()
    {
        return _and_;
    }

    public void setAnd(TAnd node)
    {
        if(_and_ != null)
        {
            _and_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _and_ = node;
    }

    public PExpr5 getExpr5()
    {
        return _expr5_;
    }

    public void setExpr5(PExpr5 node)
    {
        if(_expr5_ != null)
        {
            _expr5_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _expr5_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_expr6_)
            + toString(_and_)
            + toString(_expr5_);
    }

    void removeChild(Node child)
    {
        if(_expr6_ == child)
        {
            _expr6_ = null;
            return;
        }

        if(_and_ == child)
        {
            _and_ = null;
            return;
        }

        if(_expr5_ == child)
        {
            _expr5_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_expr6_ == oldChild)
        {
            setExpr6((PExpr6) newChild);
            return;
        }

        if(_and_ == oldChild)
        {
            setAnd((TAnd) newChild);
            return;
        }

        if(_expr5_ == oldChild)
        {
            setExpr5((PExpr5) newChild);
            return;
        }

    }
}
