/* This file was generated by SableCC (http://www.sablecc.org/). */

package edu.ksu.cis.bandera.birp.node;

import java.util.*;
import edu.ksu.cis.bandera.birp.analysis.*;

public final class ACollectionGlobal extends PGlobal
{
    private PCollection _collection_;

    public ACollectionGlobal()
    {
    }

    public ACollectionGlobal(
        PCollection _collection_)
    {
        setCollection(_collection_);

    }
    public Object clone()
    {
        return new ACollectionGlobal(
            (PCollection) cloneNode(_collection_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACollectionGlobal(this);
    }

    public PCollection getCollection()
    {
        return _collection_;
    }

    public void setCollection(PCollection node)
    {
        if(_collection_ != null)
        {
            _collection_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _collection_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_collection_);
    }

    void removeChild(Node child)
    {
        if(_collection_ == child)
        {
            _collection_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_collection_ == oldChild)
        {
            setCollection((PCollection) newChild);
            return;
        }

    }
}
