/* This file was generated by SableCC (http://www.sablecc.org/). */

package edu.ksu.cis.bandera.birp.node;

import java.util.*;
import edu.ksu.cis.bandera.birp.analysis.*;

public final class AHaslockLocktestop extends PLocktestop
{
    private THaslock _haslock_;

    public AHaslockLocktestop()
    {
    }

    public AHaslockLocktestop(
        THaslock _haslock_)
    {
        setHaslock(_haslock_);

    }
    public Object clone()
    {
        return new AHaslockLocktestop(
            (THaslock) cloneNode(_haslock_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAHaslockLocktestop(this);
    }

    public THaslock getHaslock()
    {
        return _haslock_;
    }

    public void setHaslock(THaslock node)
    {
        if(_haslock_ != null)
        {
            _haslock_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _haslock_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_haslock_);
    }

    void removeChild(Node child)
    {
        if(_haslock_ == child)
        {
            _haslock_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_haslock_ == oldChild)
        {
            setHaslock((THaslock) newChild);
            return;
        }

    }
}
