/* This file was generated by SableCC (http://www.sablecc.org/). */

package edu.ksu.cis.bandera.birp.node;

import java.util.*;
import edu.ksu.cis.bandera.birp.analysis.*;

public final class AInstanceofExpr0 extends PExpr0
{
    private PExpr0 _expr0_;
    private TInstanceof _instanceof_;
    private TId _id_;

    public AInstanceofExpr0()
    {
    }

    public AInstanceofExpr0(
        PExpr0 _expr0_,
        TInstanceof _instanceof_,
        TId _id_)
    {
        setExpr0(_expr0_);

        setInstanceof(_instanceof_);

        setId(_id_);

    }
    public Object clone()
    {
        return new AInstanceofExpr0(
            (PExpr0) cloneNode(_expr0_),
            (TInstanceof) cloneNode(_instanceof_),
            (TId) cloneNode(_id_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInstanceofExpr0(this);
    }

    public PExpr0 getExpr0()
    {
        return _expr0_;
    }

    public void setExpr0(PExpr0 node)
    {
        if(_expr0_ != null)
        {
            _expr0_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _expr0_ = node;
    }

    public TInstanceof getInstanceof()
    {
        return _instanceof_;
    }

    public void setInstanceof(TInstanceof node)
    {
        if(_instanceof_ != null)
        {
            _instanceof_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _instanceof_ = node;
    }

    public TId getId()
    {
        return _id_;
    }

    public void setId(TId node)
    {
        if(_id_ != null)
        {
            _id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _id_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_expr0_)
            + toString(_instanceof_)
            + toString(_id_);
    }

    void removeChild(Node child)
    {
        if(_expr0_ == child)
        {
            _expr0_ = null;
            return;
        }

        if(_instanceof_ == child)
        {
            _instanceof_ = null;
            return;
        }

        if(_id_ == child)
        {
            _id_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_expr0_ == oldChild)
        {
            setExpr0((PExpr0) newChild);
            return;
        }

        if(_instanceof_ == oldChild)
        {
            setInstanceof((TInstanceof) newChild);
            return;
        }

        if(_id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

    }
}
