/* This file was generated by SableCC (http://www.sablecc.org/). */

package edu.ksu.cis.bandera.birp.node;

import java.util.*;
import edu.ksu.cis.bandera.birp.analysis.*;

public final class ALeExpr4 extends PExpr4
{
    private PExpr4 _expr4_;
    private TLe _le_;
    private PExpr3 _expr3_;

    public ALeExpr4()
    {
    }

    public ALeExpr4(
        PExpr4 _expr4_,
        TLe _le_,
        PExpr3 _expr3_)
    {
        setExpr4(_expr4_);

        setLe(_le_);

        setExpr3(_expr3_);

    }
    public Object clone()
    {
        return new ALeExpr4(
            (PExpr4) cloneNode(_expr4_),
            (TLe) cloneNode(_le_),
            (PExpr3) cloneNode(_expr3_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALeExpr4(this);
    }

    public PExpr4 getExpr4()
    {
        return _expr4_;
    }

    public void setExpr4(PExpr4 node)
    {
        if(_expr4_ != null)
        {
            _expr4_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _expr4_ = node;
    }

    public TLe getLe()
    {
        return _le_;
    }

    public void setLe(TLe node)
    {
        if(_le_ != null)
        {
            _le_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _le_ = node;
    }

    public PExpr3 getExpr3()
    {
        return _expr3_;
    }

    public void setExpr3(PExpr3 node)
    {
        if(_expr3_ != null)
        {
            _expr3_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _expr3_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_expr4_)
            + toString(_le_)
            + toString(_expr3_);
    }

    void removeChild(Node child)
    {
        if(_expr4_ == child)
        {
            _expr4_ = null;
            return;
        }

        if(_le_ == child)
        {
            _le_ = null;
            return;
        }

        if(_expr3_ == child)
        {
            _expr3_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_expr4_ == oldChild)
        {
            setExpr4((PExpr4) newChild);
            return;
        }

        if(_le_ == oldChild)
        {
            setLe((TLe) newChild);
            return;
        }

        if(_expr3_ == oldChild)
        {
            setExpr3((PExpr3) newChild);
            return;
        }

    }
}
