/* This file was generated by SableCC (http://www.sablecc.org/). */

package edu.ksu.cis.bandera.birp.node;

import java.util.*;
import edu.ksu.cis.bandera.birp.analysis.*;

public final class AMorePrintargs extends PPrintargs
{
    private PPrintarg _printarg_;
    private TComma _comma_;
    private PPrintargs _printargs_;

    public AMorePrintargs()
    {
    }

    public AMorePrintargs(
        PPrintarg _printarg_,
        TComma _comma_,
        PPrintargs _printargs_)
    {
        setPrintarg(_printarg_);

        setComma(_comma_);

        setPrintargs(_printargs_);

    }
    public Object clone()
    {
        return new AMorePrintargs(
            (PPrintarg) cloneNode(_printarg_),
            (TComma) cloneNode(_comma_),
            (PPrintargs) cloneNode(_printargs_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMorePrintargs(this);
    }

    public PPrintarg getPrintarg()
    {
        return _printarg_;
    }

    public void setPrintarg(PPrintarg node)
    {
        if(_printarg_ != null)
        {
            _printarg_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _printarg_ = node;
    }

    public TComma getComma()
    {
        return _comma_;
    }

    public void setComma(TComma node)
    {
        if(_comma_ != null)
        {
            _comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _comma_ = node;
    }

    public PPrintargs getPrintargs()
    {
        return _printargs_;
    }

    public void setPrintargs(PPrintargs node)
    {
        if(_printargs_ != null)
        {
            _printargs_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _printargs_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_printarg_)
            + toString(_comma_)
            + toString(_printargs_);
    }

    void removeChild(Node child)
    {
        if(_printarg_ == child)
        {
            _printarg_ = null;
            return;
        }

        if(_comma_ == child)
        {
            _comma_ = null;
            return;
        }

        if(_printargs_ == child)
        {
            _printargs_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_printarg_ == oldChild)
        {
            setPrintarg((PPrintarg) newChild);
            return;
        }

        if(_comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(_printargs_ == oldChild)
        {
            setPrintargs((PPrintargs) newChild);
            return;
        }

    }
}
