/* This file was generated by SableCC (http://www.sablecc.org/). */

package edu.ksu.cis.bandera.birp.node;

import java.util.*;
import edu.ksu.cis.bandera.birp.analysis.*;

public final class ANotifyallLockOp extends PLockOp
{
    private TNotifyall _notifyall_;

    public ANotifyallLockOp()
    {
    }

    public ANotifyallLockOp(
        TNotifyall _notifyall_)
    {
        setNotifyall(_notifyall_);

    }
    public Object clone()
    {
        return new ANotifyallLockOp(
            (TNotifyall) cloneNode(_notifyall_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotifyallLockOp(this);
    }

    public TNotifyall getNotifyall()
    {
        return _notifyall_;
    }

    public void setNotifyall(TNotifyall node)
    {
        if(_notifyall_ != null)
        {
            _notifyall_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _notifyall_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_notifyall_);
    }

    void removeChild(Node child)
    {
        if(_notifyall_ == child)
        {
            _notifyall_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_notifyall_ == oldChild)
        {
            setNotifyall((TNotifyall) newChild);
            return;
        }

    }
}
