/* This file was generated by SableCC (http://www.sablecc.org/). */

package edu.ksu.cis.bandera.birp.node;

import java.util.*;
import edu.ksu.cis.bandera.birp.analysis.*;

public final class APlusExpr1 extends PExpr1
{
    private TPlus _plus_;
    private PExpr1 _expr1_;

    public APlusExpr1()
    {
    }

    public APlusExpr1(
        TPlus _plus_,
        PExpr1 _expr1_)
    {
        setPlus(_plus_);

        setExpr1(_expr1_);

    }
    public Object clone()
    {
        return new APlusExpr1(
            (TPlus) cloneNode(_plus_),
            (PExpr1) cloneNode(_expr1_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPlusExpr1(this);
    }

    public TPlus getPlus()
    {
        return _plus_;
    }

    public void setPlus(TPlus node)
    {
        if(_plus_ != null)
        {
            _plus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _plus_ = node;
    }

    public PExpr1 getExpr1()
    {
        return _expr1_;
    }

    public void setExpr1(PExpr1 node)
    {
        if(_expr1_ != null)
        {
            _expr1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _expr1_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_plus_)
            + toString(_expr1_);
    }

    void removeChild(Node child)
    {
        if(_plus_ == child)
        {
            _plus_ = null;
            return;
        }

        if(_expr1_ == child)
        {
            _expr1_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_plus_ == oldChild)
        {
            setPlus((TPlus) newChild);
            return;
        }

        if(_expr1_ == oldChild)
        {
            setExpr1((PExpr1) newChild);
            return;
        }

    }
}
