/* This file was generated by SableCC (http://www.sablecc.org/). */

package edu.ksu.cis.bandera.birp.node;

import java.util.*;
import edu.ksu.cis.bandera.birp.analysis.*;

public final class APlusExpr3 extends PExpr3
{
    private PExpr3 _expr3_;
    private TPlus _plus_;
    private PExpr2 _expr2_;

    public APlusExpr3()
    {
    }

    public APlusExpr3(
        PExpr3 _expr3_,
        TPlus _plus_,
        PExpr2 _expr2_)
    {
        setExpr3(_expr3_);

        setPlus(_plus_);

        setExpr2(_expr2_);

    }
    public Object clone()
    {
        return new APlusExpr3(
            (PExpr3) cloneNode(_expr3_),
            (TPlus) cloneNode(_plus_),
            (PExpr2) cloneNode(_expr2_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPlusExpr3(this);
    }

    public PExpr3 getExpr3()
    {
        return _expr3_;
    }

    public void setExpr3(PExpr3 node)
    {
        if(_expr3_ != null)
        {
            _expr3_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _expr3_ = node;
    }

    public TPlus getPlus()
    {
        return _plus_;
    }

    public void setPlus(TPlus node)
    {
        if(_plus_ != null)
        {
            _plus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _plus_ = node;
    }

    public PExpr2 getExpr2()
    {
        return _expr2_;
    }

    public void setExpr2(PExpr2 node)
    {
        if(_expr2_ != null)
        {
            _expr2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _expr2_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_expr3_)
            + toString(_plus_)
            + toString(_expr2_);
    }

    void removeChild(Node child)
    {
        if(_expr3_ == child)
        {
            _expr3_ = null;
            return;
        }

        if(_plus_ == child)
        {
            _plus_ = null;
            return;
        }

        if(_expr2_ == child)
        {
            _expr2_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_expr3_ == oldChild)
        {
            setExpr3((PExpr3) newChild);
            return;
        }

        if(_plus_ == oldChild)
        {
            setPlus((TPlus) newChild);
            return;
        }

        if(_expr2_ == oldChild)
        {
            setExpr2((PExpr2) newChild);
            return;
        }

    }
}
