/* This file was generated by SableCC (http://www.sablecc.org/). */

package edu.ksu.cis.bandera.birp.node;

import java.util.*;
import edu.ksu.cis.bandera.birp.analysis.*;

public final class AVariableGlobal extends PGlobal
{
    private PVariable _variable_;

    public AVariableGlobal()
    {
    }

    public AVariableGlobal(
        PVariable _variable_)
    {
        setVariable(_variable_);

    }
    public Object clone()
    {
        return new AVariableGlobal(
            (PVariable) cloneNode(_variable_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariableGlobal(this);
    }

    public PVariable getVariable()
    {
        return _variable_;
    }

    public void setVariable(PVariable node)
    {
        if(_variable_ != null)
        {
            _variable_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _variable_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_variable_);
    }

    void removeChild(Node child)
    {
        if(_variable_ == child)
        {
            _variable_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_variable_ == oldChild)
        {
            setVariable((PVariable) newChild);
            return;
        }

    }
}
