/* This file was generated by SableCC (http://www.sablecc.org/). */

package edu.ksu.cis.bandera.birp.node;

import edu.ksu.cis.bandera.birp.analysis.*;

public final class TEq extends Token
{
    public TEq()
    {
        super.setText("==");
    }

    public TEq(int line, int pos)
    {
        super.setText("==");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TEq(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEq(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TEq text.");
    }
}
