/* This file was generated by SableCC (http://www.sablecc.org/). */

package edu.ksu.cis.bandera.birp.node;

import edu.ksu.cis.bandera.birp.analysis.*;

public final class TLbrack extends Token
{
    public TLbrack()
    {
        super.setText("[");
    }

    public TLbrack(int line, int pos)
    {
        super.setText("[");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TLbrack(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLbrack(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TLbrack text.");
    }
}
