/* This file was generated by SableCC (http://www.sablecc.org/). */

package edu.ksu.cis.bandera.birp.node;

import edu.ksu.cis.bandera.birp.analysis.*;

public final class TLoc extends Token
{
    public TLoc()
    {
        super.setText("loc");
    }

    public TLoc(int line, int pos)
    {
        super.setText("loc");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TLoc(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLoc(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TLoc text.");
    }
}
