/* This file was generated by SableCC (http://www.sablecc.org/). */

package edu.ksu.cis.bandera.birp.node;

import edu.ksu.cis.bandera.birp.analysis.*;

public final class TNot extends Token
{
    public TNot()
    {
        super.setText("!");
    }

    public TNot(int line, int pos)
    {
        super.setText("!");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TNot(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNot(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TNot text.");
    }
}
