/* This file was generated by SableCC (http://www.sablecc.org/). */

package edu.ksu.cis.bandera.birp.node;

import edu.ksu.cis.bandera.birp.analysis.*;

public final class TRange extends Token
{
    public TRange()
    {
        super.setText("range");
    }

    public TRange(int line, int pos)
    {
        super.setText("range");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TRange(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRange(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TRange text.");
    }
}
