/* This file was generated by SableCC (http://www.sablecc.org/). */

package edu.ksu.cis.bandera.birp.node;

import edu.ksu.cis.bandera.birp.analysis.*;

public final class TTid extends Token
{
    public TTid()
    {
        super.setText("tid");
    }

    public TTid(int line, int pos)
    {
        super.setText("tid");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TTid(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTid(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TTid text.");
    }
}
