/* This file was generated by SableCC (http://www.sablecc.org/). */

package edu.ksu.cis.bandera.birp.node;

import edu.ksu.cis.bandera.birp.analysis.*;

public final class X2PLocation extends XPLocation
{
    private PLocation _pLocation_;

    public X2PLocation()
    {
    }

    public X2PLocation(
        PLocation _pLocation_)
    {
        setPLocation(_pLocation_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public PLocation getPLocation()
    {
        return _pLocation_;
    }

    public void setPLocation(PLocation node)
    {
        if(_pLocation_ != null)
        {
            _pLocation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pLocation_ = node;
    }

    void removeChild(Node child)
    {
        if(_pLocation_ == child)
        {
            _pLocation_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pLocation_);
    }
}
