package edu.ksu.cis.bandera.specification.node;

/* This file was generated by SableCC (http://www.sablecc.org/). */

import java.util.*;
import edu.ksu.cis.bandera.specification.analysis.*;

public final class AHoleFormatWord extends PFormatWord
{
	private TLBrace _lBrace_;
	private TId _id_;
	private TRBrace _rBrace_;

	public AHoleFormatWord()
	{
	}
	public AHoleFormatWord(
		TLBrace _lBrace_,
		TId _id_,
		TRBrace _rBrace_)
	{
		setLBrace(_lBrace_);

		setId(_id_);

		setRBrace(_rBrace_);

	}
	public void apply(Switch sw)
	{
		((Analysis) sw).caseAHoleFormatWord(this);
	}
	public Object clone()
	{
		return new AHoleFormatWord(
			(TLBrace) cloneNode(_lBrace_),
			(TId) cloneNode(_id_),
			(TRBrace) cloneNode(_rBrace_));
	}
	public TId getId()
	{
		return _id_;
	}
	public TLBrace getLBrace()
	{
		return _lBrace_;
	}
	public TRBrace getRBrace()
	{
		return _rBrace_;
	}
	void removeChild(Node child)
	{
		if(_lBrace_ == child)
		{
			_lBrace_ = null;
			return;
		}

		if(_id_ == child)
		{
			_id_ = null;
			return;
		}

		if(_rBrace_ == child)
		{
			_rBrace_ = null;
			return;
		}

	}
	void replaceChild(Node oldChild, Node newChild)
	{
		if(_lBrace_ == oldChild)
		{
			setLBrace((TLBrace) newChild);
			return;
		}

		if(_id_ == oldChild)
		{
			setId((TId) newChild);
			return;
		}

		if(_rBrace_ == oldChild)
		{
			setRBrace((TRBrace) newChild);
			return;
		}

	}
	public void setId(TId node)
	{
		if(_id_ != null)
		{
			_id_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_id_ = node;
	}
	public void setLBrace(TLBrace node)
	{
		if(_lBrace_ != null)
		{
			_lBrace_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_lBrace_ = node;
	}
	public void setRBrace(TRBrace node)
	{
		if(_rBrace_ != null)
		{
			_rBrace_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_rBrace_ = node;
	}
	public String toString()
	{
		return ""
			+ toString(_lBrace_)
			+ toString(_id_)
			+ toString(_rBrace_);
	}
}
