package edu.ksu.cis.bandera.specification.node;

/* This file was generated by SableCC (http://www.sablecc.org/). */

import java.util.*;
import edu.ksu.cis.bandera.specification.analysis.*;

public final class AIdsIds extends PIds
{
	private PIds _ids_;
	private TComma _comma_;
	private TId _id_;

	public AIdsIds()
	{
	}
	public AIdsIds(
		PIds _ids_,
		TComma _comma_,
		TId _id_)
	{
		setIds(_ids_);

		setComma(_comma_);

		setId(_id_);

	}
	public void apply(Switch sw)
	{
		((Analysis) sw).caseAIdsIds(this);
	}
	public Object clone()
	{
		return new AIdsIds(
			(PIds) cloneNode(_ids_),
			(TComma) cloneNode(_comma_),
			(TId) cloneNode(_id_));
	}
	public TComma getComma()
	{
		return _comma_;
	}
	public TId getId()
	{
		return _id_;
	}
	public PIds getIds()
	{
		return _ids_;
	}
	void removeChild(Node child)
	{
		if(_ids_ == child)
		{
			_ids_ = null;
			return;
		}

		if(_comma_ == child)
		{
			_comma_ = null;
			return;
		}

		if(_id_ == child)
		{
			_id_ = null;
			return;
		}

	}
	void replaceChild(Node oldChild, Node newChild)
	{
		if(_ids_ == oldChild)
		{
			setIds((PIds) newChild);
			return;
		}

		if(_comma_ == oldChild)
		{
			setComma((TComma) newChild);
			return;
		}

		if(_id_ == oldChild)
		{
			setId((TId) newChild);
			return;
		}

	}
	public void setComma(TComma node)
	{
		if(_comma_ != null)
		{
			_comma_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_comma_ = node;
	}
	public void setId(TId node)
	{
		if(_id_ != null)
		{
			_id_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_id_ = node;
	}
	public void setIds(PIds node)
	{
		if(_ids_ != null)
		{
			_ids_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_ids_ = node;
	}
	public String toString()
	{
		return ""
			+ toString(_ids_)
			+ toString(_comma_)
			+ toString(_id_);
	}
}
