package edu.ksu.cis.bandera.specification.node;

/* This file was generated by SableCC (http://www.sablecc.org/). */

import java.util.*;
import edu.ksu.cis.bandera.specification.analysis.*;

public final class APropertiesUnit extends PUnit
{
	private final LinkedList _import_ = new TypedLinkedList(new Import_Cast());
	private final LinkedList _def_ = new TypedLinkedList(new Def_Cast());

	private class Import_Cast implements Cast
	{
		public Object cast(Object o)
		{
			PImport node = (PImport) o;

			if((node.parent() != null) &&
				(node.parent() != APropertiesUnit.this))
			{
				node.parent().removeChild(node);
			}

			if((node.parent() == null) ||
				(node.parent() != APropertiesUnit.this))
			{
				node.parent(APropertiesUnit.this);
			}

			return node;
		}
	}

	private class Def_Cast implements Cast
	{
		public Object cast(Object o)
		{
			PDef node = (PDef) o;

			if((node.parent() != null) &&
				(node.parent() != APropertiesUnit.this))
			{
				node.parent().removeChild(node);
			}

			if((node.parent() == null) ||
				(node.parent() != APropertiesUnit.this))
			{
				node.parent(APropertiesUnit.this);
			}

			return node;
		}
	}
	public APropertiesUnit()
	{
	}
	public APropertiesUnit(
		XPImport _import_,
		XPDef _def_)
	{
		if(_import_ != null)
		{
			while(_import_ instanceof X1PImport)
			{
				this._import_.addFirst(((X1PImport) _import_).getPImport());
				_import_ = ((X1PImport) _import_).getXPImport();
			}
			this._import_.addFirst(((X2PImport) _import_).getPImport());
		}

		if(_def_ != null)
		{
			while(_def_ instanceof X1PDef)
			{
				this._def_.addFirst(((X1PDef) _def_).getPDef());
				_def_ = ((X1PDef) _def_).getXPDef();
			}
			this._def_.addFirst(((X2PDef) _def_).getPDef());
		}

	}
	public APropertiesUnit(
		List _import_,
		List _def_)
	{
		{
			this._import_.clear();
			this._import_.addAll(_import_);
		}

		{
			this._def_.clear();
			this._def_.addAll(_def_);
		}

	}
	public void apply(Switch sw)
	{
		((Analysis) sw).caseAPropertiesUnit(this);
	}
	public Object clone()
	{
		return new APropertiesUnit(
			cloneList(_import_),
			cloneList(_def_));
	}
	public LinkedList getDef()
	{
		return _def_;
	}
	public LinkedList getImport()
	{
		return _import_;
	}
	void removeChild(Node child)
	{
		if(_import_.remove(child))
		{
			return;
		}

		if(_def_.remove(child))
		{
			return;
		}

	}
	void replaceChild(Node oldChild, Node newChild)
	{
		for(ListIterator i = _import_.listIterator(); i.hasNext();)
		{
			if(i.next() == oldChild)
			{
				if(newChild != null)
				{
					i.set(newChild);
					oldChild.parent(null);
					return;
				}

				i.remove();
				oldChild.parent(null);
				return;
			}
		}

		for(ListIterator i = _def_.listIterator(); i.hasNext();)
		{
			if(i.next() == oldChild)
			{
				if(newChild != null)
				{
					i.set(newChild);
					oldChild.parent(null);
					return;
				}

				i.remove();
				oldChild.parent(null);
				return;
			}
		}

	}
	public void setDef(List list)
	{
		_def_.clear();
		_def_.addAll(list);
	}
	public void setImport(List list)
	{
		_import_.clear();
		_import_.addAll(list);
	}
	public String toString()
	{
		return ""
			+ toString(_import_)
			+ toString(_def_);
	}
}
