package edu.ksu.cis.bandera.specification.node;

/* This file was generated by SableCC (http://www.sablecc.org/). */

import java.util.*;
import edu.ksu.cis.bandera.specification.analysis.*;

public final class ATlDef extends PDef
{
	private PTl _tl_;

	public ATlDef()
	{
	}
	public ATlDef(
		PTl _tl_)
	{
		setTl(_tl_);

	}
	public void apply(Switch sw)
	{
		((Analysis) sw).caseATlDef(this);
	}
	public Object clone()
	{
		return new ATlDef(
			(PTl) cloneNode(_tl_));
	}
	public PTl getTl()
	{
		return _tl_;
	}
	void removeChild(Node child)
	{
		if(_tl_ == child)
		{
			_tl_ = null;
			return;
		}

	}
	void replaceChild(Node oldChild, Node newChild)
	{
		if(_tl_ == oldChild)
		{
			setTl((PTl) newChild);
			return;
		}

	}
	public void setTl(PTl node)
	{
		if(_tl_ != null)
		{
			_tl_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_tl_ = node;
	}
	public String toString()
	{
		return ""
			+ toString(_tl_);
	}
}
