package edu.ksu.cis.bandera.specification.node;

/* This file was generated by SableCC (http://www.sablecc.org/). */

import edu.ksu.cis.bandera.specification.analysis.*;

public final class EOF extends Token
{
	public EOF()
	{
		setText("");
	}
	public EOF(int line, int pos)
	{
		setText("");
		setLine(line);
		setPos(pos);
	}
	public void apply(Switch sw)
	{
		((Analysis) sw).caseEOF(this);
	}
	public Object clone()
	{
		return new EOF(getLine(), getPos());
	}
}
