package edu.ksu.cis.bandera.specification.node;

/* This file was generated by SableCC (http://www.sablecc.org/). */

public class NodeCast implements Cast
{
	public final static NodeCast instance = new NodeCast();

	private NodeCast()
	{
	}
	public Object cast(Object o)
	{
		return (Node) o;
	}
}
