package edu.ksu.cis.bandera.specification.assertion.analysis;

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Bandera, a Java(TM) analysis and transformation toolkit           *
 * Copyright (C) 1998-2001 SAnToS Laboratories (santos@cis.ksu.edu)  *

 * All rights reserved.                                              *
 *                                                                   *
 * This work was done as a project in the SAnToS Laboratory,         *
 * Department of Computing and Information Sciences, Kansas State    *
 * University, USA (http://www.cis.ksu.edu/santos).                  *
 * It is understood that any modification not identified as such is  *
 * not covered by the preceding statement.                           *
 *                                                                   *
 * This work is free software; you can redistribute it and/or        *
 * modify it under the terms of the GNU Library General Public       *
 * License as published by the Free Software Foundation; either      *
 * version 2 of the License, or (at your option) any later version.  *
 *                                                                   *
 * This work is distributed in the hope that it will be useful,      *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of    *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU *
 * Library General Public License for more details.                  *
 *                                                                   *
 * You should have received a copy of the GNU Library General Public *
 * License along with this toolkit; if not, write to the             *
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,      *
 * Boston, MA  02111-1307, USA.                                      *
 *                                                                   *
 * Java is a trademark of Sun Microsystems, Inc.                     *
 *                                                                   *
 * To submit a bug report, send a comment, or get the latest news on *
 * this project and other SAnToS projects, please visit the web-site *
 *                http://www.cis.ksu.edu/santos                      *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/* This file was generated by SableCC (http://www.sable.mcgill.ca/sablecc/). */

import edu.ksu.cis.bandera.specification.assertion.node.*;

public interface Analysis extends Switch
{
	void caseAEndOfLineComment(AEndOfLineComment node);
	void caseALocationAssertion(ALocationAssertion node);
	void caseAPostAssertion(APostAssertion node);
	void caseAPreAssertion(APreAssertion node);
	void caseAQualifiedName(AQualifiedName node);
	void caseASimpleName(ASimpleName node);
	void caseAUnit(AUnit node);
	void caseEOF(EOF node);
	void caseStart(Start node);
	void caseTColon(TColon node);
	void caseTDocumentationComment(TDocumentationComment node);
	void caseTDot(TDot node);
	void caseTEndOfLineComment(TEndOfLineComment node);
	void caseTId(TId node);
	void caseTLBracket(TLBracket node);
	void caseTLocation(TLocation node);
	void caseTPost(TPost node);
	void caseTPre(TPre node);
	void caseTRBracket(TRBracket node);
	void caseTSemicolon(TSemicolon node);
	void caseTTraditionalComment(TTraditionalComment node);
	void caseTWhiteSpace(TWhiteSpace node);
	Object getIn(Node node);
	Object getOut(Node node);
	void setIn(Node node, Object in);
	void setOut(Node node, Object out);
}
