package edu.ksu.cis.bandera.abstraction.predicate.parser;

/* Generated By:JJTree: Do not edit this line. ASTAddSubExpr.java */
public class ASTAddSubExpr extends ASTMultiBinOpExpr {
  public ASTAddSubExpr(int id) {
	super(id);
  }  
  public ASTAddSubExpr(PredicateParser p, int id) {
	super(p, id);
  }  
  /** Accept the visitor. **/
  public Object jjtAccept(PredicateParserVisitor visitor, Object data) {
	return visitor.visit(this, data);
  }  
  public static Node jjtCreate(int id) {
	  return new ASTAddSubExpr(id);
  }  
  public static Node jjtCreate(PredicateParser p, int id) {
	  return new ASTAddSubExpr(p, id);
  }  
}
