package edu.ksu.cis.bandera.abstraction.predicate.parser;

/* Generated By:JJTree: Do not edit this line. ASTBitOrExpr.java */
public class ASTBitOrExpr extends ASTBinOpExpr {
  public ASTBitOrExpr(int id) {
	super(id);
  }  
  public ASTBitOrExpr(PredicateParser p, int id) {
	super(p, id);
  }  
  /** Accept the visitor. **/
  public Object jjtAccept(PredicateParserVisitor visitor, Object data) {
	return visitor.visit(this, data);
  }  
  public static Node jjtCreate(int id) {
	  return new ASTBitOrExpr(id);
  }  
  public static Node jjtCreate(PredicateParser p, int id) {
	  return new ASTBitOrExpr(p, id);
  }  
}
