package edu.ksu.cis.bandera.abstraction.predicate.parser;

/* Generated By:JJTree: Do not edit this line. ASTLiteral.java */
public class ASTLiteral extends SimpleNode {
  // Added attributes begin
  private Object lit;
  // Added code end

  public ASTLiteral(int id) {
	super(id);
  }  
  public ASTLiteral(PredicateParser p, int id) {
	super(p, id);
  }  
  public Object getLiteral() { return lit; }  
  /** Accept the visitor. **/
  public Object jjtAccept(PredicateParserVisitor visitor, Object data) {
	return visitor.visit(this, data);
  }  
  public static Node jjtCreate(int id) {
	  return new ASTLiteral(id);
  }  
  public static Node jjtCreate(PredicateParser p, int id) {
	  return new ASTLiteral(p, id);
  }  
  // Added attributes end

  // Added code begin
  public void setLiteral(Object l) { lit = l; }  
}
