package edu.ksu.cis.bandera.abstraction.predicate.parser;

/* Generated By:JJTree: Do not edit this line. ASTPrimaryPrefix.java */

public class ASTPrimaryPrefix extends SimpleNode {
  public ASTPrimaryPrefix(int id) {
	super(id);
  }  
  public ASTPrimaryPrefix(PredicateParser p, int id) {
	super(p, id);
  }  
  /** Accept the visitor. **/
  public Object jjtAccept(PredicateParserVisitor visitor, Object data) {
	return visitor.visit(this, data);
  }  
  public static Node jjtCreate(int id) {
	  return new ASTPrimaryPrefix(id);
  }  
  public static Node jjtCreate(PredicateParser p, int id) {
	  return new ASTPrimaryPrefix(p, id);
  }  
}
