package edu.ksu.cis.bandera.abstraction.predicate.parser;

/* Generated By:JJTree: Do not edit this line. E:\MYDOC\Bandera\pa\Output\PredicateParserTreeConstants.java */

public interface PredicateParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTTYPE = 1;
  public int JJTPRIMITIVETYPE = 2;
  public int JJTNAME = 3;
  public int JJTCONDEXPR = 4;
  public int JJTOREXPR = 5;
  public int JJTANDEXPR = 6;
  public int JJTBITOREXPR = 7;
  public int JJTBITXOREXPR = 8;
  public int JJTBITANDEXPR = 9;
  public int JJTEQEXPR = 10;
  public int JJTINSTANCEOFEXPR = 11;
  public int JJTRELATIONALEXPR = 12;
  public int JJTSHIFTEXPR = 13;
  public int JJTADDSUBEXPR = 14;
  public int JJTMULDIVEXPR = 15;
  public int JJTUNARYEXPR = 16;
  public int JJTUNARYMATHEXPR = 17;
  public int JJTCASTLOOKAHEAD = 18;
  public int JJTCASTEXPR = 19;
  public int JJTPRIMARYEXPR = 20;
  public int JJTSUPEREXPR = 21;
  public int JJTTHISEXPR = 22;
  public int JJTDOTCLASSEXPR = 23;
  public int JJTARRAYEXPR = 24;
  public int JJTDOTTEDEXPR = 25;
  public int JJTLITERAL = 26;
  public int JJTARGUMENTS = 27;


  public String[] jjtNodeName = {
	"CompilationUnit",
	"Type",
	"PrimitiveType",
	"Name",
	"CondExpr",
	"OrExpr",
	"AndExpr",
	"BitOrExpr",
	"BitXorExpr",
	"BitAndExpr",
	"EqExpr",
	"InstanceOfExpr",
	"RelationalExpr",
	"ShiftExpr",
	"AddSubExpr",
	"MulDivExpr",
	"UnaryExpr",
	"UnaryMathExpr",
	"CastLookahead",
	"CastExpr",
	"PrimaryExpr",
	"SuperExpr",
	"ThisExpr",
	"DotClassExpr",
	"ArrayExpr",
	"DottedExpr",
	"Literal",
	"Arguments",
  };
}
