package edu.ksu.cis.bandera.abstraction.lib.integral;

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Bandera, a Java(TM) analysis and transformation toolkit           *
 * Copyright (C) 1998-2001 SAnToS Laboratories (santos@cis.ksu.edu)  *

 * All rights reserved.                                              *
 *                                                                   *
 * This work was done as a project in the SAnToS Laboratory,         *
 * Department of Computing and Information Sciences, Kansas State    *
 * University, USA (http://www.cis.ksu.edu/santos).                  *
 * It is understood that any modification not identified as such is  *
 * not covered by the preceding statement.                           *
 *                                                                   *
 * This work is free software; you can redistribute it and/or        *
 * modify it under the terms of the GNU Library General Public       *
 * License as published by the Free Software Foundation; either      *
 * version 2 of the License, or (at your option) any later version.  *
 *                                                                   *
 * This work is distributed in the hope that it will be useful,      *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of    *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU *
 * Library General Public License for more details.                  *
 *                                                                   *
 * You should have received a copy of the GNU Library General Public *
 * License along with this toolkit; if not, write to the             *
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,      *
 * Boston, MA  02111-1307, USA.                                      *
 *                                                                   *
 * Java is a trademark of Sun Microsystems, Inc.                     *
 *                                                                   *
 * To submit a bug report, send a comment, or get the latest news on *
 * this project and other SAnToS projects, please visit the web-site *
 *                http://www.cis.ksu.edu/santos                      *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
// This file was generated by Bandera (http://www.cis.ksu.edu/santos/bandera).
import edu.ksu.cis.bandera.abstraction.*;
public class Range04 extends IntegralAbstraction {
  private static final Range04 v = new Range04();
  public static final int R0 = 0;
  public static final int LT0 = 1;
  public static final int R1 = 2;
  public static final int R2 = 3;
  public static final int R3 = 4;
  public static final int R4 = 5;
  public static final int GT4 = 6;
  private Range04() {
  }  
  public static int abs(long n) {
	if (n < 0) return LT0;
	if (n == 0) return R0;
	if (n == 1) return R1;
	if (n == 2) return R2;
	if (n == 3) return R3;
	if (n == 4) return R4;
	if (n > 4) return GT4;
	throw new RuntimeException("Range04 cannot abstract value '" + n + "'");
  }  
  public static int add(int left$, int right$) {
	if (left$ == LT0 && right$ == LT0) return LT0;
	if (left$ == LT0 && right$ == R0) return LT0;
	if (left$ == LT0 && right$ == R1) return Abstraction.choose((1 << R0) | (1 << LT0));
	if (left$ == LT0 && right$ == R2) return Abstraction.choose((1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == LT0 && right$ == R3) return Abstraction.choose((1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == LT0 && right$ == R4) return Abstraction.choose((1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == LT0 && right$ == GT4) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == R0 && right$ == LT0) return LT0;
	if (left$ == R0 && right$ == R0) return R0;
	if (left$ == R0 && right$ == R1) return R1;
	if (left$ == R0 && right$ == R2) return R2;
	if (left$ == R0 && right$ == R3) return R3;
	if (left$ == R0 && right$ == R4) return R4;
	if (left$ == R0 && right$ == GT4) return GT4;
	if (left$ == R1 && right$ == LT0) return Abstraction.choose((1 << R0) | (1 << LT0));
	if (left$ == R1 && right$ == R0) return R1;
	if (left$ == R1 && right$ == R1) return R2;
	if (left$ == R1 && right$ == R2) return R3;
	if (left$ == R1 && right$ == R3) return R4;
	if (left$ == R1 && right$ == R4) return GT4;
	if (left$ == R1 && right$ == GT4) return GT4;
	if (left$ == R2 && right$ == LT0) return Abstraction.choose((1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == R2 && right$ == R0) return R2;
	if (left$ == R2 && right$ == R1) return R3;
	if (left$ == R2 && right$ == R2) return R4;
	if (left$ == R2 && right$ == R3) return GT4;
	if (left$ == R2 && right$ == R4) return GT4;
	if (left$ == R2 && right$ == GT4) return GT4;
	if (left$ == R3 && right$ == LT0) return Abstraction.choose((1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == R3 && right$ == R0) return R3;
	if (left$ == R3 && right$ == R1) return R4;
	if (left$ == R3 && right$ == R2) return GT4;
	if (left$ == R3 && right$ == R3) return GT4;
	if (left$ == R3 && right$ == R4) return GT4;
	if (left$ == R3 && right$ == GT4) return GT4;
	if (left$ == R4 && right$ == LT0) return Abstraction.choose((1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == R4 && right$ == R0) return R4;
	if (left$ == R4 && right$ == R1) return GT4;
	if (left$ == R4 && right$ == R2) return GT4;
	if (left$ == R4 && right$ == R3) return GT4;
	if (left$ == R4 && right$ == R4) return GT4;
	if (left$ == R4 && right$ == GT4) return GT4;
	if (left$ == GT4 && right$ == LT0) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == GT4 && right$ == R0) return GT4;
	if (left$ == GT4 && right$ == R1) return GT4;
	if (left$ == GT4 && right$ == R2) return GT4;
	if (left$ == GT4 && right$ == R3) return GT4;
	if (left$ == GT4 && right$ == R4) return GT4;
	if (left$ == GT4 && right$ == GT4) return GT4;
	throw new RuntimeException("Range04.add(" + left$ + ", " + right$ + ") is undefined");
  }  
  private static int addNoChoose(int left, int right) {
	int result = 0;
	switch (left) {
	  case 0:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 2;
			break;
		  case 2:
			result = 4;
			break;
		  case 3:
			result = 8;
			break;
		  case 4:
			result = 16;
			break;
		  case 5:
			result = 32;
			break;
		  case 6:
			result = 64;
			break;
		}
		break;
	  case 1:
		switch (right) {
		  case 0:
			result = 2;
			break;
		  case 1:
			result = 2;
			break;
		  case 2:
			result = 3;
			break;
		  case 3:
			result = 7;
			break;
		  case 4:
			result = 15;
			break;
		  case 5:
			result = 31;
			break;
		  case 6:
			result = 127;
			break;
		}
		break;
	  case 2:
		switch (right) {
		  case 0:
			result = 4;
			break;
		  case 1:
			result = 3;
			break;
		  case 2:
			result = 8;
			break;
		  case 3:
			result = 16;
			break;
		  case 4:
			result = 32;
			break;
		  case 5:
			result = 64;
			break;
		  case 6:
			result = 64;
			break;
		}
		break;
	  case 3:
		switch (right) {
		  case 0:
			result = 8;
			break;
		  case 1:
			result = 7;
			break;
		  case 2:
			result = 16;
			break;
		  case 3:
			result = 32;
			break;
		  case 4:
			result = 64;
			break;
		  case 5:
			result = 64;
			break;
		  case 6:
			result = 64;
			break;
		}
		break;
	  case 4:
		switch (right) {
		  case 0:
			result = 16;
			break;
		  case 1:
			result = 15;
			break;
		  case 2:
			result = 32;
			break;
		  case 3:
			result = 64;
			break;
		  case 4:
			result = 64;
			break;
		  case 5:
			result = 64;
			break;
		  case 6:
			result = 64;
			break;
		}
		break;
	  case 5:
		switch (right) {
		  case 0:
			result = 32;
			break;
		  case 1:
			result = 31;
			break;
		  case 2:
			result = 64;
			break;
		  case 3:
			result = 64;
			break;
		  case 4:
			result = 64;
			break;
		  case 5:
			result = 64;
			break;
		  case 6:
			result = 64;
			break;
		}
		break;
	  case 6:
		switch (right) {
		  case 0:
			result = 64;
			break;
		  case 1:
			result = 127;
			break;
		  case 2:
			result = 64;
			break;
		  case 3:
			result = 64;
			break;
		  case 4:
			result = 64;
			break;
		  case 5:
			result = 64;
			break;
		  case 6:
			result = 64;
			break;
		}
		break;
	}
	if (result == 0) throw new RuntimeException("Range04.addNoChoose(" + left + ", " + right + ") is undefined");
	return result;
  }  
  public static int addSet(int leftTokens, int rightTokens) {
	int result = -1;
	for (int left = 0; (1 << left) <= leftTokens; left++) {
	  if ((leftTokens & (1 << left)) == 0) continue;
	  for (int right = 0; (1 << right) <= rightTokens; right++) {
		if ((rightTokens & (1 << right)) != 0) {
		  if (result == -1) result = addNoChoose(left, right);
		  else result = Abstraction.meetArith(result, addNoChoose(left, right));
		}
	  }
	}
	return result;
  }  
  public static int div(int left$, int right$) {
	if (left$ == LT0 && right$ == LT0) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == LT0 && right$ == R0) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == LT0 && right$ == R1) return LT0;
	if (left$ == LT0 && right$ == R2) return LT0;
	if (left$ == LT0 && right$ == R3) return LT0;
	if (left$ == LT0 && right$ == R4) return LT0;
	if (left$ == LT0 && right$ == GT4) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == R0 && right$ == LT0) return R0;
	if (left$ == R0 && right$ == R0) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == R0 && right$ == R1) return R0;
	if (left$ == R0 && right$ == R2) return R0;
	if (left$ == R0 && right$ == R3) return R0;
	if (left$ == R0 && right$ == R4) return R0;
	if (left$ == R0 && right$ == GT4) return R0;
	if (left$ == R1 && right$ == LT0) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == R1 && right$ == R0) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == R1 && right$ == R1) return R1;
	if (left$ == R1 && right$ == R2) return R0;
	if (left$ == R1 && right$ == R3) return R0;
	if (left$ == R1 && right$ == R4) return R0;
	if (left$ == R1 && right$ == GT4) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == R2 && right$ == LT0) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == R2 && right$ == R0) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == R2 && right$ == R1) return R2;
	if (left$ == R2 && right$ == R2) return R1;
	if (left$ == R2 && right$ == R3) return R0;
	if (left$ == R2 && right$ == R4) return R0;
	if (left$ == R2 && right$ == GT4) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == R3 && right$ == LT0) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == R3 && right$ == R0) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == R3 && right$ == R1) return R3;
	if (left$ == R3 && right$ == R2) return R1;
	if (left$ == R3 && right$ == R3) return R1;
	if (left$ == R3 && right$ == R4) return R0;
	if (left$ == R3 && right$ == GT4) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == R4 && right$ == LT0) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == R4 && right$ == R0) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == R4 && right$ == R1) return R4;
	if (left$ == R4 && right$ == R2) return R2;
	if (left$ == R4 && right$ == R3) return R1;
	if (left$ == R4 && right$ == R4) return R1;
	if (left$ == R4 && right$ == GT4) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == GT4 && right$ == LT0) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == GT4 && right$ == R0) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == GT4 && right$ == R1) return GT4;
	if (left$ == GT4 && right$ == R2) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2));
	if (left$ == GT4 && right$ == R3) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1));
	if (left$ == GT4 && right$ == R4) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1));
	if (left$ == GT4 && right$ == GT4) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	throw new RuntimeException("Range04.div(" + left$ + ", " + right$ + ") is undefined");
  }  
  private static int divNoChoose(int left, int right) {
	int result = 0;
	switch (left) {
	  case 0:
		switch (right) {
		  case 0:
			result = 127;
			break;
		  case 1:
			result = 1;
			break;
		  case 2:
			result = 1;
			break;
		  case 3:
			result = 1;
			break;
		  case 4:
			result = 1;
			break;
		  case 5:
			result = 1;
			break;
		  case 6:
			result = 1;
			break;
		}
		break;
	  case 1:
		switch (right) {
		  case 0:
			result = 127;
			break;
		  case 1:
			result = 127;
			break;
		  case 2:
			result = 2;
			break;
		  case 3:
			result = 2;
			break;
		  case 4:
			result = 2;
			break;
		  case 5:
			result = 2;
			break;
		  case 6:
			result = 127;
			break;
		}
		break;
	  case 2:
		switch (right) {
		  case 0:
			result = 127;
			break;
		  case 1:
			result = 127;
			break;
		  case 2:
			result = 4;
			break;
		  case 3:
			result = 1;
			break;
		  case 4:
			result = 1;
			break;
		  case 5:
			result = 1;
			break;
		  case 6:
			result = 127;
			break;
		}
		break;
	  case 3:
		switch (right) {
		  case 0:
			result = 127;
			break;
		  case 1:
			result = 127;
			break;
		  case 2:
			result = 8;
			break;
		  case 3:
			result = 4;
			break;
		  case 4:
			result = 1;
			break;
		  case 5:
			result = 1;
			break;
		  case 6:
			result = 127;
			break;
		}
		break;
	  case 4:
		switch (right) {
		  case 0:
			result = 127;
			break;
		  case 1:
			result = 127;
			break;
		  case 2:
			result = 16;
			break;
		  case 3:
			result = 4;
			break;
		  case 4:
			result = 4;
			break;
		  case 5:
			result = 1;
			break;
		  case 6:
			result = 127;
			break;
		}
		break;
	  case 5:
		switch (right) {
		  case 0:
			result = 127;
			break;
		  case 1:
			result = 127;
			break;
		  case 2:
			result = 32;
			break;
		  case 3:
			result = 8;
			break;
		  case 4:
			result = 4;
			break;
		  case 5:
			result = 4;
			break;
		  case 6:
			result = 127;
			break;
		}
		break;
	  case 6:
		switch (right) {
		  case 0:
			result = 127;
			break;
		  case 1:
			result = 127;
			break;
		  case 2:
			result = 64;
			break;
		  case 3:
			result = 120;
			break;
		  case 4:
			result = 124;
			break;
		  case 5:
			result = 124;
			break;
		  case 6:
			result = 127;
			break;
		}
		break;
	}
	if (result == 0) throw new RuntimeException("Range04.divNoChoose(" + left + ", " + right + ") is undefined");
	return result;
  }  
  public static int divSet(int leftTokens, int rightTokens) {
	int result = -1;
	for (int left = 0; (1 << left) <= leftTokens; left++) {
	  if ((leftTokens & (1 << left)) == 0) continue;
	  for (int right = 0; (1 << right) <= rightTokens; right++) {
		if ((rightTokens & (1 << right)) != 0) {
		  if (result == -1) result = divNoChoose(left, right);
		  else result = Abstraction.meetArith(result, divNoChoose(left, right));
		}
	  }
	}
	return result;
  }  
  public static boolean eq(int left$, int right$) {
	if (left$ == LT0 && right$ == LT0) return Abstraction.choose();
	if (left$ == LT0 && right$ == R0) return false;
	if (left$ == LT0 && right$ == R1) return false;
	if (left$ == LT0 && right$ == R2) return false;
	if (left$ == LT0 && right$ == R3) return false;
	if (left$ == LT0 && right$ == R4) return false;
	if (left$ == LT0 && right$ == GT4) return false;
	if (left$ == R0 && right$ == LT0) return false;
	if (left$ == R0 && right$ == R0) return true;
	if (left$ == R0 && right$ == R1) return false;
	if (left$ == R0 && right$ == R2) return false;
	if (left$ == R0 && right$ == R3) return false;
	if (left$ == R0 && right$ == R4) return false;
	if (left$ == R0 && right$ == GT4) return false;
	if (left$ == R1 && right$ == LT0) return false;
	if (left$ == R1 && right$ == R0) return false;
	if (left$ == R1 && right$ == R1) return true;
	if (left$ == R1 && right$ == R2) return false;
	if (left$ == R1 && right$ == R3) return false;
	if (left$ == R1 && right$ == R4) return false;
	if (left$ == R1 && right$ == GT4) return false;
	if (left$ == R2 && right$ == LT0) return false;
	if (left$ == R2 && right$ == R0) return false;
	if (left$ == R2 && right$ == R1) return false;
	if (left$ == R2 && right$ == R2) return true;
	if (left$ == R2 && right$ == R3) return false;
	if (left$ == R2 && right$ == R4) return false;
	if (left$ == R2 && right$ == GT4) return false;
	if (left$ == R3 && right$ == LT0) return false;
	if (left$ == R3 && right$ == R0) return false;
	if (left$ == R3 && right$ == R1) return false;
	if (left$ == R3 && right$ == R2) return false;
	if (left$ == R3 && right$ == R3) return true;
	if (left$ == R3 && right$ == R4) return false;
	if (left$ == R3 && right$ == GT4) return false;
	if (left$ == R4 && right$ == LT0) return false;
	if (left$ == R4 && right$ == R0) return false;
	if (left$ == R4 && right$ == R1) return false;
	if (left$ == R4 && right$ == R2) return false;
	if (left$ == R4 && right$ == R3) return false;
	if (left$ == R4 && right$ == R4) return true;
	if (left$ == R4 && right$ == GT4) return false;
	if (left$ == GT4 && right$ == LT0) return false;
	if (left$ == GT4 && right$ == R0) return false;
	if (left$ == GT4 && right$ == R1) return false;
	if (left$ == GT4 && right$ == R2) return false;
	if (left$ == GT4 && right$ == R3) return false;
	if (left$ == GT4 && right$ == R4) return false;
	if (left$ == GT4 && right$ == GT4) return Abstraction.choose();
	throw new RuntimeException("Range04.eq(" + left$ + ", " + right$ + ") is undefined");
  }  
  private static byte eqNoChoose(int left, int right) {
	byte result = -1;
	switch (left) {
	  case 0:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 0;
			break;
		  case 2:
			result = 0;
			break;
		  case 3:
			result = 0;
			break;
		  case 4:
			result = 0;
			break;
		  case 5:
			result = 0;
			break;
		  case 6:
			result = 0;
			break;
		}
		break;
	  case 1:
		switch (right) {
		  case 0:
			result = 0;
			break;
		  case 1:
			result = 2;
			break;
		  case 2:
			result = 0;
			break;
		  case 3:
			result = 0;
			break;
		  case 4:
			result = 0;
			break;
		  case 5:
			result = 0;
			break;
		  case 6:
			result = 0;
			break;
		}
		break;
	  case 2:
		switch (right) {
		  case 0:
			result = 0;
			break;
		  case 1:
			result = 0;
			break;
		  case 2:
			result = 1;
			break;
		  case 3:
			result = 0;
			break;
		  case 4:
			result = 0;
			break;
		  case 5:
			result = 0;
			break;
		  case 6:
			result = 0;
			break;
		}
		break;
	  case 3:
		switch (right) {
		  case 0:
			result = 0;
			break;
		  case 1:
			result = 0;
			break;
		  case 2:
			result = 0;
			break;
		  case 3:
			result = 1;
			break;
		  case 4:
			result = 0;
			break;
		  case 5:
			result = 0;
			break;
		  case 6:
			result = 0;
			break;
		}
		break;
	  case 4:
		switch (right) {
		  case 0:
			result = 0;
			break;
		  case 1:
			result = 0;
			break;
		  case 2:
			result = 0;
			break;
		  case 3:
			result = 0;
			break;
		  case 4:
			result = 1;
			break;
		  case 5:
			result = 0;
			break;
		  case 6:
			result = 0;
			break;
		}
		break;
	  case 5:
		switch (right) {
		  case 0:
			result = 0;
			break;
		  case 1:
			result = 0;
			break;
		  case 2:
			result = 0;
			break;
		  case 3:
			result = 0;
			break;
		  case 4:
			result = 0;
			break;
		  case 5:
			result = 1;
			break;
		  case 6:
			result = 0;
			break;
		}
		break;
	  case 6:
		switch (right) {
		  case 0:
			result = 0;
			break;
		  case 1:
			result = 0;
			break;
		  case 2:
			result = 0;
			break;
		  case 3:
			result = 0;
			break;
		  case 4:
			result = 0;
			break;
		  case 5:
			result = 0;
			break;
		  case 6:
			result = 2;
			break;
		}
		break;
	}
	if (result == -1) throw new RuntimeException("Range04.eqNoChoose(" + left + ", " + right + ") is undefined");
	return result;
  }  
  public static byte eqSet(int leftTokens, int rightTokens) {
	byte result = -1;
	for (int left = 0; (1 << left) <= leftTokens; left++) {
	  if ((leftTokens & (1 << left)) == 0) continue;
	  for (int right = 0; (1 << right) <= rightTokens; right++) {
		if ((rightTokens & (1 << right)) != 0) {
		  if (result == -1) result = eqNoChoose(left, right);
		  else result = Abstraction.meetTest(result, eqNoChoose(left, right));
		}
	  }
	}
	return result;
  }  
  public static boolean ge(int left$, int right$) {
	if (left$ == LT0 && right$ == LT0) return Abstraction.choose();
	if (left$ == LT0 && right$ == R0) return false;
	if (left$ == LT0 && right$ == R1) return false;
	if (left$ == LT0 && right$ == R2) return false;
	if (left$ == LT0 && right$ == R3) return false;
	if (left$ == LT0 && right$ == R4) return false;
	if (left$ == LT0 && right$ == GT4) return false;
	if (left$ == R0 && right$ == LT0) return true;
	if (left$ == R0 && right$ == R0) return true;
	if (left$ == R0 && right$ == R1) return false;
	if (left$ == R0 && right$ == R2) return false;
	if (left$ == R0 && right$ == R3) return false;
	if (left$ == R0 && right$ == R4) return false;
	if (left$ == R0 && right$ == GT4) return false;
	if (left$ == R1 && right$ == LT0) return true;
	if (left$ == R1 && right$ == R0) return true;
	if (left$ == R1 && right$ == R1) return true;
	if (left$ == R1 && right$ == R2) return false;
	if (left$ == R1 && right$ == R3) return false;
	if (left$ == R1 && right$ == R4) return false;
	if (left$ == R1 && right$ == GT4) return false;
	if (left$ == R2 && right$ == LT0) return true;
	if (left$ == R2 && right$ == R0) return true;
	if (left$ == R2 && right$ == R1) return true;
	if (left$ == R2 && right$ == R2) return true;
	if (left$ == R2 && right$ == R3) return false;
	if (left$ == R2 && right$ == R4) return false;
	if (left$ == R2 && right$ == GT4) return false;
	if (left$ == R3 && right$ == LT0) return true;
	if (left$ == R3 && right$ == R0) return true;
	if (left$ == R3 && right$ == R1) return true;
	if (left$ == R3 && right$ == R2) return true;
	if (left$ == R3 && right$ == R3) return true;
	if (left$ == R3 && right$ == R4) return false;
	if (left$ == R3 && right$ == GT4) return false;
	if (left$ == R4 && right$ == LT0) return true;
	if (left$ == R4 && right$ == R0) return true;
	if (left$ == R4 && right$ == R1) return true;
	if (left$ == R4 && right$ == R2) return true;
	if (left$ == R4 && right$ == R3) return true;
	if (left$ == R4 && right$ == R4) return true;
	if (left$ == R4 && right$ == GT4) return false;
	if (left$ == GT4 && right$ == LT0) return true;
	if (left$ == GT4 && right$ == R0) return true;
	if (left$ == GT4 && right$ == R1) return true;
	if (left$ == GT4 && right$ == R2) return true;
	if (left$ == GT4 && right$ == R3) return true;
	if (left$ == GT4 && right$ == R4) return true;
	if (left$ == GT4 && right$ == GT4) return Abstraction.choose();
	throw new RuntimeException("Range04.ge(" + left$ + ", " + right$ + ") is undefined");
  }  
  private static byte geNoChoose(int left, int right) {
	byte result = -1;
	switch (left) {
	  case 0:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 1;
			break;
		  case 2:
			result = 0;
			break;
		  case 3:
			result = 0;
			break;
		  case 4:
			result = 0;
			break;
		  case 5:
			result = 0;
			break;
		  case 6:
			result = 0;
			break;
		}
		break;
	  case 1:
		switch (right) {
		  case 0:
			result = 0;
			break;
		  case 1:
			result = 2;
			break;
		  case 2:
			result = 0;
			break;
		  case 3:
			result = 0;
			break;
		  case 4:
			result = 0;
			break;
		  case 5:
			result = 0;
			break;
		  case 6:
			result = 0;
			break;
		}
		break;
	  case 2:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 1;
			break;
		  case 2:
			result = 1;
			break;
		  case 3:
			result = 0;
			break;
		  case 4:
			result = 0;
			break;
		  case 5:
			result = 0;
			break;
		  case 6:
			result = 0;
			break;
		}
		break;
	  case 3:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 1;
			break;
		  case 2:
			result = 1;
			break;
		  case 3:
			result = 1;
			break;
		  case 4:
			result = 0;
			break;
		  case 5:
			result = 0;
			break;
		  case 6:
			result = 0;
			break;
		}
		break;
	  case 4:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 1;
			break;
		  case 2:
			result = 1;
			break;
		  case 3:
			result = 1;
			break;
		  case 4:
			result = 1;
			break;
		  case 5:
			result = 0;
			break;
		  case 6:
			result = 0;
			break;
		}
		break;
	  case 5:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 1;
			break;
		  case 2:
			result = 1;
			break;
		  case 3:
			result = 1;
			break;
		  case 4:
			result = 1;
			break;
		  case 5:
			result = 1;
			break;
		  case 6:
			result = 0;
			break;
		}
		break;
	  case 6:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 1;
			break;
		  case 2:
			result = 1;
			break;
		  case 3:
			result = 1;
			break;
		  case 4:
			result = 1;
			break;
		  case 5:
			result = 1;
			break;
		  case 6:
			result = 2;
			break;
		}
		break;
	}
	if (result == -1) throw new RuntimeException("Range04.geNoChoose(" + left + ", " + right + ") is undefined");
	return result;
  }  
  public static byte geSet(int leftTokens, int rightTokens) {
	byte result = -1;
	for (int left = 0; (1 << left) <= leftTokens; left++) {
	  if ((leftTokens & (1 << left)) == 0) continue;
	  for (int right = 0; (1 << right) <= rightTokens; right++) {
		if ((rightTokens & (1 << right)) != 0) {
		  if (result == -1) result = geNoChoose(left, right);
		  else result = Abstraction.meetTest(result, geNoChoose(left, right));
		}
	  }
	}
	return result;
  }  
  public static String getBASLRepresentation() {
	return
	  "abstraction Range04 extends integral \n"
	  + "  begin\n"
	  + "    TOKENS = {LT0, R0, R1, R2, R3, R4, GT4};\n"
	  + "    DEFAULT = R0;\n"
	  + "    ONE2ONE = {R0, R1, R2, R3, R4};\n"
	  + "    abstract (n)\n"
	  + "      begin\n"
	  + "        n < 0 -> LT0;\n"
	  + "        n == 0 -> R0;\n"
	  + "        n == 1 -> R1;\n"
	  + "        n == 2 -> R2;\n"
	  + "        n == 3 -> R3;\n"
	  + "        n == 4 -> R4;\n"
	  + "        n > 4 -> GT4;\n"
	  + "      end\n"
	  + "    operator + add \n"
	  + "      begin\n"
	  + "        (LT0, LT0) -> LT0;\n"
	  + "        (LT0, R0) -> LT0;\n"
	  + "        (LT0, R1) -> {LT0, R0};\n"
	  + "        (LT0, R2) -> {LT0, R0, R1};\n"
	  + "        (LT0, R3) -> {LT0, R0, R1, R2};\n"
	  + "        (LT0, R4) -> {LT0, R0, R1, R2, R3};\n"
	  + "        (LT0, GT4) -> {LT0, R0, R1, R2, R3, R4, GT4};\n"
	  + "        (R0, LT0) -> LT0;\n"
	  + "        (R0, R0) -> R0;\n"
	  + "        (R0, R1) -> R1;\n"
	  + "        (R0, R2) -> R2;\n"
	  + "        (R0, R3) -> R3;\n"
	  + "        (R0, R4) -> R4;\n"
	  + "        (R0, GT4) -> GT4;\n"
	  + "        (R1, LT0) -> {LT0, R0};\n"
	  + "        (R1, R0) -> R1;\n"
	  + "        (R1, R1) -> R2;\n"
	  + "        (R1, R2) -> R3;\n"
	  + "        (R1, R3) -> R4;\n"
	  + "        (R1, R4) -> GT4;\n"
	  + "        (R1, GT4) -> GT4;\n"
	  + "        (R2, LT0) -> {LT0, R0, R1};\n"
	  + "        (R2, R0) -> R2;\n"
	  + "        (R2, R1) -> R3;\n"
	  + "        (R2, R2) -> R4;\n"
	  + "        (R2, R3) -> GT4;\n"
	  + "        (R2, R4) -> GT4;\n"
	  + "        (R2, GT4) -> GT4;\n"
	  + "        (R3, LT0) -> {LT0, R0, R1, R2};\n"
	  + "        (R3, R0) -> R3;\n"
	  + "        (R3, R1) -> R4;\n"
	  + "        (R3, R2) -> GT4;\n"
	  + "        (R3, R3) -> GT4;\n"
	  + "        (R3, R4) -> GT4;\n"
	  + "        (R3, GT4) -> GT4;\n"
	  + "        (R4, LT0) -> {LT0, R0, R1, R2, R3};\n"
	  + "        (R4, R0) -> R4;\n"
	  + "        (R4, R1) -> GT4;\n"
	  + "        (R4, R2) -> GT4;\n"
	  + "        (R4, R3) -> GT4;\n"
	  + "        (R4, R4) -> GT4;\n"
	  + "        (R4, GT4) -> GT4;\n"
	  + "        (GT4, LT0) -> {LT0, R0, R1, R2, R3, R4, GT4};\n"
	  + "        (GT4, R0) -> GT4;\n"
	  + "        (GT4, R1) -> GT4;\n"
	  + "        (GT4, R2) -> GT4;\n"
	  + "        (GT4, R3) -> GT4;\n"
	  + "        (GT4, R4) -> GT4;\n"
	  + "        (GT4, GT4) -> GT4;\n"
	  + "      end\n"
	  + "    operator - sub \n"
	  + "      begin\n"
	  + "        (LT0, LT0) -> {LT0, R0, R1, R2, R3, R4, GT4};\n"
	  + "        (LT0, R0) -> LT0;\n"
	  + "        (LT0, R1) -> LT0;\n"
	  + "        (LT0, R2) -> LT0;\n"
	  + "        (LT0, R3) -> LT0;\n"
	  + "        (LT0, R4) -> LT0;\n"
	  + "        (LT0, GT4) -> LT0;\n"
	  + "        (R0, LT0) -> {R1, R2, R3, R4, GT4};\n"
	  + "        (R0, R0) -> R0;\n"
	  + "        (R0, R1) -> LT0;\n"
	  + "        (R0, R2) -> LT0;\n"
	  + "        (R0, R3) -> LT0;\n"
	  + "        (R0, R4) -> LT0;\n"
	  + "        (R0, GT4) -> LT0;\n"
	  + "        (R1, LT0) -> {R2, R3, R4, GT4};\n"
	  + "        (R1, R0) -> R1;\n"
	  + "        (R1, R1) -> R0;\n"
	  + "        (R1, R2) -> LT0;\n"
	  + "        (R1, R3) -> LT0;\n"
	  + "        (R1, R4) -> LT0;\n"
	  + "        (R1, GT4) -> LT0;\n"
	  + "        (R2, LT0) -> {R3, R4, GT4};\n"
	  + "        (R2, R0) -> R2;\n"
	  + "        (R2, R1) -> R1;\n"
	  + "        (R2, R2) -> R0;\n"
	  + "        (R2, R3) -> LT0;\n"
	  + "        (R2, R4) -> LT0;\n"
	  + "        (R2, GT4) -> LT0;\n"
	  + "        (R3, LT0) -> {R4, GT4};\n"
	  + "        (R3, R0) -> R3;\n"
	  + "        (R3, R1) -> R2;\n"
	  + "        (R3, R2) -> R1;\n"
	  + "        (R3, R3) -> R0;\n"
	  + "        (R3, R4) -> LT0;\n"
	  + "        (R3, GT4) -> LT0;\n"
	  + "        (R4, LT0) -> GT4;\n"
	  + "        (R4, R0) -> R4;\n"
	  + "        (R4, R1) -> R3;\n"
	  + "        (R4, R2) -> R2;\n"
	  + "        (R4, R3) -> R1;\n"
	  + "        (R4, R4) -> R0;\n"
	  + "        (R4, GT4) -> LT0;\n"
	  + "        (GT4, LT0) -> GT4;\n"
	  + "        (GT4, R0) -> GT4;\n"
	  + "        (GT4, R1) -> {R4, GT4};\n"
	  + "        (GT4, R2) -> {R3, R4, GT4};\n"
	  + "        (GT4, R3) -> {R2, R3, R4, GT4};\n"
	  + "        (GT4, R4) -> {R1, R2, R3, R4, GT4};\n"
	  + "        (GT4, GT4) -> {LT0, R0, R1, R2, R3, R4, GT4};\n"
	  + "      end\n"
	  + "    operator * mul \n"
	  + "      begin\n"
	  + "        (LT0, LT0) -> {R1, R2, R3, R4, GT4};\n"
	  + "        (LT0, R0) -> R0;\n"
	  + "        (LT0, R1) -> LT0;\n"
	  + "        (LT0, R2) -> LT0;\n"
	  + "        (LT0, R3) -> LT0;\n"
	  + "        (LT0, R4) -> LT0;\n"
	  + "        (LT0, GT4) -> {LT0, R1, R2, R3, R4, GT4};\n"
	  + "        (R0, LT0) -> R0;\n"
	  + "        (R0, R0) -> R0;\n"
	  + "        (R0, R1) -> R0;\n"
	  + "        (R0, R2) -> R0;\n"
	  + "        (R0, R3) -> R0;\n"
	  + "        (R0, R4) -> R0;\n"
	  + "        (R0, GT4) -> R0;\n"
	  + "        (R1, LT0) -> LT0;\n"
	  + "        (R1, R0) -> R0;\n"
	  + "        (R1, R1) -> R1;\n"
	  + "        (R1, R2) -> R2;\n"
	  + "        (R1, R3) -> R3;\n"
	  + "        (R1, R4) -> R4;\n"
	  + "        (R1, GT4) -> GT4;\n"
	  + "        (R2, LT0) -> LT0;\n"
	  + "        (R2, R0) -> R0;\n"
	  + "        (R2, R1) -> R2;\n"
	  + "        (R2, R2) -> R4;\n"
	  + "        (R2, R3) -> GT4;\n"
	  + "        (R2, R4) -> GT4;\n"
	  + "        (R2, GT4) -> GT4;\n"
	  + "        (R3, LT0) -> LT0;\n"
	  + "        (R3, R0) -> R0;\n"
	  + "        (R3, R1) -> R3;\n"
	  + "        (R3, R2) -> GT4;\n"
	  + "        (R3, R3) -> GT4;\n"
	  + "        (R3, R4) -> GT4;\n"
	  + "        (R3, GT4) -> GT4;\n"
	  + "        (R4, LT0) -> LT0;\n"
	  + "        (R4, R0) -> R0;\n"
	  + "        (R4, R1) -> R4;\n"
	  + "        (R4, R2) -> GT4;\n"
	  + "        (R4, R3) -> GT4;\n"
	  + "        (R4, R4) -> GT4;\n"
	  + "        (R4, GT4) -> GT4;\n"
	  + "        (GT4, LT0) -> {LT0, R1, R2, R3, R4, GT4};\n"
	  + "        (GT4, R0) -> R0;\n"
	  + "        (GT4, R1) -> GT4;\n"
	  + "        (GT4, R2) -> GT4;\n"
	  + "        (GT4, R3) -> GT4;\n"
	  + "        (GT4, R4) -> GT4;\n"
	  + "        (GT4, GT4) -> {R1, R2, R3, R4, GT4};\n"
	  + "      end\n"
	  + "    operator / div \n"
	  + "      begin\n"
	  + "        (LT0, LT0) -> {LT0, R0, R1, R2, R3, R4, GT4};\n"
	  + "        (LT0, R0) -> T;\n"
	  + "        (LT0, R1) -> LT0;\n"
	  + "        (LT0, R2) -> LT0;\n"
	  + "        (LT0, R3) -> LT0;\n"
	  + "        (LT0, R4) -> LT0;\n"
	  + "        (LT0, GT4) -> {LT0, R0, R1, R2, R3, R4, GT4};\n"
	  + "        (R0, LT0) -> R0;\n"
	  + "        (R0, R0) -> T;\n"
	  + "        (R0, R1) -> R0;\n"
	  + "        (R0, R2) -> R0;\n"
	  + "        (R0, R3) -> R0;\n"
	  + "        (R0, R4) -> R0;\n"
	  + "        (R0, GT4) -> R0;\n"
	  + "        (R1, LT0) -> {LT0, R0, R1, R2, R3, R4, GT4};\n"
	  + "        (R1, R0) -> T;\n"
	  + "        (R1, R1) -> R1;\n"
	  + "        (R1, R2) -> R0;\n"
	  + "        (R1, R3) -> R0;\n"
	  + "        (R1, R4) -> R0;\n"
	  + "        (R1, GT4) -> {LT0, R0, R1, R2, R3, R4, GT4};\n"
	  + "        (R2, LT0) -> {LT0, R0, R1, R2, R3, R4, GT4};\n"
	  + "        (R2, R0) -> T;\n"
	  + "        (R2, R1) -> R2;\n"
	  + "        (R2, R2) -> R1;\n"
	  + "        (R2, R3) -> R0;\n"
	  + "        (R2, R4) -> R0;\n"
	  + "        (R2, GT4) -> {LT0, R0, R1, R2, R3, R4, GT4};\n"
	  + "        (R3, LT0) -> {LT0, R0, R1, R2, R3, R4, GT4};\n"
	  + "        (R3, R0) -> T;\n"
	  + "        (R3, R1) -> R3;\n"
	  + "        (R3, R2) -> R1;\n"
	  + "        (R3, R3) -> R1;\n"
	  + "        (R3, R4) -> R0;\n"
	  + "        (R3, GT4) -> {LT0, R0, R1, R2, R3, R4, GT4};\n"
	  + "        (R4, LT0) -> {LT0, R0, R1, R2, R3, R4, GT4};\n"
	  + "        (R4, R0) -> T;\n"
	  + "        (R4, R1) -> R4;\n"
	  + "        (R4, R2) -> R2;\n"
	  + "        (R4, R3) -> R1;\n"
	  + "        (R4, R4) -> R1;\n"
	  + "        (R4, GT4) -> {LT0, R0, R1, R2, R3, R4, GT4};\n"
	  + "        (GT4, LT0) -> {LT0, R0, R1, R2, R3, R4, GT4};\n"
	  + "        (GT4, R0) -> T;\n"
	  + "        (GT4, R1) -> GT4;\n"
	  + "        (GT4, R2) -> {R2, R3, R4, GT4};\n"
	  + "        (GT4, R3) -> {R1, R2, R3, R4, GT4};\n"
	  + "        (GT4, R4) -> {R1, R2, R3, R4, GT4};\n"
	  + "        (GT4, GT4) -> {LT0, R0, R1, R2, R3, R4, GT4};\n"
	  + "      end\n"
	  + "    operator % rem \n"
	  + "      begin\n"
	  + "        (LT0, LT0) -> {LT0, R0, R1, R2, R3, R4, GT4};\n"
	  + "        (LT0, R0) -> T;\n"
	  + "        (LT0, R1) -> R0;\n"
	  + "        (LT0, R2) -> {R0, R1};\n"
	  + "        (LT0, R3) -> {R0, R1, R2};\n"
	  + "        (LT0, R4) -> {R0, R1, R2, R3};\n"
	  + "        (LT0, GT4) -> {LT0, R0, R1, R2, R3, R4, GT4};\n"
	  + "        (R0, LT0) -> R0;\n"
	  + "        (R0, R0) -> T;\n"
	  + "        (R0, R1) -> R0;\n"
	  + "        (R0, R2) -> R0;\n"
	  + "        (R0, R3) -> R0;\n"
	  + "        (R0, R4) -> R0;\n"
	  + "        (R0, GT4) -> R0;\n"
	  + "        (R1, LT0) -> {LT0, R0, R1, R2, R3, R4, GT4};\n"
	  + "        (R1, R0) -> T;\n"
	  + "        (R1, R1) -> R0;\n"
	  + "        (R1, R2) -> R1;\n"
	  + "        (R1, R3) -> R1;\n"
	  + "        (R1, R4) -> R1;\n"
	  + "        (R1, GT4) -> {LT0, R0, R1, R2, R3, R4, GT4};\n"
	  + "        (R2, LT0) -> {LT0, R0, R1, R2, R3, R4, GT4};\n"
	  + "        (R2, R0) -> T;\n"
	  + "        (R2, R1) -> R0;\n"
	  + "        (R2, R2) -> R0;\n"
	  + "        (R2, R3) -> R2;\n"
	  + "        (R2, R4) -> R2;\n"
	  + "        (R2, GT4) -> {LT0, R0, R1, R2, R3, R4, GT4};\n"
	  + "        (R3, LT0) -> {LT0, R0, R1, R2, R3, R4, GT4};\n"
	  + "        (R3, R0) -> T;\n"
	  + "        (R3, R1) -> R0;\n"
	  + "        (R3, R2) -> R1;\n"
	  + "        (R3, R3) -> R0;\n"
	  + "        (R3, R4) -> R3;\n"
	  + "        (R3, GT4) -> {LT0, R0, R1, R2, R3, R4, GT4};\n"
	  + "        (R4, LT0) -> {LT0, R0, R1, R2, R3, R4, GT4};\n"
	  + "        (R4, R0) -> T;\n"
	  + "        (R4, R1) -> R0;\n"
	  + "        (R4, R2) -> R0;\n"
	  + "        (R4, R3) -> R1;\n"
	  + "        (R4, R4) -> R0;\n"
	  + "        (R4, GT4) -> {LT0, R0, R1, R2, R3, R4, GT4};\n"
	  + "        (GT4, LT0) -> {LT0, R0, R1, R2, R3, R4, GT4};\n"
	  + "        (GT4, R0) -> T;\n"
	  + "        (GT4, R1) -> R0;\n"
	  + "        (GT4, R2) -> {R0, R1};\n"
	  + "        (GT4, R3) -> {R0, R1, R2};\n"
	  + "        (GT4, R4) -> {R0, R1, R2, R3};\n"
	  + "        (GT4, GT4) -> {LT0, R0, R1, R2, R3, R4, GT4};\n"
	  + "      end\n"
	  + "    test == eq \n"
	  + "      begin\n"
	  + "        (LT0, LT0) -> {TRUE, FALSE};\n"
	  + "        (LT0, R0) -> FALSE;\n"
	  + "        (LT0, R1) -> FALSE;\n"
	  + "        (LT0, R2) -> FALSE;\n"
	  + "        (LT0, R3) -> FALSE;\n"
	  + "        (LT0, R4) -> FALSE;\n"
	  + "        (LT0, GT4) -> FALSE;\n"
	  + "        (R0, LT0) -> FALSE;\n"
	  + "        (R0, R0) -> TRUE;\n"
	  + "        (R0, R1) -> FALSE;\n"
	  + "        (R0, R2) -> FALSE;\n"
	  + "        (R0, R3) -> FALSE;\n"
	  + "        (R0, R4) -> FALSE;\n"
	  + "        (R0, GT4) -> FALSE;\n"
	  + "        (R1, LT0) -> FALSE;\n"
	  + "        (R1, R0) -> FALSE;\n"
	  + "        (R1, R1) -> TRUE;\n"
	  + "        (R1, R2) -> FALSE;\n"
	  + "        (R1, R3) -> FALSE;\n"
	  + "        (R1, R4) -> FALSE;\n"
	  + "        (R1, GT4) -> FALSE;\n"
	  + "        (R2, LT0) -> FALSE;\n"
	  + "        (R2, R0) -> FALSE;\n"
	  + "        (R2, R1) -> FALSE;\n"
	  + "        (R2, R2) -> TRUE;\n"
	  + "        (R2, R3) -> FALSE;\n"
	  + "        (R2, R4) -> FALSE;\n"
	  + "        (R2, GT4) -> FALSE;\n"
	  + "        (R3, LT0) -> FALSE;\n"
	  + "        (R3, R0) -> FALSE;\n"
	  + "        (R3, R1) -> FALSE;\n"
	  + "        (R3, R2) -> FALSE;\n"
	  + "        (R3, R3) -> TRUE;\n"
	  + "        (R3, R4) -> FALSE;\n"
	  + "        (R3, GT4) -> FALSE;\n"
	  + "        (R4, LT0) -> FALSE;\n"
	  + "        (R4, R0) -> FALSE;\n"
	  + "        (R4, R1) -> FALSE;\n"
	  + "        (R4, R2) -> FALSE;\n"
	  + "        (R4, R3) -> FALSE;\n"
	  + "        (R4, R4) -> TRUE;\n"
	  + "        (R4, GT4) -> FALSE;\n"
	  + "        (GT4, LT0) -> FALSE;\n"
	  + "        (GT4, R0) -> FALSE;\n"
	  + "        (GT4, R1) -> FALSE;\n"
	  + "        (GT4, R2) -> FALSE;\n"
	  + "        (GT4, R3) -> FALSE;\n"
	  + "        (GT4, R4) -> FALSE;\n"
	  + "        (GT4, GT4) -> {TRUE, FALSE};\n"
	  + "      end\n"
	  + "    test != neq \n"
	  + "      begin\n"
	  + "        (LT0, LT0) -> {TRUE, FALSE};\n"
	  + "        (LT0, R0) -> TRUE;\n"
	  + "        (LT0, R1) -> TRUE;\n"
	  + "        (LT0, R2) -> TRUE;\n"
	  + "        (LT0, R3) -> TRUE;\n"
	  + "        (LT0, R4) -> TRUE;\n"
	  + "        (LT0, GT4) -> TRUE;\n"
	  + "        (R0, LT0) -> TRUE;\n"
	  + "        (R0, R0) -> FALSE;\n"
	  + "        (R0, R1) -> TRUE;\n"
	  + "        (R0, R2) -> TRUE;\n"
	  + "        (R0, R3) -> TRUE;\n"
	  + "        (R0, R4) -> TRUE;\n"
	  + "        (R0, GT4) -> TRUE;\n"
	  + "        (R1, LT0) -> TRUE;\n"
	  + "        (R1, R0) -> TRUE;\n"
	  + "        (R1, R1) -> FALSE;\n"
	  + "        (R1, R2) -> TRUE;\n"
	  + "        (R1, R3) -> TRUE;\n"
	  + "        (R1, R4) -> TRUE;\n"
	  + "        (R1, GT4) -> TRUE;\n"
	  + "        (R2, LT0) -> TRUE;\n"
	  + "        (R2, R0) -> TRUE;\n"
	  + "        (R2, R1) -> TRUE;\n"
	  + "        (R2, R2) -> FALSE;\n"
	  + "        (R2, R3) -> TRUE;\n"
	  + "        (R2, R4) -> TRUE;\n"
	  + "        (R2, GT4) -> TRUE;\n"
	  + "        (R3, LT0) -> TRUE;\n"
	  + "        (R3, R0) -> TRUE;\n"
	  + "        (R3, R1) -> TRUE;\n"
	  + "        (R3, R2) -> TRUE;\n"
	  + "        (R3, R3) -> FALSE;\n"
	  + "        (R3, R4) -> TRUE;\n"
	  + "        (R3, GT4) -> TRUE;\n"
	  + "        (R4, LT0) -> TRUE;\n"
	  + "        (R4, R0) -> TRUE;\n"
	  + "        (R4, R1) -> TRUE;\n"
	  + "        (R4, R2) -> TRUE;\n"
	  + "        (R4, R3) -> TRUE;\n"
	  + "        (R4, R4) -> FALSE;\n"
	  + "        (R4, GT4) -> TRUE;\n"
	  + "        (GT4, LT0) -> TRUE;\n"
	  + "        (GT4, R0) -> TRUE;\n"
	  + "        (GT4, R1) -> TRUE;\n"
	  + "        (GT4, R2) -> TRUE;\n"
	  + "        (GT4, R3) -> TRUE;\n"
	  + "        (GT4, R4) -> TRUE;\n"
	  + "        (GT4, GT4) -> {TRUE, FALSE};\n"
	  + "      end\n"
	  + "    test < lt \n"
	  + "      begin\n"
	  + "        (LT0, LT0) -> {TRUE, FALSE};\n"
	  + "        (LT0, R0) -> TRUE;\n"
	  + "        (LT0, R1) -> TRUE;\n"
	  + "        (LT0, R2) -> TRUE;\n"
	  + "        (LT0, R3) -> TRUE;\n"
	  + "        (LT0, R4) -> TRUE;\n"
	  + "        (LT0, GT4) -> TRUE;\n"
	  + "        (R0, LT0) -> FALSE;\n"
	  + "        (R0, R0) -> FALSE;\n"
	  + "        (R0, R1) -> TRUE;\n"
	  + "        (R0, R2) -> TRUE;\n"
	  + "        (R0, R3) -> TRUE;\n"
	  + "        (R0, R4) -> TRUE;\n"
	  + "        (R0, GT4) -> TRUE;\n"
	  + "        (R1, LT0) -> FALSE;\n"
	  + "        (R1, R0) -> FALSE;\n"
	  + "        (R1, R1) -> FALSE;\n"
	  + "        (R1, R2) -> TRUE;\n"
	  + "        (R1, R3) -> TRUE;\n"
	  + "        (R1, R4) -> TRUE;\n"
	  + "        (R1, GT4) -> TRUE;\n"
	  + "        (R2, LT0) -> FALSE;\n"
	  + "        (R2, R0) -> FALSE;\n"
	  + "        (R2, R1) -> FALSE;\n"
	  + "        (R2, R2) -> FALSE;\n"
	  + "        (R2, R3) -> TRUE;\n"
	  + "        (R2, R4) -> TRUE;\n"
	  + "        (R2, GT4) -> TRUE;\n"
	  + "        (R3, LT0) -> FALSE;\n"
	  + "        (R3, R0) -> FALSE;\n"
	  + "        (R3, R1) -> FALSE;\n"
	  + "        (R3, R2) -> FALSE;\n"
	  + "        (R3, R3) -> FALSE;\n"
	  + "        (R3, R4) -> TRUE;\n"
	  + "        (R3, GT4) -> TRUE;\n"
	  + "        (R4, LT0) -> FALSE;\n"
	  + "        (R4, R0) -> FALSE;\n"
	  + "        (R4, R1) -> FALSE;\n"
	  + "        (R4, R2) -> FALSE;\n"
	  + "        (R4, R3) -> FALSE;\n"
	  + "        (R4, R4) -> FALSE;\n"
	  + "        (R4, GT4) -> TRUE;\n"
	  + "        (GT4, LT0) -> FALSE;\n"
	  + "        (GT4, R0) -> FALSE;\n"
	  + "        (GT4, R1) -> FALSE;\n"
	  + "        (GT4, R2) -> FALSE;\n"
	  + "        (GT4, R3) -> FALSE;\n"
	  + "        (GT4, R4) -> FALSE;\n"
	  + "        (GT4, GT4) -> {TRUE, FALSE};\n"
	  + "      end\n"
	  + "    test <= le \n"
	  + "      begin\n"
	  + "        (LT0, LT0) -> {TRUE, FALSE};\n"
	  + "        (LT0, R0) -> TRUE;\n"
	  + "        (LT0, R1) -> TRUE;\n"
	  + "        (LT0, R2) -> TRUE;\n"
	  + "        (LT0, R3) -> TRUE;\n"
	  + "        (LT0, R4) -> TRUE;\n"
	  + "        (LT0, GT4) -> TRUE;\n"
	  + "        (R0, LT0) -> FALSE;\n"
	  + "        (R0, R0) -> TRUE;\n"
	  + "        (R0, R1) -> TRUE;\n"
	  + "        (R0, R2) -> TRUE;\n"
	  + "        (R0, R3) -> TRUE;\n"
	  + "        (R0, R4) -> TRUE;\n"
	  + "        (R0, GT4) -> TRUE;\n"
	  + "        (R1, LT0) -> FALSE;\n"
	  + "        (R1, R0) -> FALSE;\n"
	  + "        (R1, R1) -> TRUE;\n"
	  + "        (R1, R2) -> TRUE;\n"
	  + "        (R1, R3) -> TRUE;\n"
	  + "        (R1, R4) -> TRUE;\n"
	  + "        (R1, GT4) -> TRUE;\n"
	  + "        (R2, LT0) -> FALSE;\n"
	  + "        (R2, R0) -> FALSE;\n"
	  + "        (R2, R1) -> FALSE;\n"
	  + "        (R2, R2) -> TRUE;\n"
	  + "        (R2, R3) -> TRUE;\n"
	  + "        (R2, R4) -> TRUE;\n"
	  + "        (R2, GT4) -> TRUE;\n"
	  + "        (R3, LT0) -> FALSE;\n"
	  + "        (R3, R0) -> FALSE;\n"
	  + "        (R3, R1) -> FALSE;\n"
	  + "        (R3, R2) -> FALSE;\n"
	  + "        (R3, R3) -> TRUE;\n"
	  + "        (R3, R4) -> TRUE;\n"
	  + "        (R3, GT4) -> TRUE;\n"
	  + "        (R4, LT0) -> FALSE;\n"
	  + "        (R4, R0) -> FALSE;\n"
	  + "        (R4, R1) -> FALSE;\n"
	  + "        (R4, R2) -> FALSE;\n"
	  + "        (R4, R3) -> FALSE;\n"
	  + "        (R4, R4) -> TRUE;\n"
	  + "        (R4, GT4) -> TRUE;\n"
	  + "        (GT4, LT0) -> FALSE;\n"
	  + "        (GT4, R0) -> FALSE;\n"
	  + "        (GT4, R1) -> FALSE;\n"
	  + "        (GT4, R2) -> FALSE;\n"
	  + "        (GT4, R3) -> FALSE;\n"
	  + "        (GT4, R4) -> FALSE;\n"
	  + "        (GT4, GT4) -> {TRUE, FALSE};\n"
	  + "      end\n"
	  + "    test > gt \n"
	  + "      begin\n"
	  + "        (LT0, LT0) -> {TRUE, FALSE};\n"
	  + "        (LT0, R0) -> FALSE;\n"
	  + "        (LT0, R1) -> FALSE;\n"
	  + "        (LT0, R2) -> FALSE;\n"
	  + "        (LT0, R3) -> FALSE;\n"
	  + "        (LT0, R4) -> FALSE;\n"
	  + "        (LT0, GT4) -> FALSE;\n"
	  + "        (R0, LT0) -> TRUE;\n"
	  + "        (R0, R0) -> FALSE;\n"
	  + "        (R0, R1) -> FALSE;\n"
	  + "        (R0, R2) -> FALSE;\n"
	  + "        (R0, R3) -> FALSE;\n"
	  + "        (R0, R4) -> FALSE;\n"
	  + "        (R0, GT4) -> FALSE;\n"
	  + "        (R1, LT0) -> TRUE;\n"
	  + "        (R1, R0) -> TRUE;\n"
	  + "        (R1, R1) -> FALSE;\n"
	  + "        (R1, R2) -> FALSE;\n"
	  + "        (R1, R3) -> FALSE;\n"
	  + "        (R1, R4) -> FALSE;\n"
	  + "        (R1, GT4) -> FALSE;\n"
	  + "        (R2, LT0) -> TRUE;\n"
	  + "        (R2, R0) -> TRUE;\n"
	  + "        (R2, R1) -> TRUE;\n"
	  + "        (R2, R2) -> FALSE;\n"
	  + "        (R2, R3) -> FALSE;\n"
	  + "        (R2, R4) -> FALSE;\n"
	  + "        (R2, GT4) -> FALSE;\n"
	  + "        (R3, LT0) -> TRUE;\n"
	  + "        (R3, R0) -> TRUE;\n"
	  + "        (R3, R1) -> TRUE;\n"
	  + "        (R3, R2) -> TRUE;\n"
	  + "        (R3, R3) -> FALSE;\n"
	  + "        (R3, R4) -> FALSE;\n"
	  + "        (R3, GT4) -> FALSE;\n"
	  + "        (R4, LT0) -> TRUE;\n"
	  + "        (R4, R0) -> TRUE;\n"
	  + "        (R4, R1) -> TRUE;\n"
	  + "        (R4, R2) -> TRUE;\n"
	  + "        (R4, R3) -> TRUE;\n"
	  + "        (R4, R4) -> FALSE;\n"
	  + "        (R4, GT4) -> FALSE;\n"
	  + "        (GT4, LT0) -> TRUE;\n"
	  + "        (GT4, R0) -> TRUE;\n"
	  + "        (GT4, R1) -> TRUE;\n"
	  + "        (GT4, R2) -> TRUE;\n"
	  + "        (GT4, R3) -> TRUE;\n"
	  + "        (GT4, R4) -> TRUE;\n"
	  + "        (GT4, GT4) -> {TRUE, FALSE};\n"
	  + "      end\n"
	  + "    test >= ge \n"
	  + "      begin\n"
	  + "        (LT0, LT0) -> {TRUE, FALSE};\n"
	  + "        (LT0, R0) -> FALSE;\n"
	  + "        (LT0, R1) -> FALSE;\n"
	  + "        (LT0, R2) -> FALSE;\n"
	  + "        (LT0, R3) -> FALSE;\n"
	  + "        (LT0, R4) -> FALSE;\n"
	  + "        (LT0, GT4) -> FALSE;\n"
	  + "        (R0, LT0) -> TRUE;\n"
	  + "        (R0, R0) -> TRUE;\n"
	  + "        (R0, R1) -> FALSE;\n"
	  + "        (R0, R2) -> FALSE;\n"
	  + "        (R0, R3) -> FALSE;\n"
	  + "        (R0, R4) -> FALSE;\n"
	  + "        (R0, GT4) -> FALSE;\n"
	  + "        (R1, LT0) -> TRUE;\n"
	  + "        (R1, R0) -> TRUE;\n"
	  + "        (R1, R1) -> TRUE;\n"
	  + "        (R1, R2) -> FALSE;\n"
	  + "        (R1, R3) -> FALSE;\n"
	  + "        (R1, R4) -> FALSE;\n"
	  + "        (R1, GT4) -> FALSE;\n"
	  + "        (R2, LT0) -> TRUE;\n"
	  + "        (R2, R0) -> TRUE;\n"
	  + "        (R2, R1) -> TRUE;\n"
	  + "        (R2, R2) -> TRUE;\n"
	  + "        (R2, R3) -> FALSE;\n"
	  + "        (R2, R4) -> FALSE;\n"
	  + "        (R2, GT4) -> FALSE;\n"
	  + "        (R3, LT0) -> TRUE;\n"
	  + "        (R3, R0) -> TRUE;\n"
	  + "        (R3, R1) -> TRUE;\n"
	  + "        (R3, R2) -> TRUE;\n"
	  + "        (R3, R3) -> TRUE;\n"
	  + "        (R3, R4) -> FALSE;\n"
	  + "        (R3, GT4) -> FALSE;\n"
	  + "        (R4, LT0) -> TRUE;\n"
	  + "        (R4, R0) -> TRUE;\n"
	  + "        (R4, R1) -> TRUE;\n"
	  + "        (R4, R2) -> TRUE;\n"
	  + "        (R4, R3) -> TRUE;\n"
	  + "        (R4, R4) -> TRUE;\n"
	  + "        (R4, GT4) -> FALSE;\n"
	  + "        (GT4, LT0) -> TRUE;\n"
	  + "        (GT4, R0) -> TRUE;\n"
	  + "        (GT4, R1) -> TRUE;\n"
	  + "        (GT4, R2) -> TRUE;\n"
	  + "        (GT4, R3) -> TRUE;\n"
	  + "        (GT4, R4) -> TRUE;\n"
	  + "        (GT4, GT4) -> {TRUE, FALSE};\n"
	  + "      end\n"
	  + "  end\n"
	;
  }  
  public static String getName() {
	return "Range04";
  }  
  public static int getNumOfTokens() {
	return 7;
  }  
  public static String getToken(int value) {
	switch(value) {
	  case R0: return "Range04.R0";
	  case LT0: return "Range04.LT0";
	  case R1: return "Range04.R1";
	  case R2: return "Range04.R2";
	  case R3: return "Range04.R3";
	  case R4: return "Range04.R4";
	  case GT4: return "Range04.GT4";
	}
	return "Range04.???";
  }  
  public static boolean gt(int left$, int right$) {
	if (left$ == LT0 && right$ == LT0) return Abstraction.choose();
	if (left$ == LT0 && right$ == R0) return false;
	if (left$ == LT0 && right$ == R1) return false;
	if (left$ == LT0 && right$ == R2) return false;
	if (left$ == LT0 && right$ == R3) return false;
	if (left$ == LT0 && right$ == R4) return false;
	if (left$ == LT0 && right$ == GT4) return false;
	if (left$ == R0 && right$ == LT0) return true;
	if (left$ == R0 && right$ == R0) return false;
	if (left$ == R0 && right$ == R1) return false;
	if (left$ == R0 && right$ == R2) return false;
	if (left$ == R0 && right$ == R3) return false;
	if (left$ == R0 && right$ == R4) return false;
	if (left$ == R0 && right$ == GT4) return false;
	if (left$ == R1 && right$ == LT0) return true;
	if (left$ == R1 && right$ == R0) return true;
	if (left$ == R1 && right$ == R1) return false;
	if (left$ == R1 && right$ == R2) return false;
	if (left$ == R1 && right$ == R3) return false;
	if (left$ == R1 && right$ == R4) return false;
	if (left$ == R1 && right$ == GT4) return false;
	if (left$ == R2 && right$ == LT0) return true;
	if (left$ == R2 && right$ == R0) return true;
	if (left$ == R2 && right$ == R1) return true;
	if (left$ == R2 && right$ == R2) return false;
	if (left$ == R2 && right$ == R3) return false;
	if (left$ == R2 && right$ == R4) return false;
	if (left$ == R2 && right$ == GT4) return false;
	if (left$ == R3 && right$ == LT0) return true;
	if (left$ == R3 && right$ == R0) return true;
	if (left$ == R3 && right$ == R1) return true;
	if (left$ == R3 && right$ == R2) return true;
	if (left$ == R3 && right$ == R3) return false;
	if (left$ == R3 && right$ == R4) return false;
	if (left$ == R3 && right$ == GT4) return false;
	if (left$ == R4 && right$ == LT0) return true;
	if (left$ == R4 && right$ == R0) return true;
	if (left$ == R4 && right$ == R1) return true;
	if (left$ == R4 && right$ == R2) return true;
	if (left$ == R4 && right$ == R3) return true;
	if (left$ == R4 && right$ == R4) return false;
	if (left$ == R4 && right$ == GT4) return false;
	if (left$ == GT4 && right$ == LT0) return true;
	if (left$ == GT4 && right$ == R0) return true;
	if (left$ == GT4 && right$ == R1) return true;
	if (left$ == GT4 && right$ == R2) return true;
	if (left$ == GT4 && right$ == R3) return true;
	if (left$ == GT4 && right$ == R4) return true;
	if (left$ == GT4 && right$ == GT4) return Abstraction.choose();
	throw new RuntimeException("Range04.gt(" + left$ + ", " + right$ + ") is undefined");
  }  
  private static byte gtNoChoose(int left, int right) {
	byte result = -1;
	switch (left) {
	  case 0:
		switch (right) {
		  case 0:
			result = 0;
			break;
		  case 1:
			result = 1;
			break;
		  case 2:
			result = 0;
			break;
		  case 3:
			result = 0;
			break;
		  case 4:
			result = 0;
			break;
		  case 5:
			result = 0;
			break;
		  case 6:
			result = 0;
			break;
		}
		break;
	  case 1:
		switch (right) {
		  case 0:
			result = 0;
			break;
		  case 1:
			result = 2;
			break;
		  case 2:
			result = 0;
			break;
		  case 3:
			result = 0;
			break;
		  case 4:
			result = 0;
			break;
		  case 5:
			result = 0;
			break;
		  case 6:
			result = 0;
			break;
		}
		break;
	  case 2:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 1;
			break;
		  case 2:
			result = 0;
			break;
		  case 3:
			result = 0;
			break;
		  case 4:
			result = 0;
			break;
		  case 5:
			result = 0;
			break;
		  case 6:
			result = 0;
			break;
		}
		break;
	  case 3:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 1;
			break;
		  case 2:
			result = 1;
			break;
		  case 3:
			result = 0;
			break;
		  case 4:
			result = 0;
			break;
		  case 5:
			result = 0;
			break;
		  case 6:
			result = 0;
			break;
		}
		break;
	  case 4:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 1;
			break;
		  case 2:
			result = 1;
			break;
		  case 3:
			result = 1;
			break;
		  case 4:
			result = 0;
			break;
		  case 5:
			result = 0;
			break;
		  case 6:
			result = 0;
			break;
		}
		break;
	  case 5:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 1;
			break;
		  case 2:
			result = 1;
			break;
		  case 3:
			result = 1;
			break;
		  case 4:
			result = 1;
			break;
		  case 5:
			result = 0;
			break;
		  case 6:
			result = 0;
			break;
		}
		break;
	  case 6:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 1;
			break;
		  case 2:
			result = 1;
			break;
		  case 3:
			result = 1;
			break;
		  case 4:
			result = 1;
			break;
		  case 5:
			result = 1;
			break;
		  case 6:
			result = 2;
			break;
		}
		break;
	}
	if (result == -1) throw new RuntimeException("Range04.gtNoChoose(" + left + ", " + right + ") is undefined");
	return result;
  }  
  public static byte gtSet(int leftTokens, int rightTokens) {
	byte result = -1;
	for (int left = 0; (1 << left) <= leftTokens; left++) {
	  if ((leftTokens & (1 << left)) == 0) continue;
	  for (int right = 0; (1 << right) <= rightTokens; right++) {
		if ((rightTokens & (1 << right)) != 0) {
		  if (result == -1) result = gtNoChoose(left, right);
		  else result = Abstraction.meetTest(result, gtNoChoose(left, right));
		}
	  }
	}
	return result;
  }  
  public static boolean isOne2One(int value) {
	switch(value) {
	  case R4: return true;
	  case R3: return true;
	  case R2: return true;
	  case R1: return true;
	  case R0: return true;
	}
	return false;
  }  
  public static boolean le(int left$, int right$) {
	if (left$ == LT0 && right$ == LT0) return Abstraction.choose();
	if (left$ == LT0 && right$ == R0) return true;
	if (left$ == LT0 && right$ == R1) return true;
	if (left$ == LT0 && right$ == R2) return true;
	if (left$ == LT0 && right$ == R3) return true;
	if (left$ == LT0 && right$ == R4) return true;
	if (left$ == LT0 && right$ == GT4) return true;
	if (left$ == R0 && right$ == LT0) return false;
	if (left$ == R0 && right$ == R0) return true;
	if (left$ == R0 && right$ == R1) return true;
	if (left$ == R0 && right$ == R2) return true;
	if (left$ == R0 && right$ == R3) return true;
	if (left$ == R0 && right$ == R4) return true;
	if (left$ == R0 && right$ == GT4) return true;
	if (left$ == R1 && right$ == LT0) return false;
	if (left$ == R1 && right$ == R0) return false;
	if (left$ == R1 && right$ == R1) return true;
	if (left$ == R1 && right$ == R2) return true;
	if (left$ == R1 && right$ == R3) return true;
	if (left$ == R1 && right$ == R4) return true;
	if (left$ == R1 && right$ == GT4) return true;
	if (left$ == R2 && right$ == LT0) return false;
	if (left$ == R2 && right$ == R0) return false;
	if (left$ == R2 && right$ == R1) return false;
	if (left$ == R2 && right$ == R2) return true;
	if (left$ == R2 && right$ == R3) return true;
	if (left$ == R2 && right$ == R4) return true;
	if (left$ == R2 && right$ == GT4) return true;
	if (left$ == R3 && right$ == LT0) return false;
	if (left$ == R3 && right$ == R0) return false;
	if (left$ == R3 && right$ == R1) return false;
	if (left$ == R3 && right$ == R2) return false;
	if (left$ == R3 && right$ == R3) return true;
	if (left$ == R3 && right$ == R4) return true;
	if (left$ == R3 && right$ == GT4) return true;
	if (left$ == R4 && right$ == LT0) return false;
	if (left$ == R4 && right$ == R0) return false;
	if (left$ == R4 && right$ == R1) return false;
	if (left$ == R4 && right$ == R2) return false;
	if (left$ == R4 && right$ == R3) return false;
	if (left$ == R4 && right$ == R4) return true;
	if (left$ == R4 && right$ == GT4) return true;
	if (left$ == GT4 && right$ == LT0) return false;
	if (left$ == GT4 && right$ == R0) return false;
	if (left$ == GT4 && right$ == R1) return false;
	if (left$ == GT4 && right$ == R2) return false;
	if (left$ == GT4 && right$ == R3) return false;
	if (left$ == GT4 && right$ == R4) return false;
	if (left$ == GT4 && right$ == GT4) return Abstraction.choose();
	throw new RuntimeException("Range04.le(" + left$ + ", " + right$ + ") is undefined");
  }  
  private static byte leNoChoose(int left, int right) {
	byte result = -1;
	switch (left) {
	  case 0:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 0;
			break;
		  case 2:
			result = 1;
			break;
		  case 3:
			result = 1;
			break;
		  case 4:
			result = 1;
			break;
		  case 5:
			result = 1;
			break;
		  case 6:
			result = 1;
			break;
		}
		break;
	  case 1:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 2;
			break;
		  case 2:
			result = 1;
			break;
		  case 3:
			result = 1;
			break;
		  case 4:
			result = 1;
			break;
		  case 5:
			result = 1;
			break;
		  case 6:
			result = 1;
			break;
		}
		break;
	  case 2:
		switch (right) {
		  case 0:
			result = 0;
			break;
		  case 1:
			result = 0;
			break;
		  case 2:
			result = 1;
			break;
		  case 3:
			result = 1;
			break;
		  case 4:
			result = 1;
			break;
		  case 5:
			result = 1;
			break;
		  case 6:
			result = 1;
			break;
		}
		break;
	  case 3:
		switch (right) {
		  case 0:
			result = 0;
			break;
		  case 1:
			result = 0;
			break;
		  case 2:
			result = 0;
			break;
		  case 3:
			result = 1;
			break;
		  case 4:
			result = 1;
			break;
		  case 5:
			result = 1;
			break;
		  case 6:
			result = 1;
			break;
		}
		break;
	  case 4:
		switch (right) {
		  case 0:
			result = 0;
			break;
		  case 1:
			result = 0;
			break;
		  case 2:
			result = 0;
			break;
		  case 3:
			result = 0;
			break;
		  case 4:
			result = 1;
			break;
		  case 5:
			result = 1;
			break;
		  case 6:
			result = 1;
			break;
		}
		break;
	  case 5:
		switch (right) {
		  case 0:
			result = 0;
			break;
		  case 1:
			result = 0;
			break;
		  case 2:
			result = 0;
			break;
		  case 3:
			result = 0;
			break;
		  case 4:
			result = 0;
			break;
		  case 5:
			result = 1;
			break;
		  case 6:
			result = 1;
			break;
		}
		break;
	  case 6:
		switch (right) {
		  case 0:
			result = 0;
			break;
		  case 1:
			result = 0;
			break;
		  case 2:
			result = 0;
			break;
		  case 3:
			result = 0;
			break;
		  case 4:
			result = 0;
			break;
		  case 5:
			result = 0;
			break;
		  case 6:
			result = 2;
			break;
		}
		break;
	}
	if (result == -1) throw new RuntimeException("Range04.leNoChoose(" + left + ", " + right + ") is undefined");
	return result;
  }  
  public static byte leSet(int leftTokens, int rightTokens) {
	byte result = -1;
	for (int left = 0; (1 << left) <= leftTokens; left++) {
	  if ((leftTokens & (1 << left)) == 0) continue;
	  for (int right = 0; (1 << right) <= rightTokens; right++) {
		if ((rightTokens & (1 << right)) != 0) {
		  if (result == -1) result = leNoChoose(left, right);
		  else result = Abstraction.meetTest(result, leNoChoose(left, right));
		}
	  }
	}
	return result;
  }  
  public static boolean lt(int left$, int right$) {
	if (left$ == LT0 && right$ == LT0) return Abstraction.choose();
	if (left$ == LT0 && right$ == R0) return true;
	if (left$ == LT0 && right$ == R1) return true;
	if (left$ == LT0 && right$ == R2) return true;
	if (left$ == LT0 && right$ == R3) return true;
	if (left$ == LT0 && right$ == R4) return true;
	if (left$ == LT0 && right$ == GT4) return true;
	if (left$ == R0 && right$ == LT0) return false;
	if (left$ == R0 && right$ == R0) return false;
	if (left$ == R0 && right$ == R1) return true;
	if (left$ == R0 && right$ == R2) return true;
	if (left$ == R0 && right$ == R3) return true;
	if (left$ == R0 && right$ == R4) return true;
	if (left$ == R0 && right$ == GT4) return true;
	if (left$ == R1 && right$ == LT0) return false;
	if (left$ == R1 && right$ == R0) return false;
	if (left$ == R1 && right$ == R1) return false;
	if (left$ == R1 && right$ == R2) return true;
	if (left$ == R1 && right$ == R3) return true;
	if (left$ == R1 && right$ == R4) return true;
	if (left$ == R1 && right$ == GT4) return true;
	if (left$ == R2 && right$ == LT0) return false;
	if (left$ == R2 && right$ == R0) return false;
	if (left$ == R2 && right$ == R1) return false;
	if (left$ == R2 && right$ == R2) return false;
	if (left$ == R2 && right$ == R3) return true;
	if (left$ == R2 && right$ == R4) return true;
	if (left$ == R2 && right$ == GT4) return true;
	if (left$ == R3 && right$ == LT0) return false;
	if (left$ == R3 && right$ == R0) return false;
	if (left$ == R3 && right$ == R1) return false;
	if (left$ == R3 && right$ == R2) return false;
	if (left$ == R3 && right$ == R3) return false;
	if (left$ == R3 && right$ == R4) return true;
	if (left$ == R3 && right$ == GT4) return true;
	if (left$ == R4 && right$ == LT0) return false;
	if (left$ == R4 && right$ == R0) return false;
	if (left$ == R4 && right$ == R1) return false;
	if (left$ == R4 && right$ == R2) return false;
	if (left$ == R4 && right$ == R3) return false;
	if (left$ == R4 && right$ == R4) return false;
	if (left$ == R4 && right$ == GT4) return true;
	if (left$ == GT4 && right$ == LT0) return false;
	if (left$ == GT4 && right$ == R0) return false;
	if (left$ == GT4 && right$ == R1) return false;
	if (left$ == GT4 && right$ == R2) return false;
	if (left$ == GT4 && right$ == R3) return false;
	if (left$ == GT4 && right$ == R4) return false;
	if (left$ == GT4 && right$ == GT4) return Abstraction.choose();
	throw new RuntimeException("Range04.lt(" + left$ + ", " + right$ + ") is undefined");
  }  
  private static byte ltNoChoose(int left, int right) {
	byte result = -1;
	switch (left) {
	  case 0:
		switch (right) {
		  case 0:
			result = 0;
			break;
		  case 1:
			result = 0;
			break;
		  case 2:
			result = 1;
			break;
		  case 3:
			result = 1;
			break;
		  case 4:
			result = 1;
			break;
		  case 5:
			result = 1;
			break;
		  case 6:
			result = 1;
			break;
		}
		break;
	  case 1:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 2;
			break;
		  case 2:
			result = 1;
			break;
		  case 3:
			result = 1;
			break;
		  case 4:
			result = 1;
			break;
		  case 5:
			result = 1;
			break;
		  case 6:
			result = 1;
			break;
		}
		break;
	  case 2:
		switch (right) {
		  case 0:
			result = 0;
			break;
		  case 1:
			result = 0;
			break;
		  case 2:
			result = 0;
			break;
		  case 3:
			result = 1;
			break;
		  case 4:
			result = 1;
			break;
		  case 5:
			result = 1;
			break;
		  case 6:
			result = 1;
			break;
		}
		break;
	  case 3:
		switch (right) {
		  case 0:
			result = 0;
			break;
		  case 1:
			result = 0;
			break;
		  case 2:
			result = 0;
			break;
		  case 3:
			result = 0;
			break;
		  case 4:
			result = 1;
			break;
		  case 5:
			result = 1;
			break;
		  case 6:
			result = 1;
			break;
		}
		break;
	  case 4:
		switch (right) {
		  case 0:
			result = 0;
			break;
		  case 1:
			result = 0;
			break;
		  case 2:
			result = 0;
			break;
		  case 3:
			result = 0;
			break;
		  case 4:
			result = 0;
			break;
		  case 5:
			result = 1;
			break;
		  case 6:
			result = 1;
			break;
		}
		break;
	  case 5:
		switch (right) {
		  case 0:
			result = 0;
			break;
		  case 1:
			result = 0;
			break;
		  case 2:
			result = 0;
			break;
		  case 3:
			result = 0;
			break;
		  case 4:
			result = 0;
			break;
		  case 5:
			result = 0;
			break;
		  case 6:
			result = 1;
			break;
		}
		break;
	  case 6:
		switch (right) {
		  case 0:
			result = 0;
			break;
		  case 1:
			result = 0;
			break;
		  case 2:
			result = 0;
			break;
		  case 3:
			result = 0;
			break;
		  case 4:
			result = 0;
			break;
		  case 5:
			result = 0;
			break;
		  case 6:
			result = 2;
			break;
		}
		break;
	}
	if (result == -1) throw new RuntimeException("Range04.ltNoChoose(" + left + ", " + right + ") is undefined");
	return result;
  }  
  public static byte ltSet(int leftTokens, int rightTokens) {
	byte result = -1;
	for (int left = 0; (1 << left) <= leftTokens; left++) {
	  if ((leftTokens & (1 << left)) == 0) continue;
	  for (int right = 0; (1 << right) <= rightTokens; right++) {
		if ((rightTokens & (1 << right)) != 0) {
		  if (result == -1) result = ltNoChoose(left, right);
		  else result = Abstraction.meetTest(result, ltNoChoose(left, right));
		}
	  }
	}
	return result;
  }  
  public static int mul(int left$, int right$) {
	if (left$ == LT0 && right$ == LT0) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1));
	if (left$ == LT0 && right$ == R0) return R0;
	if (left$ == LT0 && right$ == R1) return LT0;
	if (left$ == LT0 && right$ == R2) return LT0;
	if (left$ == LT0 && right$ == R3) return LT0;
	if (left$ == LT0 && right$ == R4) return LT0;
	if (left$ == LT0 && right$ == GT4) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << LT0));
	if (left$ == R0 && right$ == LT0) return R0;
	if (left$ == R0 && right$ == R0) return R0;
	if (left$ == R0 && right$ == R1) return R0;
	if (left$ == R0 && right$ == R2) return R0;
	if (left$ == R0 && right$ == R3) return R0;
	if (left$ == R0 && right$ == R4) return R0;
	if (left$ == R0 && right$ == GT4) return R0;
	if (left$ == R1 && right$ == LT0) return LT0;
	if (left$ == R1 && right$ == R0) return R0;
	if (left$ == R1 && right$ == R1) return R1;
	if (left$ == R1 && right$ == R2) return R2;
	if (left$ == R1 && right$ == R3) return R3;
	if (left$ == R1 && right$ == R4) return R4;
	if (left$ == R1 && right$ == GT4) return GT4;
	if (left$ == R2 && right$ == LT0) return LT0;
	if (left$ == R2 && right$ == R0) return R0;
	if (left$ == R2 && right$ == R1) return R2;
	if (left$ == R2 && right$ == R2) return R4;
	if (left$ == R2 && right$ == R3) return GT4;
	if (left$ == R2 && right$ == R4) return GT4;
	if (left$ == R2 && right$ == GT4) return GT4;
	if (left$ == R3 && right$ == LT0) return LT0;
	if (left$ == R3 && right$ == R0) return R0;
	if (left$ == R3 && right$ == R1) return R3;
	if (left$ == R3 && right$ == R2) return GT4;
	if (left$ == R3 && right$ == R3) return GT4;
	if (left$ == R3 && right$ == R4) return GT4;
	if (left$ == R3 && right$ == GT4) return GT4;
	if (left$ == R4 && right$ == LT0) return LT0;
	if (left$ == R4 && right$ == R0) return R0;
	if (left$ == R4 && right$ == R1) return R4;
	if (left$ == R4 && right$ == R2) return GT4;
	if (left$ == R4 && right$ == R3) return GT4;
	if (left$ == R4 && right$ == R4) return GT4;
	if (left$ == R4 && right$ == GT4) return GT4;
	if (left$ == GT4 && right$ == LT0) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << LT0));
	if (left$ == GT4 && right$ == R0) return R0;
	if (left$ == GT4 && right$ == R1) return GT4;
	if (left$ == GT4 && right$ == R2) return GT4;
	if (left$ == GT4 && right$ == R3) return GT4;
	if (left$ == GT4 && right$ == R4) return GT4;
	if (left$ == GT4 && right$ == GT4) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1));
	throw new RuntimeException("Range04.mul(" + left$ + ", " + right$ + ") is undefined");
  }  
  private static int mulNoChoose(int left, int right) {
	int result = 0;
	switch (left) {
	  case 0:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 1;
			break;
		  case 2:
			result = 1;
			break;
		  case 3:
			result = 1;
			break;
		  case 4:
			result = 1;
			break;
		  case 5:
			result = 1;
			break;
		  case 6:
			result = 1;
			break;
		}
		break;
	  case 1:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 124;
			break;
		  case 2:
			result = 2;
			break;
		  case 3:
			result = 2;
			break;
		  case 4:
			result = 2;
			break;
		  case 5:
			result = 2;
			break;
		  case 6:
			result = 126;
			break;
		}
		break;
	  case 2:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 2;
			break;
		  case 2:
			result = 4;
			break;
		  case 3:
			result = 8;
			break;
		  case 4:
			result = 16;
			break;
		  case 5:
			result = 32;
			break;
		  case 6:
			result = 64;
			break;
		}
		break;
	  case 3:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 2;
			break;
		  case 2:
			result = 8;
			break;
		  case 3:
			result = 32;
			break;
		  case 4:
			result = 64;
			break;
		  case 5:
			result = 64;
			break;
		  case 6:
			result = 64;
			break;
		}
		break;
	  case 4:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 2;
			break;
		  case 2:
			result = 16;
			break;
		  case 3:
			result = 64;
			break;
		  case 4:
			result = 64;
			break;
		  case 5:
			result = 64;
			break;
		  case 6:
			result = 64;
			break;
		}
		break;
	  case 5:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 2;
			break;
		  case 2:
			result = 32;
			break;
		  case 3:
			result = 64;
			break;
		  case 4:
			result = 64;
			break;
		  case 5:
			result = 64;
			break;
		  case 6:
			result = 64;
			break;
		}
		break;
	  case 6:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 126;
			break;
		  case 2:
			result = 64;
			break;
		  case 3:
			result = 64;
			break;
		  case 4:
			result = 64;
			break;
		  case 5:
			result = 64;
			break;
		  case 6:
			result = 124;
			break;
		}
		break;
	}
	if (result == 0) throw new RuntimeException("Range04.mulNoChoose(" + left + ", " + right + ") is undefined");
	return result;
  }  
  public static int mulSet(int leftTokens, int rightTokens) {
	int result = -1;
	for (int left = 0; (1 << left) <= leftTokens; left++) {
	  if ((leftTokens & (1 << left)) == 0) continue;
	  for (int right = 0; (1 << right) <= rightTokens; right++) {
		if ((rightTokens & (1 << right)) != 0) {
		  if (result == -1) result = mulNoChoose(left, right);
		  else result = Abstraction.meetArith(result, mulNoChoose(left, right));
		}
	  }
	}
	return result;
  }  
  public static boolean ne(int left$, int right$) {
	if (left$ == LT0 && right$ == LT0) return Abstraction.choose();
	if (left$ == LT0 && right$ == R0) return true;
	if (left$ == LT0 && right$ == R1) return true;
	if (left$ == LT0 && right$ == R2) return true;
	if (left$ == LT0 && right$ == R3) return true;
	if (left$ == LT0 && right$ == R4) return true;
	if (left$ == LT0 && right$ == GT4) return true;
	if (left$ == R0 && right$ == LT0) return true;
	if (left$ == R0 && right$ == R0) return false;
	if (left$ == R0 && right$ == R1) return true;
	if (left$ == R0 && right$ == R2) return true;
	if (left$ == R0 && right$ == R3) return true;
	if (left$ == R0 && right$ == R4) return true;
	if (left$ == R0 && right$ == GT4) return true;
	if (left$ == R1 && right$ == LT0) return true;
	if (left$ == R1 && right$ == R0) return true;
	if (left$ == R1 && right$ == R1) return false;
	if (left$ == R1 && right$ == R2) return true;
	if (left$ == R1 && right$ == R3) return true;
	if (left$ == R1 && right$ == R4) return true;
	if (left$ == R1 && right$ == GT4) return true;
	if (left$ == R2 && right$ == LT0) return true;
	if (left$ == R2 && right$ == R0) return true;
	if (left$ == R2 && right$ == R1) return true;
	if (left$ == R2 && right$ == R2) return false;
	if (left$ == R2 && right$ == R3) return true;
	if (left$ == R2 && right$ == R4) return true;
	if (left$ == R2 && right$ == GT4) return true;
	if (left$ == R3 && right$ == LT0) return true;
	if (left$ == R3 && right$ == R0) return true;
	if (left$ == R3 && right$ == R1) return true;
	if (left$ == R3 && right$ == R2) return true;
	if (left$ == R3 && right$ == R3) return false;
	if (left$ == R3 && right$ == R4) return true;
	if (left$ == R3 && right$ == GT4) return true;
	if (left$ == R4 && right$ == LT0) return true;
	if (left$ == R4 && right$ == R0) return true;
	if (left$ == R4 && right$ == R1) return true;
	if (left$ == R4 && right$ == R2) return true;
	if (left$ == R4 && right$ == R3) return true;
	if (left$ == R4 && right$ == R4) return false;
	if (left$ == R4 && right$ == GT4) return true;
	if (left$ == GT4 && right$ == LT0) return true;
	if (left$ == GT4 && right$ == R0) return true;
	if (left$ == GT4 && right$ == R1) return true;
	if (left$ == GT4 && right$ == R2) return true;
	if (left$ == GT4 && right$ == R3) return true;
	if (left$ == GT4 && right$ == R4) return true;
	if (left$ == GT4 && right$ == GT4) return Abstraction.choose();
	throw new RuntimeException("Range04.ne(" + left$ + ", " + right$ + ") is undefined");
  }  
  private static byte neNoChoose(int left, int right) {
	byte result = -1;
	switch (left) {
	  case 0:
		switch (right) {
		  case 0:
			result = 0;
			break;
		  case 1:
			result = 1;
			break;
		  case 2:
			result = 1;
			break;
		  case 3:
			result = 1;
			break;
		  case 4:
			result = 1;
			break;
		  case 5:
			result = 1;
			break;
		  case 6:
			result = 1;
			break;
		}
		break;
	  case 1:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 2;
			break;
		  case 2:
			result = 1;
			break;
		  case 3:
			result = 1;
			break;
		  case 4:
			result = 1;
			break;
		  case 5:
			result = 1;
			break;
		  case 6:
			result = 1;
			break;
		}
		break;
	  case 2:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 1;
			break;
		  case 2:
			result = 0;
			break;
		  case 3:
			result = 1;
			break;
		  case 4:
			result = 1;
			break;
		  case 5:
			result = 1;
			break;
		  case 6:
			result = 1;
			break;
		}
		break;
	  case 3:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 1;
			break;
		  case 2:
			result = 1;
			break;
		  case 3:
			result = 0;
			break;
		  case 4:
			result = 1;
			break;
		  case 5:
			result = 1;
			break;
		  case 6:
			result = 1;
			break;
		}
		break;
	  case 4:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 1;
			break;
		  case 2:
			result = 1;
			break;
		  case 3:
			result = 1;
			break;
		  case 4:
			result = 0;
			break;
		  case 5:
			result = 1;
			break;
		  case 6:
			result = 1;
			break;
		}
		break;
	  case 5:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 1;
			break;
		  case 2:
			result = 1;
			break;
		  case 3:
			result = 1;
			break;
		  case 4:
			result = 1;
			break;
		  case 5:
			result = 0;
			break;
		  case 6:
			result = 1;
			break;
		}
		break;
	  case 6:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 1;
			break;
		  case 2:
			result = 1;
			break;
		  case 3:
			result = 1;
			break;
		  case 4:
			result = 1;
			break;
		  case 5:
			result = 1;
			break;
		  case 6:
			result = 2;
			break;
		}
		break;
	}
	if (result == -1) throw new RuntimeException("Range04.neNoChoose(" + left + ", " + right + ") is undefined");
	return result;
  }  
  public static byte neSet(int leftTokens, int rightTokens) {
	byte result = -1;
	for (int left = 0; (1 << left) <= leftTokens; left++) {
	  if ((leftTokens & (1 << left)) == 0) continue;
	  for (int right = 0; (1 << right) <= rightTokens; right++) {
		if ((rightTokens & (1 << right)) != 0) {
		  if (result == -1) result = neNoChoose(left, right);
		  else result = Abstraction.meetTest(result, neNoChoose(left, right));
		}
	  }
	}
	return result;
  }  
  public static int rem(int left$, int right$) {
	if (left$ == LT0 && right$ == LT0) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == LT0 && right$ == R0) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == LT0 && right$ == R1) return R0;
	if (left$ == LT0 && right$ == R2) return Abstraction.choose((1 << R1) | (1 << R0));
	if (left$ == LT0 && right$ == R3) return Abstraction.choose((1 << R2) | (1 << R1) | (1 << R0));
	if (left$ == LT0 && right$ == R4) return Abstraction.choose((1 << R3) | (1 << R2) | (1 << R1) | (1 << R0));
	if (left$ == LT0 && right$ == GT4) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == R0 && right$ == LT0) return R0;
	if (left$ == R0 && right$ == R0) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == R0 && right$ == R1) return R0;
	if (left$ == R0 && right$ == R2) return R0;
	if (left$ == R0 && right$ == R3) return R0;
	if (left$ == R0 && right$ == R4) return R0;
	if (left$ == R0 && right$ == GT4) return R0;
	if (left$ == R1 && right$ == LT0) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == R1 && right$ == R0) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == R1 && right$ == R1) return R0;
	if (left$ == R1 && right$ == R2) return R1;
	if (left$ == R1 && right$ == R3) return R1;
	if (left$ == R1 && right$ == R4) return R1;
	if (left$ == R1 && right$ == GT4) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == R2 && right$ == LT0) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == R2 && right$ == R0) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == R2 && right$ == R1) return R0;
	if (left$ == R2 && right$ == R2) return R0;
	if (left$ == R2 && right$ == R3) return R2;
	if (left$ == R2 && right$ == R4) return R2;
	if (left$ == R2 && right$ == GT4) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == R3 && right$ == LT0) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == R3 && right$ == R0) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == R3 && right$ == R1) return R0;
	if (left$ == R3 && right$ == R2) return R1;
	if (left$ == R3 && right$ == R3) return R0;
	if (left$ == R3 && right$ == R4) return R3;
	if (left$ == R3 && right$ == GT4) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == R4 && right$ == LT0) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == R4 && right$ == R0) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == R4 && right$ == R1) return R0;
	if (left$ == R4 && right$ == R2) return R0;
	if (left$ == R4 && right$ == R3) return R1;
	if (left$ == R4 && right$ == R4) return R0;
	if (left$ == R4 && right$ == GT4) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == GT4 && right$ == LT0) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == GT4 && right$ == R0) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == GT4 && right$ == R1) return R0;
	if (left$ == GT4 && right$ == R2) return Abstraction.choose((1 << R1) | (1 << R0));
	if (left$ == GT4 && right$ == R3) return Abstraction.choose((1 << R2) | (1 << R1) | (1 << R0));
	if (left$ == GT4 && right$ == R4) return Abstraction.choose((1 << R3) | (1 << R2) | (1 << R1) | (1 << R0));
	if (left$ == GT4 && right$ == GT4) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	throw new RuntimeException("Range04.rem(" + left$ + ", " + right$ + ") is undefined");
  }  
  private static int remNoChoose(int left, int right) {
	int result = 0;
	switch (left) {
	  case 0:
		switch (right) {
		  case 0:
			result = 127;
			break;
		  case 1:
			result = 1;
			break;
		  case 2:
			result = 1;
			break;
		  case 3:
			result = 1;
			break;
		  case 4:
			result = 1;
			break;
		  case 5:
			result = 1;
			break;
		  case 6:
			result = 1;
			break;
		}
		break;
	  case 1:
		switch (right) {
		  case 0:
			result = 127;
			break;
		  case 1:
			result = 127;
			break;
		  case 2:
			result = 1;
			break;
		  case 3:
			result = 5;
			break;
		  case 4:
			result = 13;
			break;
		  case 5:
			result = 29;
			break;
		  case 6:
			result = 127;
			break;
		}
		break;
	  case 2:
		switch (right) {
		  case 0:
			result = 127;
			break;
		  case 1:
			result = 127;
			break;
		  case 2:
			result = 1;
			break;
		  case 3:
			result = 4;
			break;
		  case 4:
			result = 4;
			break;
		  case 5:
			result = 4;
			break;
		  case 6:
			result = 127;
			break;
		}
		break;
	  case 3:
		switch (right) {
		  case 0:
			result = 127;
			break;
		  case 1:
			result = 127;
			break;
		  case 2:
			result = 1;
			break;
		  case 3:
			result = 1;
			break;
		  case 4:
			result = 8;
			break;
		  case 5:
			result = 8;
			break;
		  case 6:
			result = 127;
			break;
		}
		break;
	  case 4:
		switch (right) {
		  case 0:
			result = 127;
			break;
		  case 1:
			result = 127;
			break;
		  case 2:
			result = 1;
			break;
		  case 3:
			result = 4;
			break;
		  case 4:
			result = 1;
			break;
		  case 5:
			result = 16;
			break;
		  case 6:
			result = 127;
			break;
		}
		break;
	  case 5:
		switch (right) {
		  case 0:
			result = 127;
			break;
		  case 1:
			result = 127;
			break;
		  case 2:
			result = 1;
			break;
		  case 3:
			result = 1;
			break;
		  case 4:
			result = 4;
			break;
		  case 5:
			result = 1;
			break;
		  case 6:
			result = 127;
			break;
		}
		break;
	  case 6:
		switch (right) {
		  case 0:
			result = 127;
			break;
		  case 1:
			result = 127;
			break;
		  case 2:
			result = 1;
			break;
		  case 3:
			result = 5;
			break;
		  case 4:
			result = 13;
			break;
		  case 5:
			result = 29;
			break;
		  case 6:
			result = 127;
			break;
		}
		break;
	}
	if (result == 0) throw new RuntimeException("Range04.remNoChoose(" + left + ", " + right + ") is undefined");
	return result;
  }  
  public static int remSet(int leftTokens, int rightTokens) {
	int result = -1;
	for (int left = 0; (1 << left) <= leftTokens; left++) {
	  if ((leftTokens & (1 << left)) == 0) continue;
	  for (int right = 0; (1 << right) <= rightTokens; right++) {
		if ((rightTokens & (1 << right)) != 0) {
		  if (result == -1) result = remNoChoose(left, right);
		  else result = Abstraction.meetArith(result, remNoChoose(left, right));
		}
	  }
	}
	return result;
  }  
  public static int sub(int left$, int right$) {
	if (left$ == LT0 && right$ == LT0) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	if (left$ == LT0 && right$ == R0) return LT0;
	if (left$ == LT0 && right$ == R1) return LT0;
	if (left$ == LT0 && right$ == R2) return LT0;
	if (left$ == LT0 && right$ == R3) return LT0;
	if (left$ == LT0 && right$ == R4) return LT0;
	if (left$ == LT0 && right$ == GT4) return LT0;
	if (left$ == R0 && right$ == LT0) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1));
	if (left$ == R0 && right$ == R0) return R0;
	if (left$ == R0 && right$ == R1) return LT0;
	if (left$ == R0 && right$ == R2) return LT0;
	if (left$ == R0 && right$ == R3) return LT0;
	if (left$ == R0 && right$ == R4) return LT0;
	if (left$ == R0 && right$ == GT4) return LT0;
	if (left$ == R1 && right$ == LT0) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2));
	if (left$ == R1 && right$ == R0) return R1;
	if (left$ == R1 && right$ == R1) return R0;
	if (left$ == R1 && right$ == R2) return LT0;
	if (left$ == R1 && right$ == R3) return LT0;
	if (left$ == R1 && right$ == R4) return LT0;
	if (left$ == R1 && right$ == GT4) return LT0;
	if (left$ == R2 && right$ == LT0) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3));
	if (left$ == R2 && right$ == R0) return R2;
	if (left$ == R2 && right$ == R1) return R1;
	if (left$ == R2 && right$ == R2) return R0;
	if (left$ == R2 && right$ == R3) return LT0;
	if (left$ == R2 && right$ == R4) return LT0;
	if (left$ == R2 && right$ == GT4) return LT0;
	if (left$ == R3 && right$ == LT0) return Abstraction.choose((1 << GT4) | (1 << R4));
	if (left$ == R3 && right$ == R0) return R3;
	if (left$ == R3 && right$ == R1) return R2;
	if (left$ == R3 && right$ == R2) return R1;
	if (left$ == R3 && right$ == R3) return R0;
	if (left$ == R3 && right$ == R4) return LT0;
	if (left$ == R3 && right$ == GT4) return LT0;
	if (left$ == R4 && right$ == LT0) return GT4;
	if (left$ == R4 && right$ == R0) return R4;
	if (left$ == R4 && right$ == R1) return R3;
	if (left$ == R4 && right$ == R2) return R2;
	if (left$ == R4 && right$ == R3) return R1;
	if (left$ == R4 && right$ == R4) return R0;
	if (left$ == R4 && right$ == GT4) return LT0;
	if (left$ == GT4 && right$ == LT0) return GT4;
	if (left$ == GT4 && right$ == R0) return GT4;
	if (left$ == GT4 && right$ == R1) return Abstraction.choose((1 << GT4) | (1 << R4));
	if (left$ == GT4 && right$ == R2) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3));
	if (left$ == GT4 && right$ == R3) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2));
	if (left$ == GT4 && right$ == R4) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1));
	if (left$ == GT4 && right$ == GT4) return Abstraction.choose((1 << GT4) | (1 << R4) | (1 << R3) | (1 << R2) | (1 << R1) | (1 << R0) | (1 << LT0));
	throw new RuntimeException("Range04.sub(" + left$ + ", " + right$ + ") is undefined");
  }  
  private static int subNoChoose(int left, int right) {
	int result = 0;
	switch (left) {
	  case 0:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 124;
			break;
		  case 2:
			result = 2;
			break;
		  case 3:
			result = 2;
			break;
		  case 4:
			result = 2;
			break;
		  case 5:
			result = 2;
			break;
		  case 6:
			result = 2;
			break;
		}
		break;
	  case 1:
		switch (right) {
		  case 0:
			result = 2;
			break;
		  case 1:
			result = 127;
			break;
		  case 2:
			result = 2;
			break;
		  case 3:
			result = 2;
			break;
		  case 4:
			result = 2;
			break;
		  case 5:
			result = 2;
			break;
		  case 6:
			result = 2;
			break;
		}
		break;
	  case 2:
		switch (right) {
		  case 0:
			result = 4;
			break;
		  case 1:
			result = 120;
			break;
		  case 2:
			result = 1;
			break;
		  case 3:
			result = 2;
			break;
		  case 4:
			result = 2;
			break;
		  case 5:
			result = 2;
			break;
		  case 6:
			result = 2;
			break;
		}
		break;
	  case 3:
		switch (right) {
		  case 0:
			result = 8;
			break;
		  case 1:
			result = 112;
			break;
		  case 2:
			result = 4;
			break;
		  case 3:
			result = 1;
			break;
		  case 4:
			result = 2;
			break;
		  case 5:
			result = 2;
			break;
		  case 6:
			result = 2;
			break;
		}
		break;
	  case 4:
		switch (right) {
		  case 0:
			result = 16;
			break;
		  case 1:
			result = 96;
			break;
		  case 2:
			result = 8;
			break;
		  case 3:
			result = 4;
			break;
		  case 4:
			result = 1;
			break;
		  case 5:
			result = 2;
			break;
		  case 6:
			result = 2;
			break;
		}
		break;
	  case 5:
		switch (right) {
		  case 0:
			result = 32;
			break;
		  case 1:
			result = 64;
			break;
		  case 2:
			result = 16;
			break;
		  case 3:
			result = 8;
			break;
		  case 4:
			result = 4;
			break;
		  case 5:
			result = 1;
			break;
		  case 6:
			result = 2;
			break;
		}
		break;
	  case 6:
		switch (right) {
		  case 0:
			result = 64;
			break;
		  case 1:
			result = 64;
			break;
		  case 2:
			result = 96;
			break;
		  case 3:
			result = 112;
			break;
		  case 4:
			result = 120;
			break;
		  case 5:
			result = 124;
			break;
		  case 6:
			result = 127;
			break;
		}
		break;
	}
	if (result == 0) throw new RuntimeException("Range04.subNoChoose(" + left + ", " + right + ") is undefined");
	return result;
  }  
  public static int subSet(int leftTokens, int rightTokens) {
	int result = -1;
	for (int left = 0; (1 << left) <= leftTokens; left++) {
	  if ((leftTokens & (1 << left)) == 0) continue;
	  for (int right = 0; (1 << right) <= rightTokens; right++) {
		if ((rightTokens & (1 << right)) != 0) {
		  if (result == -1) result = subNoChoose(left, right);
		  else result = Abstraction.meetArith(result, subNoChoose(left, right));
		}
	  }
	}
	return result;
  }  
  public String toString() {
	return getName();
  }  
  public static Range04 v() {
	return v;
  }  
}
