package edu.ksu.cis.bandera.abstraction.lib.integral;

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Bandera, a Java(TM) analysis and transformation toolkit           *
 * Copyright (C) 1998-2001 SAnToS Laboratories (santos@cis.ksu.edu)  *

 * All rights reserved.                                              *
 *                                                                   *
 * This work was done as a project in the SAnToS Laboratory,         *
 * Department of Computing and Information Sciences, Kansas State    *
 * University, USA (http://www.cis.ksu.edu/santos).                  *
 * It is understood that any modification not identified as such is  *
 * not covered by the preceding statement.                           *
 *                                                                   *
 * This work is free software; you can redistribute it and/or        *
 * modify it under the terms of the GNU Library General Public       *
 * License as published by the Free Software Foundation; either      *
 * version 2 of the License, or (at your option) any later version.  *
 *                                                                   *
 * This work is distributed in the hope that it will be useful,      *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of    *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU *
 * Library General Public License for more details.                  *
 *                                                                   *
 * You should have received a copy of the GNU Library General Public *
 * License along with this toolkit; if not, write to the             *
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,      *
 * Boston, MA  02111-1307, USA.                                      *
 *                                                                   *
 * Java is a trademark of Sun Microsystems, Inc.                     *
 *                                                                   *
 * To submit a bug report, send a comment, or get the latest news on *
 * this project and other SAnToS projects, please visit the web-site *
 *                http://www.cis.ksu.edu/santos                      *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
// This file was generated by Bandera (http://www.cis.ksu.edu/santos/bandera).
import edu.ksu.cis.bandera.abstraction.*;
public class Set0 extends IntegralAbstraction {
  private static final Set0 v = new Set0();
  public static final int R0 = 0;
  public static final int REST = 1;
  private Set0() {
  }  
  public static int abs(long n) {
	if (n == 0) return R0;
	if (n != 0) return REST;
	throw new RuntimeException("Set0 cannot abstract value '" + n + "'");
  }  
  public static int add(int left$, int right$) {
	if (left$ == R0 && right$ == R0) return R0;
	if (left$ == R0 && right$ == REST) return REST;
	if (left$ == REST && right$ == R0) return REST;
	if (left$ == REST && right$ == REST) return Abstraction.choose((1 << R0) | (1 << REST));
	throw new RuntimeException("Set0.add(" + left$ + ", " + right$ + ") is undefined");
  }  
  private static int addNoChoose(int left, int right) {
	int result = 0;
	switch (left) {
	  case 0:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 2;
			break;
		}
		break;
	  case 1:
		switch (right) {
		  case 0:
			result = 2;
			break;
		  case 1:
			result = 3;
			break;
		}
		break;
	}
	if (result == 0) throw new RuntimeException("Set0.addNoChoose(" + left + ", " + right + ") is undefined");
	return result;
  }  
  public static int addSet(int leftTokens, int rightTokens) {
	int result = -1;
	for (int left = 0; (1 << left) <= leftTokens; left++) {
	  if ((leftTokens & (1 << left)) == 0) continue;
	  for (int right = 0; (1 << right) <= rightTokens; right++) {
		if ((rightTokens & (1 << right)) != 0) {
		  if (result == -1) result = addNoChoose(left, right);
		  else result = Abstraction.meetArith(result, addNoChoose(left, right));
		}
	  }
	}
	return result;
  }  
  public static int div(int left$, int right$) {
	if (left$ == R0 && right$ == R0) return Abstraction.choose((1 << R0) | (1 << REST));
	if (left$ == R0 && right$ == REST) return R0;
	if (left$ == REST && right$ == R0) return Abstraction.choose((1 << R0) | (1 << REST));
	if (left$ == REST && right$ == REST) return Abstraction.choose((1 << R0) | (1 << REST));
	throw new RuntimeException("Set0.div(" + left$ + ", " + right$ + ") is undefined");
  }  
  private static int divNoChoose(int left, int right) {
	int result = 0;
	switch (left) {
	  case 0:
		switch (right) {
		  case 0:
			result = 3;
			break;
		  case 1:
			result = 1;
			break;
		}
		break;
	  case 1:
		switch (right) {
		  case 0:
			result = 3;
			break;
		  case 1:
			result = 3;
			break;
		}
		break;
	}
	if (result == 0) throw new RuntimeException("Set0.divNoChoose(" + left + ", " + right + ") is undefined");
	return result;
  }  
  public static int divSet(int leftTokens, int rightTokens) {
	int result = -1;
	for (int left = 0; (1 << left) <= leftTokens; left++) {
	  if ((leftTokens & (1 << left)) == 0) continue;
	  for (int right = 0; (1 << right) <= rightTokens; right++) {
		if ((rightTokens & (1 << right)) != 0) {
		  if (result == -1) result = divNoChoose(left, right);
		  else result = Abstraction.meetArith(result, divNoChoose(left, right));
		}
	  }
	}
	return result;
  }  
  public static boolean eq(int left$, int right$) {
	if (left$ == R0 && right$ == R0) return true;
	if (left$ == R0 && right$ == REST) return false;
	if (left$ == REST && right$ == R0) return false;
	if (left$ == REST && right$ == REST) return Abstraction.choose();
	throw new RuntimeException("Set0.eq(" + left$ + ", " + right$ + ") is undefined");
  }  
  private static byte eqNoChoose(int left, int right) {
	byte result = -1;
	switch (left) {
	  case 0:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 0;
			break;
		}
		break;
	  case 1:
		switch (right) {
		  case 0:
			result = 0;
			break;
		  case 1:
			result = 2;
			break;
		}
		break;
	}
	if (result == -1) throw new RuntimeException("Set0.eqNoChoose(" + left + ", " + right + ") is undefined");
	return result;
  }  
  public static byte eqSet(int leftTokens, int rightTokens) {
	byte result = -1;
	for (int left = 0; (1 << left) <= leftTokens; left++) {
	  if ((leftTokens & (1 << left)) == 0) continue;
	  for (int right = 0; (1 << right) <= rightTokens; right++) {
		if ((rightTokens & (1 << right)) != 0) {
		  if (result == -1) result = eqNoChoose(left, right);
		  else result = Abstraction.meetTest(result, eqNoChoose(left, right));
		}
	  }
	}
	return result;
  }  
  public static boolean ge(int left$, int right$) {
	if (left$ == R0 && right$ == R0) return true;
	if (left$ == R0 && right$ == REST) return Abstraction.choose();
	if (left$ == REST && right$ == R0) return Abstraction.choose();
	if (left$ == REST && right$ == REST) return Abstraction.choose();
	throw new RuntimeException("Set0.ge(" + left$ + ", " + right$ + ") is undefined");
  }  
  private static byte geNoChoose(int left, int right) {
	byte result = -1;
	switch (left) {
	  case 0:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 2;
			break;
		}
		break;
	  case 1:
		switch (right) {
		  case 0:
			result = 2;
			break;
		  case 1:
			result = 2;
			break;
		}
		break;
	}
	if (result == -1) throw new RuntimeException("Set0.geNoChoose(" + left + ", " + right + ") is undefined");
	return result;
  }  
  public static byte geSet(int leftTokens, int rightTokens) {
	byte result = -1;
	for (int left = 0; (1 << left) <= leftTokens; left++) {
	  if ((leftTokens & (1 << left)) == 0) continue;
	  for (int right = 0; (1 << right) <= rightTokens; right++) {
		if ((rightTokens & (1 << right)) != 0) {
		  if (result == -1) result = geNoChoose(left, right);
		  else result = Abstraction.meetTest(result, geNoChoose(left, right));
		}
	  }
	}
	return result;
  }  
  public static String getBASLRepresentation() {
	return
	  "abstraction Set0 extends integral \n"
	  + "  begin\n"
	  + "    TOKENS = {R0, REST};\n"
	  + "    DEFAULT = R0;\n"
	  + "    ONE2ONE = {R0};\n"
	  + "    abstract (n)\n"
	  + "      begin\n"
	  + "        n == 0 -> R0;\n"
	  + "        n != 0 -> REST;\n"
	  + "      end\n"
	  + "    operator + add \n"
	  + "      begin\n"
	  + "        (R0, R0) -> R0;\n"
	  + "        (R0, REST) -> REST;\n"
	  + "        (REST, R0) -> REST;\n"
	  + "        (REST, REST) -> {R0, REST};\n"
	  + "      end\n"
	  + "    operator - sub \n"
	  + "      begin\n"
	  + "        (R0, R0) -> R0;\n"
	  + "        (R0, REST) -> REST;\n"
	  + "        (REST, R0) -> REST;\n"
	  + "        (REST, REST) -> {R0, REST};\n"
	  + "      end\n"
	  + "    operator * mul \n"
	  + "      begin\n"
	  + "        (R0, R0) -> R0;\n"
	  + "        (R0, REST) -> R0;\n"
	  + "        (REST, R0) -> R0;\n"
	  + "        (REST, REST) -> REST;\n"
	  + "      end\n"
	  + "    operator / div \n"
	  + "      begin\n"
	  + "        (R0, R0) -> T;\n"
	  + "        (R0, REST) -> R0;\n"
	  + "        (REST, R0) -> T;\n"
	  + "        (REST, REST) -> {R0, REST};\n"
	  + "      end\n"
	  + "    operator % rem \n"
	  + "      begin\n"
	  + "        (R0, R0) -> T;\n"
	  + "        (R0, REST) -> R0;\n"
	  + "        (REST, R0) -> T;\n"
	  + "        (REST, REST) -> {R0, REST};\n"
	  + "      end\n"
	  + "    test == eq \n"
	  + "      begin\n"
	  + "        (R0, R0) -> TRUE;\n"
	  + "        (R0, REST) -> FALSE;\n"
	  + "        (REST, R0) -> FALSE;\n"
	  + "        (REST, REST) -> {TRUE, FALSE};\n"
	  + "      end\n"
	  + "    test != neq \n"
	  + "      begin\n"
	  + "        (R0, R0) -> FALSE;\n"
	  + "        (R0, REST) -> TRUE;\n"
	  + "        (REST, R0) -> TRUE;\n"
	  + "        (REST, REST) -> {TRUE, FALSE};\n"
	  + "      end\n"
	  + "    test < lt \n"
	  + "      begin\n"
	  + "        (R0, R0) -> FALSE;\n"
	  + "        (R0, REST) -> {TRUE, FALSE};\n"
	  + "        (REST, R0) -> {TRUE, FALSE};\n"
	  + "        (REST, REST) -> {TRUE, FALSE};\n"
	  + "      end\n"
	  + "    test <= le \n"
	  + "      begin\n"
	  + "        (R0, R0) -> TRUE;\n"
	  + "        (R0, REST) -> {TRUE, FALSE};\n"
	  + "        (REST, R0) -> {TRUE, FALSE};\n"
	  + "        (REST, REST) -> {TRUE, FALSE};\n"
	  + "      end\n"
	  + "    test > gt \n"
	  + "      begin\n"
	  + "        (R0, R0) -> FALSE;\n"
	  + "        (R0, REST) -> {TRUE, FALSE};\n"
	  + "        (REST, R0) -> {TRUE, FALSE};\n"
	  + "        (REST, REST) -> {TRUE, FALSE};\n"
	  + "      end\n"
	  + "    test >= ge \n"
	  + "      begin\n"
	  + "        (R0, R0) -> TRUE;\n"
	  + "        (R0, REST) -> {TRUE, FALSE};\n"
	  + "        (REST, R0) -> {TRUE, FALSE};\n"
	  + "        (REST, REST) -> {TRUE, FALSE};\n"
	  + "      end\n"
	  + "  end\n"
	;
  }  
  public static String getName() {
	return "Set0";
  }  
  public static int getNumOfTokens() {
	return 2;
  }  
  public static String getToken(int value) {
	switch(value) {
	  case R0: return "Set0.R0";
	  case REST: return "Set0.REST";
	}
	return "Set0.???";
  }  
  public static boolean gt(int left$, int right$) {
	if (left$ == R0 && right$ == R0) return false;
	if (left$ == R0 && right$ == REST) return Abstraction.choose();
	if (left$ == REST && right$ == R0) return Abstraction.choose();
	if (left$ == REST && right$ == REST) return Abstraction.choose();
	throw new RuntimeException("Set0.gt(" + left$ + ", " + right$ + ") is undefined");
  }  
  private static byte gtNoChoose(int left, int right) {
	byte result = -1;
	switch (left) {
	  case 0:
		switch (right) {
		  case 0:
			result = 0;
			break;
		  case 1:
			result = 2;
			break;
		}
		break;
	  case 1:
		switch (right) {
		  case 0:
			result = 2;
			break;
		  case 1:
			result = 2;
			break;
		}
		break;
	}
	if (result == -1) throw new RuntimeException("Set0.gtNoChoose(" + left + ", " + right + ") is undefined");
	return result;
  }  
  public static byte gtSet(int leftTokens, int rightTokens) {
	byte result = -1;
	for (int left = 0; (1 << left) <= leftTokens; left++) {
	  if ((leftTokens & (1 << left)) == 0) continue;
	  for (int right = 0; (1 << right) <= rightTokens; right++) {
		if ((rightTokens & (1 << right)) != 0) {
		  if (result == -1) result = gtNoChoose(left, right);
		  else result = Abstraction.meetTest(result, gtNoChoose(left, right));
		}
	  }
	}
	return result;
  }  
  public static boolean isOne2One(int value) {
	switch(value) {
	  case R0: return true;
	}
	return false;
  }  
  public static boolean le(int left$, int right$) {
	if (left$ == R0 && right$ == R0) return true;
	if (left$ == R0 && right$ == REST) return Abstraction.choose();
	if (left$ == REST && right$ == R0) return Abstraction.choose();
	if (left$ == REST && right$ == REST) return Abstraction.choose();
	throw new RuntimeException("Set0.le(" + left$ + ", " + right$ + ") is undefined");
  }  
  private static byte leNoChoose(int left, int right) {
	byte result = -1;
	switch (left) {
	  case 0:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 2;
			break;
		}
		break;
	  case 1:
		switch (right) {
		  case 0:
			result = 2;
			break;
		  case 1:
			result = 2;
			break;
		}
		break;
	}
	if (result == -1) throw new RuntimeException("Set0.leNoChoose(" + left + ", " + right + ") is undefined");
	return result;
  }  
  public static byte leSet(int leftTokens, int rightTokens) {
	byte result = -1;
	for (int left = 0; (1 << left) <= leftTokens; left++) {
	  if ((leftTokens & (1 << left)) == 0) continue;
	  for (int right = 0; (1 << right) <= rightTokens; right++) {
		if ((rightTokens & (1 << right)) != 0) {
		  if (result == -1) result = leNoChoose(left, right);
		  else result = Abstraction.meetTest(result, leNoChoose(left, right));
		}
	  }
	}
	return result;
  }  
  public static boolean lt(int left$, int right$) {
	if (left$ == R0 && right$ == R0) return false;
	if (left$ == R0 && right$ == REST) return Abstraction.choose();
	if (left$ == REST && right$ == R0) return Abstraction.choose();
	if (left$ == REST && right$ == REST) return Abstraction.choose();
	throw new RuntimeException("Set0.lt(" + left$ + ", " + right$ + ") is undefined");
  }  
  private static byte ltNoChoose(int left, int right) {
	byte result = -1;
	switch (left) {
	  case 0:
		switch (right) {
		  case 0:
			result = 0;
			break;
		  case 1:
			result = 2;
			break;
		}
		break;
	  case 1:
		switch (right) {
		  case 0:
			result = 2;
			break;
		  case 1:
			result = 2;
			break;
		}
		break;
	}
	if (result == -1) throw new RuntimeException("Set0.ltNoChoose(" + left + ", " + right + ") is undefined");
	return result;
  }  
  public static byte ltSet(int leftTokens, int rightTokens) {
	byte result = -1;
	for (int left = 0; (1 << left) <= leftTokens; left++) {
	  if ((leftTokens & (1 << left)) == 0) continue;
	  for (int right = 0; (1 << right) <= rightTokens; right++) {
		if ((rightTokens & (1 << right)) != 0) {
		  if (result == -1) result = ltNoChoose(left, right);
		  else result = Abstraction.meetTest(result, ltNoChoose(left, right));
		}
	  }
	}
	return result;
  }  
  public static int mul(int left$, int right$) {
	if (left$ == R0 && right$ == R0) return R0;
	if (left$ == R0 && right$ == REST) return R0;
	if (left$ == REST && right$ == R0) return R0;
	if (left$ == REST && right$ == REST) return REST;
	throw new RuntimeException("Set0.mul(" + left$ + ", " + right$ + ") is undefined");
  }  
  private static int mulNoChoose(int left, int right) {
	int result = 0;
	switch (left) {
	  case 0:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 1;
			break;
		}
		break;
	  case 1:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 2;
			break;
		}
		break;
	}
	if (result == 0) throw new RuntimeException("Set0.mulNoChoose(" + left + ", " + right + ") is undefined");
	return result;
  }  
  public static int mulSet(int leftTokens, int rightTokens) {
	int result = -1;
	for (int left = 0; (1 << left) <= leftTokens; left++) {
	  if ((leftTokens & (1 << left)) == 0) continue;
	  for (int right = 0; (1 << right) <= rightTokens; right++) {
		if ((rightTokens & (1 << right)) != 0) {
		  if (result == -1) result = mulNoChoose(left, right);
		  else result = Abstraction.meetArith(result, mulNoChoose(left, right));
		}
	  }
	}
	return result;
  }  
  public static boolean ne(int left$, int right$) {
	if (left$ == R0 && right$ == R0) return false;
	if (left$ == R0 && right$ == REST) return true;
	if (left$ == REST && right$ == R0) return true;
	if (left$ == REST && right$ == REST) return Abstraction.choose();
	throw new RuntimeException("Set0.ne(" + left$ + ", " + right$ + ") is undefined");
  }  
  private static byte neNoChoose(int left, int right) {
	byte result = -1;
	switch (left) {
	  case 0:
		switch (right) {
		  case 0:
			result = 0;
			break;
		  case 1:
			result = 1;
			break;
		}
		break;
	  case 1:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 2;
			break;
		}
		break;
	}
	if (result == -1) throw new RuntimeException("Set0.neNoChoose(" + left + ", " + right + ") is undefined");
	return result;
  }  
  public static byte neSet(int leftTokens, int rightTokens) {
	byte result = -1;
	for (int left = 0; (1 << left) <= leftTokens; left++) {
	  if ((leftTokens & (1 << left)) == 0) continue;
	  for (int right = 0; (1 << right) <= rightTokens; right++) {
		if ((rightTokens & (1 << right)) != 0) {
		  if (result == -1) result = neNoChoose(left, right);
		  else result = Abstraction.meetTest(result, neNoChoose(left, right));
		}
	  }
	}
	return result;
  }  
  public static int rem(int left$, int right$) {
	if (left$ == R0 && right$ == R0) return Abstraction.choose((1 << R0) | (1 << REST));
	if (left$ == R0 && right$ == REST) return R0;
	if (left$ == REST && right$ == R0) return Abstraction.choose((1 << R0) | (1 << REST));
	if (left$ == REST && right$ == REST) return Abstraction.choose((1 << R0) | (1 << REST));
	throw new RuntimeException("Set0.rem(" + left$ + ", " + right$ + ") is undefined");
  }  
  private static int remNoChoose(int left, int right) {
	int result = 0;
	switch (left) {
	  case 0:
		switch (right) {
		  case 0:
			result = 3;
			break;
		  case 1:
			result = 1;
			break;
		}
		break;
	  case 1:
		switch (right) {
		  case 0:
			result = 3;
			break;
		  case 1:
			result = 3;
			break;
		}
		break;
	}
	if (result == 0) throw new RuntimeException("Set0.remNoChoose(" + left + ", " + right + ") is undefined");
	return result;
  }  
  public static int remSet(int leftTokens, int rightTokens) {
	int result = -1;
	for (int left = 0; (1 << left) <= leftTokens; left++) {
	  if ((leftTokens & (1 << left)) == 0) continue;
	  for (int right = 0; (1 << right) <= rightTokens; right++) {
		if ((rightTokens & (1 << right)) != 0) {
		  if (result == -1) result = remNoChoose(left, right);
		  else result = Abstraction.meetArith(result, remNoChoose(left, right));
		}
	  }
	}
	return result;
  }  
  public static int sub(int left$, int right$) {
	if (left$ == R0 && right$ == R0) return R0;
	if (left$ == R0 && right$ == REST) return REST;
	if (left$ == REST && right$ == R0) return REST;
	if (left$ == REST && right$ == REST) return Abstraction.choose((1 << R0) | (1 << REST));
	throw new RuntimeException("Set0.sub(" + left$ + ", " + right$ + ") is undefined");
  }  
  private static int subNoChoose(int left, int right) {
	int result = 0;
	switch (left) {
	  case 0:
		switch (right) {
		  case 0:
			result = 1;
			break;
		  case 1:
			result = 2;
			break;
		}
		break;
	  case 1:
		switch (right) {
		  case 0:
			result = 2;
			break;
		  case 1:
			result = 3;
			break;
		}
		break;
	}
	if (result == 0) throw new RuntimeException("Set0.subNoChoose(" + left + ", " + right + ") is undefined");
	return result;
  }  
  public static int subSet(int leftTokens, int rightTokens) {
	int result = -1;
	for (int left = 0; (1 << left) <= leftTokens; left++) {
	  if ((leftTokens & (1 << left)) == 0) continue;
	  for (int right = 0; (1 << right) <= rightTokens; right++) {
		if ((rightTokens & (1 << right)) != 0) {
		  if (result == -1) result = subNoChoose(left, right);
		  else result = Abstraction.meetArith(result, subNoChoose(left, right));
		}
	  }
	}
	return result;
  }  
  public String toString() {
	return getName();
  }  
  public static Set0 v() {
	return v;
  }  
}
