package edu.ksu.cis.bandera.specification.predicate.node;

/* This file was generated by SableCC (http://www.sablecc.org/). */

import java.util.*;
import edu.ksu.cis.bandera.specification.predicate.analysis.*;

public final class AAndOrExp extends POrExp
{
	private PAndExp _andExp_;

	public AAndOrExp()
	{
	}
	public AAndOrExp(
		PAndExp _andExp_)
	{
		setAndExp(_andExp_);

	}
	public void apply(Switch sw)
	{
		((Analysis) sw).caseAAndOrExp(this);
	}
	public Object clone()
	{
		return new AAndOrExp(
			(PAndExp) cloneNode(_andExp_));
	}
	public PAndExp getAndExp()
	{
		return _andExp_;
	}
	void removeChild(Node child)
	{
		if(_andExp_ == child)
		{
			_andExp_ = null;
			return;
		}

	}
	void replaceChild(Node oldChild, Node newChild)
	{
		if(_andExp_ == oldChild)
		{
			setAndExp((PAndExp) newChild);
			return;
		}

	}
	public void setAndExp(PAndExp node)
	{
		if(_andExp_ != null)
		{
			_andExp_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_andExp_ = node;
	}
	public String toString()
	{
		return ""
			+ toString(_andExp_);
	}
}
