package edu.ksu.cis.bandera.specification.predicate.node;

/* This file was generated by SableCC (http://www.sablecc.org/). */

import java.util.*;
import edu.ksu.cis.bandera.specification.predicate.analysis.*;

public final class ABytePrimitiveType extends PPrimitiveType
{
	private TByte _byte_;

	public ABytePrimitiveType()
	{
	}
	public ABytePrimitiveType(
		TByte _byte_)
	{
		setByte(_byte_);

	}
	public void apply(Switch sw)
	{
		((Analysis) sw).caseABytePrimitiveType(this);
	}
	public Object clone()
	{
		return new ABytePrimitiveType(
			(TByte) cloneNode(_byte_));
	}
	public TByte getByte()
	{
		return _byte_;
	}
	void removeChild(Node child)
	{
		if(_byte_ == child)
		{
			_byte_ = null;
			return;
		}

	}
	void replaceChild(Node oldChild, Node newChild)
	{
		if(_byte_ == oldChild)
		{
			setByte((TByte) newChild);
			return;
		}

	}
	public void setByte(TByte node)
	{
		if(_byte_ != null)
		{
			_byte_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_byte_ = node;
	}
	public String toString()
	{
		return ""
			+ toString(_byte_);
	}
}
