package edu.ksu.cis.bandera.specification.predicate.node;

/* This file was generated by SableCC (http://www.sablecc.org/). */

import java.util.*;
import edu.ksu.cis.bandera.specification.predicate.analysis.*;

public final class AMinusAddExp extends PAddExp
{
	private PAddExp _addExp_;
	private TMinus _minus_;
	private PMultExp _multExp_;

	public AMinusAddExp()
	{
	}
	public AMinusAddExp(
		PAddExp _addExp_,
		TMinus _minus_,
		PMultExp _multExp_)
	{
		setAddExp(_addExp_);

		setMinus(_minus_);

		setMultExp(_multExp_);

	}
	public void apply(Switch sw)
	{
		((Analysis) sw).caseAMinusAddExp(this);
	}
	public Object clone()
	{
		return new AMinusAddExp(
			(PAddExp) cloneNode(_addExp_),
			(TMinus) cloneNode(_minus_),
			(PMultExp) cloneNode(_multExp_));
	}
	public PAddExp getAddExp()
	{
		return _addExp_;
	}
	public TMinus getMinus()
	{
		return _minus_;
	}
	public PMultExp getMultExp()
	{
		return _multExp_;
	}
	void removeChild(Node child)
	{
		if(_addExp_ == child)
		{
			_addExp_ = null;
			return;
		}

		if(_minus_ == child)
		{
			_minus_ = null;
			return;
		}

		if(_multExp_ == child)
		{
			_multExp_ = null;
			return;
		}

	}
	void replaceChild(Node oldChild, Node newChild)
	{
		if(_addExp_ == oldChild)
		{
			setAddExp((PAddExp) newChild);
			return;
		}

		if(_minus_ == oldChild)
		{
			setMinus((TMinus) newChild);
			return;
		}

		if(_multExp_ == oldChild)
		{
			setMultExp((PMultExp) newChild);
			return;
		}

	}
	public void setAddExp(PAddExp node)
	{
		if(_addExp_ != null)
		{
			_addExp_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_addExp_ = node;
	}
	public void setMinus(TMinus node)
	{
		if(_minus_ != null)
		{
			_minus_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_minus_ = node;
	}
	public void setMultExp(PMultExp node)
	{
		if(_multExp_ != null)
		{
			_multExp_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_multExp_ = node;
	}
	public String toString()
	{
		return ""
			+ toString(_addExp_)
			+ toString(_minus_)
			+ toString(_multExp_);
	}
}
