package edu.ksu.cis.bandera.specification.predicate.node;

/* This file was generated by SableCC (http://www.sablecc.org/). */

import java.util.*;
import edu.ksu.cis.bandera.specification.predicate.analysis.*;

public final class AOctLongLiteral extends PLiteral
{
	private TOctLongLiteral _octLongLiteral_;

	public AOctLongLiteral()
	{
	}
	public AOctLongLiteral(
		TOctLongLiteral _octLongLiteral_)
	{
		setOctLongLiteral(_octLongLiteral_);

	}
	public void apply(Switch sw)
	{
		((Analysis) sw).caseAOctLongLiteral(this);
	}
	public Object clone()
	{
		return new AOctLongLiteral(
			(TOctLongLiteral) cloneNode(_octLongLiteral_));
	}
	public TOctLongLiteral getOctLongLiteral()
	{
		return _octLongLiteral_;
	}
	void removeChild(Node child)
	{
		if(_octLongLiteral_ == child)
		{
			_octLongLiteral_ = null;
			return;
		}

	}
	void replaceChild(Node oldChild, Node newChild)
	{
		if(_octLongLiteral_ == oldChild)
		{
			setOctLongLiteral((TOctLongLiteral) newChild);
			return;
		}

	}
	public void setOctLongLiteral(TOctLongLiteral node)
	{
		if(_octLongLiteral_ != null)
		{
			_octLongLiteral_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_octLongLiteral_ = node;
	}
	public String toString()
	{
		return ""
			+ toString(_octLongLiteral_);
	}
}
