package edu.ksu.cis.bandera.specification.predicate.node;

/* This file was generated by SableCC (http://www.sablecc.org/). */

import java.util.*;
import edu.ksu.cis.bandera.specification.predicate.analysis.*;

public final class AOctIntLiteral extends PLiteral
{
	private TOctIntLiteral _octIntLiteral_;

	public AOctIntLiteral()
	{
	}
	public AOctIntLiteral(
		TOctIntLiteral _octIntLiteral_)
	{
		setOctIntLiteral(_octIntLiteral_);

	}
	public void apply(Switch sw)
	{
		((Analysis) sw).caseAOctIntLiteral(this);
	}
	public Object clone()
	{
		return new AOctIntLiteral(
			(TOctIntLiteral) cloneNode(_octIntLiteral_));
	}
	public TOctIntLiteral getOctIntLiteral()
	{
		return _octIntLiteral_;
	}
	void removeChild(Node child)
	{
		if(_octIntLiteral_ == child)
		{
			_octIntLiteral_ = null;
			return;
		}

	}
	void replaceChild(Node oldChild, Node newChild)
	{
		if(_octIntLiteral_ == oldChild)
		{
			setOctIntLiteral((TOctIntLiteral) newChild);
			return;
		}

	}
	public void setOctIntLiteral(TOctIntLiteral node)
	{
		if(_octIntLiteral_ != null)
		{
			_octIntLiteral_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_octIntLiteral_ = node;
	}
	public String toString()
	{
		return ""
			+ toString(_octIntLiteral_);
	}
}
