package edu.ksu.cis.bandera.specification.predicate.node;

/* This file was generated by SableCC (http://www.sablecc.org/). */

import java.util.*;
import edu.ksu.cis.bandera.specification.predicate.analysis.*;

public final class APrimaryPostfixExp extends PPostfixExp
{
	private PPrimaryExp _primaryExp_;

	public APrimaryPostfixExp()
	{
	}
	public APrimaryPostfixExp(
		PPrimaryExp _primaryExp_)
	{
		setPrimaryExp(_primaryExp_);

	}
	public void apply(Switch sw)
	{
		((Analysis) sw).caseAPrimaryPostfixExp(this);
	}
	public Object clone()
	{
		return new APrimaryPostfixExp(
			(PPrimaryExp) cloneNode(_primaryExp_));
	}
	public PPrimaryExp getPrimaryExp()
	{
		return _primaryExp_;
	}
	void removeChild(Node child)
	{
		if(_primaryExp_ == child)
		{
			_primaryExp_ = null;
			return;
		}

	}
	void replaceChild(Node oldChild, Node newChild)
	{
		if(_primaryExp_ == oldChild)
		{
			setPrimaryExp((PPrimaryExp) newChild);
			return;
		}

	}
	public void setPrimaryExp(PPrimaryExp node)
	{
		if(_primaryExp_ != null)
		{
			_primaryExp_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_primaryExp_ = node;
	}
	public String toString()
	{
		return ""
			+ toString(_primaryExp_);
	}
}
