package edu.ksu.cis.bandera.specification.predicate.node;

/* This file was generated by SableCC (http://www.sablecc.org/). */

import java.util.*;
import edu.ksu.cis.bandera.specification.predicate.analysis.*;

public final class AReturnValuePrimaryExp extends PPrimaryExp
{
	private TRetVal _retVal_;

	public AReturnValuePrimaryExp()
	{
	}
	public AReturnValuePrimaryExp(
		TRetVal _retVal_)
	{
		setRetVal(_retVal_);

	}
	public void apply(Switch sw)
	{
		((Analysis) sw).caseAReturnValuePrimaryExp(this);
	}
	public Object clone()
	{
		return new AReturnValuePrimaryExp(
			(TRetVal) cloneNode(_retVal_));
	}
	public TRetVal getRetVal()
	{
		return _retVal_;
	}
	void removeChild(Node child)
	{
		if(_retVal_ == child)
		{
			_retVal_ = null;
			return;
		}

	}
	void replaceChild(Node oldChild, Node newChild)
	{
		if(_retVal_ == oldChild)
		{
			setRetVal((TRetVal) newChild);
			return;
		}

	}
	public void setRetVal(TRetVal node)
	{
		if(_retVal_ != null)
		{
			_retVal_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_retVal_ = node;
	}
	public String toString()
	{
		return ""
			+ toString(_retVal_);
	}
}
