package edu.ksu.cis.bandera.specification.predicate.node;

/* This file was generated by SableCC (http://www.sablecc.org/). */

import java.util.*;
import edu.ksu.cis.bandera.specification.predicate.analysis.*;

public final class AStrongObjectNavigation extends PNavigation
{
	private TDot _dot_;
	private TId _id_;

	public AStrongObjectNavigation()
	{
	}
	public AStrongObjectNavigation(
		TDot _dot_,
		TId _id_)
	{
		setDot(_dot_);

		setId(_id_);

	}
	public void apply(Switch sw)
	{
		((Analysis) sw).caseAStrongObjectNavigation(this);
	}
	public Object clone()
	{
		return new AStrongObjectNavigation(
			(TDot) cloneNode(_dot_),
			(TId) cloneNode(_id_));
	}
	public TDot getDot()
	{
		return _dot_;
	}
	public TId getId()
	{
		return _id_;
	}
	void removeChild(Node child)
	{
		if(_dot_ == child)
		{
			_dot_ = null;
			return;
		}

		if(_id_ == child)
		{
			_id_ = null;
			return;
		}

	}
	void replaceChild(Node oldChild, Node newChild)
	{
		if(_dot_ == oldChild)
		{
			setDot((TDot) newChild);
			return;
		}

		if(_id_ == oldChild)
		{
			setId((TId) newChild);
			return;
		}

	}
	public void setDot(TDot node)
	{
		if(_dot_ != null)
		{
			_dot_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_dot_ = node;
	}
	public void setId(TId node)
	{
		if(_id_ != null)
		{
			_id_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_id_ = node;
	}
	public String toString()
	{
		return ""
			+ toString(_dot_)
			+ toString(_id_);
	}
}
