package edu.ksu.cis.bandera.specification.predicate.node;

/* This file was generated by SableCC (http://www.sablecc.org/). */

import java.util.*;
import edu.ksu.cis.bandera.specification.predicate.analysis.*;

public final class AStrongModBinOp extends PBinOp
{
	private TStrongMod _strongMod_;

	public AStrongModBinOp()
	{
	}
	public AStrongModBinOp(
		TStrongMod _strongMod_)
	{
		setStrongMod(_strongMod_);

	}
	public void apply(Switch sw)
	{
		((Analysis) sw).caseAStrongModBinOp(this);
	}
	public Object clone()
	{
		return new AStrongModBinOp(
			(TStrongMod) cloneNode(_strongMod_));
	}
	public TStrongMod getStrongMod()
	{
		return _strongMod_;
	}
	void removeChild(Node child)
	{
		if(_strongMod_ == child)
		{
			_strongMod_ = null;
			return;
		}

	}
	void replaceChild(Node oldChild, Node newChild)
	{
		if(_strongMod_ == oldChild)
		{
			setStrongMod((TStrongMod) newChild);
			return;
		}

	}
	public void setStrongMod(TStrongMod node)
	{
		if(_strongMod_ != null)
		{
			_strongMod_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_strongMod_ = node;
	}
	public String toString()
	{
		return ""
			+ toString(_strongMod_);
	}
}
