package edu.ksu.cis.bandera.specification.predicate.node;

/* This file was generated by SableCC (http://www.sablecc.org/). */

import java.util.*;
import edu.ksu.cis.bandera.specification.predicate.analysis.*;

public final class AXorExclusiveOrExp extends PExclusiveOrExp
{
	private PExclusiveOrExp _exclusiveOrExp_;
	private TBitXor _bitXor_;
	private PBitAndExp _bitAndExp_;

	public AXorExclusiveOrExp()
	{
	}
	public AXorExclusiveOrExp(
		PExclusiveOrExp _exclusiveOrExp_,
		TBitXor _bitXor_,
		PBitAndExp _bitAndExp_)
	{
		setExclusiveOrExp(_exclusiveOrExp_);

		setBitXor(_bitXor_);

		setBitAndExp(_bitAndExp_);

	}
	public void apply(Switch sw)
	{
		((Analysis) sw).caseAXorExclusiveOrExp(this);
	}
	public Object clone()
	{
		return new AXorExclusiveOrExp(
			(PExclusiveOrExp) cloneNode(_exclusiveOrExp_),
			(TBitXor) cloneNode(_bitXor_),
			(PBitAndExp) cloneNode(_bitAndExp_));
	}
	public PBitAndExp getBitAndExp()
	{
		return _bitAndExp_;
	}
	public TBitXor getBitXor()
	{
		return _bitXor_;
	}
	public PExclusiveOrExp getExclusiveOrExp()
	{
		return _exclusiveOrExp_;
	}
	void removeChild(Node child)
	{
		if(_exclusiveOrExp_ == child)
		{
			_exclusiveOrExp_ = null;
			return;
		}

		if(_bitXor_ == child)
		{
			_bitXor_ = null;
			return;
		}

		if(_bitAndExp_ == child)
		{
			_bitAndExp_ = null;
			return;
		}

	}
	void replaceChild(Node oldChild, Node newChild)
	{
		if(_exclusiveOrExp_ == oldChild)
		{
			setExclusiveOrExp((PExclusiveOrExp) newChild);
			return;
		}

		if(_bitXor_ == oldChild)
		{
			setBitXor((TBitXor) newChild);
			return;
		}

		if(_bitAndExp_ == oldChild)
		{
			setBitAndExp((PBitAndExp) newChild);
			return;
		}

	}
	public void setBitAndExp(PBitAndExp node)
	{
		if(_bitAndExp_ != null)
		{
			_bitAndExp_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_bitAndExp_ = node;
	}
	public void setBitXor(TBitXor node)
	{
		if(_bitXor_ != null)
		{
			_bitXor_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_bitXor_ = node;
	}
	public void setExclusiveOrExp(PExclusiveOrExp node)
	{
		if(_exclusiveOrExp_ != null)
		{
			_exclusiveOrExp_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_exclusiveOrExp_ = node;
	}
	public String toString()
	{
		return ""
			+ toString(_exclusiveOrExp_)
			+ toString(_bitXor_)
			+ toString(_bitAndExp_);
	}
}
