package edu.ksu.cis.bandera.specification.predicate.node;

/* This file was generated by SableCC (http://www.sable.mcgill.ca/sablecc/). */

public abstract class PPropositionDefinition extends Node
{
	public abstract TId getId(); // robbyjo's patch
}
