package edu.ksu.cis.bandera.specification.predicate.node;

/* This file was generated by SableCC (http://www.sablecc.org/). */

import edu.ksu.cis.bandera.specification.predicate.analysis.*;

public final class TBitComplement extends Token
{
	public TBitComplement()
	{
		super.setText("~");
	}
	public TBitComplement(int line, int pos)
	{
		super.setText("~");
		setLine(line);
		setPos(pos);
	}
	public void apply(Switch sw)
	{
		((Analysis) sw).caseTBitComplement(this);
	}
	public Object clone()
	{
	  return new TBitComplement(getLine(), getPos());
	}
	public void setText(String text)
	{
		throw new RuntimeException("Cannot change TBitComplement text.");
	}
}
