package edu.ksu.cis.bandera.specification.predicate.node;

/* This file was generated by SableCC (http://www.sablecc.org/). */

import edu.ksu.cis.bandera.specification.predicate.analysis.*;

public final class TBitAnd extends Token
{
	public TBitAnd()
	{
		super.setText("&");
	}
	public TBitAnd(int line, int pos)
	{
		super.setText("&");
		setLine(line);
		setPos(pos);
	}
	public void apply(Switch sw)
	{
		((Analysis) sw).caseTBitAnd(this);
	}
	public Object clone()
	{
	  return new TBitAnd(getLine(), getPos());
	}
	public void setText(String text)
	{
		throw new RuntimeException("Cannot change TBitAnd text.");
	}
}
