package edu.ksu.cis.bandera.specification.predicate.node;

/* This file was generated by SableCC (http://www.sablecc.org/). */

import edu.ksu.cis.bandera.specification.predicate.analysis.*;

public final class TEqual extends Token
{
	public TEqual()
	{
		super.setText("==");
	}
	public TEqual(int line, int pos)
	{
		super.setText("==");
		setLine(line);
		setPos(pos);
	}
	public void apply(Switch sw)
	{
		((Analysis) sw).caseTEqual(this);
	}
	public Object clone()
	{
	  return new TEqual(getLine(), getPos());
	}
	public void setText(String text)
	{
		throw new RuntimeException("Cannot change TEqual text.");
	}
}
