package edu.ksu.cis.bandera.specification.predicate.node;

/* This file was generated by SableCC (http://www.sablecc.org/). */

import edu.ksu.cis.bandera.specification.predicate.analysis.*;

public final class TGreater extends Token
{
	public TGreater()
	{
		super.setText(">");
	}
	public TGreater(int line, int pos)
	{
		super.setText(">");
		setLine(line);
		setPos(pos);
	}
	public void apply(Switch sw)
	{
		((Analysis) sw).caseTGreater(this);
	}
	public Object clone()
	{
	  return new TGreater(getLine(), getPos());
	}
	public void setText(String text)
	{
		throw new RuntimeException("Cannot change TGreater text.");
	}
}
