package edu.ksu.cis.bandera.specification.predicate.node;

/* This file was generated by SableCC (http://www.sablecc.org/). */

import edu.ksu.cis.bandera.specification.predicate.analysis.*;

public final class TInstanceof extends Token
{
	public TInstanceof()
	{
		super.setText("instanceof");
	}
	public TInstanceof(int line, int pos)
	{
		super.setText("instanceof");
		setLine(line);
		setPos(pos);
	}
	public void apply(Switch sw)
	{
		((Analysis) sw).caseTInstanceof(this);
	}
	public Object clone()
	{
	  return new TInstanceof(getLine(), getPos());
	}
	public void setText(String text)
	{
		throw new RuntimeException("Cannot change TInstanceof text.");
	}
}
