package edu.ksu.cis.bandera.specification.predicate.node;

/* This file was generated by SableCC (http://www.sablecc.org/). */

import edu.ksu.cis.bandera.specification.predicate.analysis.*;

public final class TStar extends Token
{
	public TStar()
	{
		super.setText("*");
	}
	public TStar(int line, int pos)
	{
		super.setText("*");
		setLine(line);
		setPos(pos);
	}
	public void apply(Switch sw)
	{
		((Analysis) sw).caseTStar(this);
	}
	public Object clone()
	{
	  return new TStar(getLine(), getPos());
	}
	public void setText(String text)
	{
		throw new RuntimeException("Cannot change TStar text.");
	}
}
