package edu.ksu.cis.bandera.specification.predicate.node;

/* This file was generated by SableCC (http://www.sablecc.org/). */

import edu.ksu.cis.bandera.specification.predicate.analysis.*;

public final class TThread extends Token
{
	public TThread()
	{
		super.setText("$thread");
	}
	public TThread(int line, int pos)
	{
		super.setText("$thread");
		setLine(line);
		setPos(pos);
	}
	public void apply(Switch sw)
	{
		((Analysis) sw).caseTThread(this);
	}
	public Object clone()
	{
	  return new TThread(getLine(), getPos());
	}
	public void setText(String text)
	{
		throw new RuntimeException("Cannot change TThread text.");
	}
}
