package edu.ksu.cis.bandera.specification.predicate.node;

/* This file was generated by SableCC (http://www.sablecc.org/). */

import edu.ksu.cis.bandera.specification.predicate.analysis.*;

public final class X2PComment extends XPComment
{
	private PComment _pComment_;

	public X2PComment()
	{
	}
	public X2PComment(
		PComment _pComment_)
	{
		setPComment(_pComment_);
	}
	public void apply(Switch sw)
	{
		throw new RuntimeException("Switch not supported.");
	}
	public Object clone()
	{
		throw new RuntimeException("Unsupported Operation");
	}
	public PComment getPComment()
	{
		return _pComment_;
	}
	void removeChild(Node child)
	{
		if(_pComment_ == child)
		{
			_pComment_ = null;
		}
	}
	void replaceChild(Node oldChild, Node newChild)
	{
	}
	public void setPComment(PComment node)
	{
		if(_pComment_ != null)
		{
			_pComment_.parent(null);
		}

		if(node != null)
		{
			if(node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_pComment_ = node;
	}
	public String toString()
	{
		return "" +
			toString(_pComment_);
	}
}
